from tkinter import *
from tkinter import ttk

root = Tk()

content = ttk.Frame(root, padding=(3,3,12,12))
frame = ttk.Frame(content, borderwidth=5, relief="sunken", width=200, height=100)
imageEx = PhotoImage(file='image.gif')
Label(image=imageEx).grid(row=0, column=10, sticky=(N,W))

""" basic character information declaration """
name = ttk.Entry(content, width=43)
namelbl = ttk.Label(content, text="Character Name")
align = ttk.Entry(content, width=10) 
alignlbl = ttk.Label(content, text="Alignment")
player = ttk.Entry(content, width=43)
playerlbl = ttk.Label(content, text="Player")
level = ttk.Entry(content, width=54)
levellbl = ttk.Label(content, text="Character Level")
deity = ttk.Entry(content, width=21)
deitylbl = ttk.Label(content, text="Deity")
homeland = ttk.Entry(content, width=21)
homelandlbl = ttk.Label(content, text="Homeland")
race = ttk.Entry(content, width=29)
racelbl = ttk.Label(content, text="Race")
size = ttk.Entry(content, width=13)
sizelbl = ttk.Label(content, text="Size")
gender = ttk.Entry(content, width=6)
genderlbl = ttk.Label(content, text="Gender")
age = ttk.Entry(content, width=3)
agelbl = ttk.Label(content, text="Age")
height = ttk.Entry(content, width=10)
heightlbl = ttk.Label(content, text="Height")
weight = ttk.Entry(content, width=10)
weightlbl = ttk.Label(content, text="Weight")
hair = ttk.Entry(content, width=10)
hairlbl = ttk.Label(content, text="Hair")
eyes = ttk.Entry(content, width=10)
eyeslbl = ttk.Label(content, text="Eyes")


""" basic character information placement """
content.grid(    column=0, row=0)
name.grid(       column=1, row=2, columnspan=3)
namelbl.grid(    column=1, row=3, sticky=(N, W))
align.grid(      column=4, row=2, sticky=(W), columnspan=1)
alignlbl.grid(   column=4, row=3, sticky=(N, W))
player.grid(     column=5, row=2, sticky=(W), columnspan=4)
playerlbl.grid(  column=5, row=3, sticky=(N,W))
level.grid(      column=1, row=4, sticky=(W), columnspan=4)
levellbl.grid(   column=1, row=5, sticky=(N,W))
deity.grid(      column=5, row=4, sticky=(W), columnspan=2)
deitylbl.grid(   column=5, row=5, sticky=(N,W))
homeland.grid(   column=7, row=4, sticky=(W), columnspan=2)
homelandlbl.grid(column=7, row=5, sticky=(N,W))
race.grid(       column=1, row=7, sticky=(W), columnspan=2)
racelbl.grid(    column=1, row=8, sticky=(N,W))
size.grid(       column=3, row=7, sticky=(W), columnspan=1)
sizelbl.grid(    column=3, row=8, sticky=(N,W))
gender.grid(     column=4, row=7, sticky=(W))
genderlbl.grid(  column=4, row=8, sticky=(N,W))
age.grid(        column=4, row=7, sticky=(E))
agelbl.grid(     column=4, row=8, sticky=(N,E))
height.grid(     column=5, row=7, sticky=(W), columnspan=1)
heightlbl.grid(  column=5, row=8, sticky=(N,W))
weight.grid(     column=6, row=7, sticky=(W), columnspan=1)
weightlbl.grid(  column=6, row=8, sticky=(N,W))
hair.grid(       column=7, row=7, sticky=(W), columnspan=1)
hairlbl.grid(    column=7, row=8, sticky=(N,W))
eyes.grid(       column=8, row=7, sticky=(W), columnspan=1)
eyeslbl.grid(    column=8, row=8, sticky=(N,W))


""" stats declaration """
abnamelbl = ttk.Label(content, text="Ability Name")
abscorelbl = ttk.Label(content, text = "Abl Score | Mod")
tempadjlbl = ttk.Label(content, text = "Temp Adj | Mod")
strlbl = ttk.Label(content, text = "Strength")
strabs = ttk.Entry(content, width = 6)
strabm = ttk.Entry(content, width = 6)
strtma = ttk.Entry(content, width = 6)
strtmm = ttk.Entry(content, width = 6)
dexlbl = ttk.Label(content, text = "Dexterity")
dexabs = ttk.Entry(content, width = 6)
dexabm = ttk.Entry(content, width = 6)
dextma = ttk.Entry(content, width = 6)
dextmm = ttk.Entry(content, width = 6)
conlbl = ttk.Label(content, text = "Constitution")
conabs = ttk.Entry(content, width = 6)
conabm = ttk.Entry(content, width = 6)
contma = ttk.Entry(content, width = 6)
contmm = ttk.Entry(content, width = 6)
intlbl = ttk.Label(content, text = "Intelligence")
intabs = ttk.Entry(content, width = 6)
intabm = ttk.Entry(content, width = 6)
inttma = ttk.Entry(content, width = 6)
inttmm = ttk.Entry(content, width = 6)
wislbl = ttk.Label(content, text = "Wisdom")
wisabs = ttk.Entry(content, width = 6)
wisabm = ttk.Entry(content, width = 6)
wistma = ttk.Entry(content, width = 6)
wistmm = ttk.Entry(content, width = 6)
chalbl = ttk.Label(content, text = "Charisma")
chaabs = ttk.Entry(content, width = 6)
chaabm = ttk.Entry(content, width = 6)
chatma = ttk.Entry(content, width = 6)
chatmm = ttk.Entry(content, width = 6)
hplbl = ttk.Label(content, text = "Total HP")
hp = ttk.Entry(content, width = 10)
drlbl = ttk.Label(content, text = " DR")
dmgres = ttk.Entry(content, width = 6)
wcrlbl = ttk.Label(content, text = "  Wounds / HP")
wcr1 = ttk.Entry(content, width = 31)
wcr2 = ttk.Entry(content, width = 31)
nldlbl = ttk.Label(content, text = "  Non-Lethal Damage")
nld = ttk.Entry(content, width = 31)
inilbl = ttk.Label(content, text = "  Initiative")
initot = ttk.Entry(content, width = 5)
inidex = ttk.Entry(content, width = 4)
inimsc = ttk.Entry(content, width = 4)
inip = ttk.Label(content, text = "+")
inie = ttk.Label(content, text = "=")

""" stats placement """
abnamelbl.grid(  column=1, row=9, sticky = (W))
abscorelbl.grid( column=2, row=9, sticky = (W))
tempadjlbl.grid( column=3, row=9, sticky = (W))
strlbl.grid(     column=1, row=10, columnspan = 2, sticky = (W))
strabs.grid(     column=2, row=10, sticky = (W))
strabm.grid(     column=2, row=10, sticky = (E), padx = 5)
strtma.grid(     column=3, row=10, sticky = (W))
strtmm.grid(     column=3, row=10, sticky = (E))
dexlbl.grid(     column=1, row=11, columnspan = 2, sticky = (W))
dexabs.grid(     column=2, row=11, sticky = (W))
dexabm.grid(     column=2, row=11, sticky = (E), padx = 5)
dextma.grid(     column=3, row=11, sticky = (W))
dextmm.grid(     column=3, row=11, sticky = (E))
conlbl.grid(     column=1, row=12, columnspan = 2, sticky = (W))
conabs.grid(     column=2, row=12, sticky = (W))
conabm.grid(     column=2, row=12, sticky = (E), padx = 5)
contma.grid(     column=3, row=12, sticky = (W))
contmm.grid(     column=3, row=12, sticky = (E))
intlbl.grid(     column=1, row=13, columnspan = 2, sticky = (W))
intabs.grid(     column=2, row=13, sticky = (W))
intabm.grid(     column=2, row=13, sticky = (E), padx = 5)
inttma.grid(     column=3, row=13, sticky = (W))
inttmm.grid(     column=3, row=13, sticky = (E))
wislbl.grid(     column=1, row=14, columnspan = 2, sticky = (W))
wisabs.grid(     column=2, row=14, sticky = (W))
wisabm.grid(     column=2, row=14, sticky = (E), padx = 5)
wistma.grid(     column=3, row=14, sticky = (W))
wistmm.grid(     column=3, row=14, sticky = (E))
chalbl.grid(     column=1, row=15, columnspan = 2, sticky = (W))
chaabs.grid(     column=2, row=15, sticky = (W))
chaabm.grid(     column=2, row=15, sticky = (E), padx = 5)
chatma.grid(     column=3, row=15, sticky = (W))
chatmm.grid(     column=3, row=15, sticky = (E))
hplbl.grid(      column=4, row=9, sticky = (E))
hp.grid(         column=5, row=9, sticky = (W))
drlbl.grid(      column=6, row=9, sticky = (W))
dmgres.grid(     column=6, row=9, sticky = (E))
wcrlbl.grid(     column=4, row=10, columnspan = 2, sticky = (W))
wcr1.grid(       column=4, row=11, columnspan = 3, sticky = (NE))
wcr2.grid(       column=4, row=12, columnspan = 3, sticky = (NE))
nldlbl.grid(     column=4, row=13, columnspan = 2, sticky = (W))
nld.grid(        column=4, row=14, columnspan = 3, sticky = (NE))
inilbl.grid(     column=4, row=15, columnspan = 2, sticky = (W))
initot.grid(     column=5, row=15, sticky = (E), padx = 5)
inie.grid(       column=5, row=15, sticky = (E))
inidex.grid(     column=6, row=15, sticky = (E))
inip.grid(       column=6, row=15)
inimsc.grid(     column=6, row=15, sticky = (W))

root.mainloop()
