from tkinter import *
from tkinter import ttk

class PathfinderGUI(ttk.Frame):
    def __init__(self, name='pathfindergui'):
        ttk.Frame.__init__(self, name=name)
        self.pack(expand=Y, fill=BOTH)
        self.master.title('NoWhere Pathfinder Assistant')
        Panel = Frame(self, name='char')
        Panel.pack(side=TOP, fill=BOTH, expand=Y)

        character =ttk.Notebook(Panel, name='character')

        character.enable_traversal()
        character.pack(fill=BOTH, expand=Y, padx=2, pady=3)
        self._create_information_tab(character)
        self._create_abilities_tab(character)
        self._create_inventory_tab(character)
        self._create_weapons_tab(character)
        self._create_armor_tab(character)
        self._create_skills_tab(character)
        self._create_spells_tab(character)
        
    def _create_information_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)
            
            """ basic character information declaration """
            name = ttk.Entry(content, width=45)
            namelbl = ttk.Label(content, text="Character Name", foreground='grey')
            align = ttk.Entry(content, width=10) 
            alignlbl = ttk.Label(content, text="Alignment", foreground='grey')
            player = ttk.Entry(content, width=43)
            playerlbl = ttk.Label(content, text="Player", foreground='grey')
            level = ttk.Entry(content, width=56)
            levellbl = ttk.Label(content, text="Character Level", foreground='grey')
            deity = ttk.Entry(content, width=21)
            deitylbl = ttk.Label(content, text="Deity", foreground='grey')
            homeland = ttk.Entry(content, width=21)
            homelandlbl = ttk.Label(content, text="Homeland", foreground='grey')
            race = ttk.Entry(content, width=29)
            racelbl = ttk.Label(content, text="Race", foreground='grey')
            size = ttk.Entry(content, width=15)
            sizelbl = ttk.Label(content, text="Size", foreground='grey')
            gender = ttk.Entry(content, width=6)
            genderlbl = ttk.Label(content, text="Gender", foreground='grey')
            age = ttk.Entry(content, width=3)
            agelbl = ttk.Label(content, text="Age", foreground='grey')
            height = ttk.Entry(content, width=10)
            heightlbl = ttk.Label(content, text="Height", foreground='grey')
            weight = ttk.Entry(content, width=10)
            weightlbl = ttk.Label(content, text="Weight", foreground='grey')
            hair = ttk.Entry(content, width=10)
            hairlbl = ttk.Label(content, text="Hair", foreground='grey')
            eyes = ttk.Entry(content, width=10)
            eyeslbl = ttk.Label(content, text="Eyes", foreground='grey')

            """ basic character information placement """
            content.grid(    column=0, row=0)
            name.grid(       column=1, row=2, columnspan=3)
            namelbl.grid(    column=1, row=3, sticky=(N, W))
            align.grid(      column=4, row=2, sticky=(W), columnspan=1)
            alignlbl.grid(   column=4, row=3, sticky=(N, W))
            player.grid(     column=5, row=2, sticky=(W), columnspan=4)
            playerlbl.grid(  column=5, row=3, sticky=(N,W))
            level.grid(      column=1, row=4, sticky=(W), columnspan=4)
            levellbl.grid(   column=1, row=5, sticky=(N,W))
            deity.grid(      column=5, row=4, sticky=(W), columnspan=2)
            deitylbl.grid(   column=5, row=5, sticky=(N,W))
            homeland.grid(   column=7, row=4, sticky=(W), columnspan=2)
            homelandlbl.grid(column=7, row=5, sticky=(N,W))
            race.grid(       column=1, row=7, sticky=(W), columnspan=2)
            racelbl.grid(    column=1, row=8, sticky=(N,W))
            size.grid(       column=3, row=7, sticky=(W), columnspan=1)
            sizelbl.grid(    column=3, row=8, sticky=(N,W))
            gender.grid(     column=4, row=7, sticky=(W))
            genderlbl.grid(  column=4, row=8, sticky=(N,W))
            age.grid(        column=4, row=7, sticky=(E))
            agelbl.grid(     column=4, row=8, sticky=(N,E))
            height.grid(     column=5, row=7, sticky=(W), columnspan=1)
            heightlbl.grid(  column=5, row=8, sticky=(N,W))
            weight.grid(     column=6, row=7, sticky=(W), columnspan=1)
            weightlbl.grid(  column=6, row=8, sticky=(N,W))
            hair.grid(       column=7, row=7, sticky=(W), columnspan=1)
            hairlbl.grid(    column=7, row=8, sticky=(N,W))
            eyes.grid(       column=8, row=7, sticky=(W), columnspan=1)
            eyeslbl.grid(    column=8, row=8, sticky=(N,W))

            character.add(content, text='Information')
            
    def _create_abilities_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            """ ability declaration """
            abnamelbl = ttk.Label(content, text="Ability Name", background='black', foreground='white')
            abscorelbl = ttk.Label(content, text = "Abl Score | Mod", background='black', foreground='white')
            tempadjlbl = ttk.Label(content, text = "Temp Adj | Mod", background='black', foreground='white')
            strlbl = ttk.Label(content, text = "   Strength    "  , background='black', foreground='white')
            strabs = ttk.Entry(content, width = 6)
            strabm = ttk.Entry(content, width = 6)
            strtma = ttk.Entry(content, width = 6)
            strtmm = ttk.Entry(content, width = 6) 
            dexlbl = ttk.Label(content, text = "   Dexterity    ", background='black', foreground='white')
            dexabs = ttk.Entry(content, width = 6)
            dexabm = ttk.Entry(content, width = 6)
            dextma = ttk.Entry(content, width = 6)
            dextmm = ttk.Entry(content, width = 6)
            conlbl = ttk.Label(content, text = "Constitution", background='black', foreground='white')
            conabs = ttk.Entry(content, width = 6)
            conabm = ttk.Entry(content, width = 6)
            contma = ttk.Entry(content, width = 6)
            contmm = ttk.Entry(content, width = 6)
            intlbl = ttk.Label(content, text = " Intelligence ", background='black', foreground='white')
            intabs = ttk.Entry(content, width = 6)
            intabm = ttk.Entry(content, width = 6)
            inttma = ttk.Entry(content, width = 6)
            inttmm = ttk.Entry(content, width = 6)
            wislbl = ttk.Label(content, text = "   Wisdom    ", background='black', foreground='white')
            wisabs = ttk.Entry(content, width = 6)
            wisabm = ttk.Entry(content, width = 6)
            wistma = ttk.Entry(content, width = 6)
            wistmm = ttk.Entry(content, width = 6)
            chalbl = ttk.Label(content, text = "   Charisma  ", background='black', foreground='white')
            chaabs = ttk.Entry(content, width = 6)
            chaabm = ttk.Entry(content, width = 6)
            chatma = ttk.Entry(content, width = 6)
            chatmm = ttk.Entry(content, width = 6)

            """ ability placement """
            abnamelbl.grid(  column=1, row=9, sticky = (W))
            abscorelbl.grid( column=2, row=9, sticky = (W))
            tempadjlbl.grid( column=3, row=9, sticky = (W))
            strlbl.grid(     column=1, row=10, columnspan = 2, sticky = (W))
            strabs.grid(     column=2, row=10, sticky = (W))
            strabm.grid(     column=2, row=10, sticky = (E), padx = 5)
            strtma.grid(     column=3, row=10, sticky = (W), padx = 3)
            strtmm.grid(     column=3, row=10, sticky = (E), padx = 8)
            dexlbl.grid(     column=1, row=11, columnspan = 2, sticky = (W))
            dexabs.grid(     column=2, row=11, sticky = (W))
            dexabm.grid(     column=2, row=11, sticky = (E), padx = 5)
            dextma.grid(     column=3, row=11, sticky = (W), padx = 3)
            dextmm.grid(     column=3, row=11, sticky = (E), padx = 8)
            conlbl.grid(     column=1, row=12, columnspan = 2, sticky = (W))
            conabs.grid(     column=2, row=12, sticky = (W))
            conabm.grid(     column=2, row=12, sticky = (E), padx = 5)
            contma.grid(     column=3, row=12, sticky = (W), padx = 3)
            contmm.grid(     column=3, row=12, sticky = (E), padx = 8)
            intlbl.grid(     column=1, row=13, columnspan = 2, sticky = (W))
            intabs.grid(     column=2, row=13, sticky = (W))
            intabm.grid(     column=2, row=13, sticky = (E), padx = 5)
            inttma.grid(     column=3, row=13, sticky = (W), padx = 3)
            inttmm.grid(     column=3, row=13, sticky = (E), padx = 8)
            wislbl.grid(     column=1, row=14, columnspan = 2, sticky = (W))
            wisabs.grid(     column=2, row=14, sticky = (W))
            wisabm.grid(     column=2, row=14, sticky = (E), padx = 5)
            wistma.grid(     column=3, row=14, sticky = (W), padx = 3)
            wistmm.grid(     column=3, row=14, sticky = (E), padx = 8)
            chalbl.grid(     column=1, row=15, columnspan = 2, sticky = (W))
            chaabs.grid(     column=2, row=15, sticky = (W))
            chaabm.grid(     column=2, row=15, sticky = (E), padx = 5)
            chatma.grid(     column=3, row=15, sticky = (W), padx = 3)
            chatmm.grid(     column=3, row=15, sticky = (E), padx = 8)

            """ Basic attribute declaration """
            hplbl = ttk.Label(content, text = "Total HP", background='black', foreground='white')
            hp = ttk.Entry(content, width = 10)
            drlbl = ttk.Label(content, text = "DR", foreground='grey')
            dmgres = ttk.Entry(content, width = 5)
            speedlbl = ttk.Label(content, text = "Speed", background='black', foreground='white')
            bspeed = ttk.Entry(content, width = 10)
            bpdlbl = ttk.Label(content, text = " Base", foreground='grey')
            aspeed = ttk.Entry(content, width = 10)
            asplbl = ttk.Label(content, text = " w/ Armor", foreground='grey')
            sspeed = ttk.Entry(content, width = 5)
            ssplbl = ttk.Label(content, text = "Swim", foreground='grey')
            fspeed = ttk.Entry(content, width = 4)
            fsplbl = ttk.Label(content, text = "Fly", foreground='grey')
            maneuv = ttk.Entry(content, width = 10)
            mnvlbl = ttk.Label(content, text = "Maneuver", foreground='grey')
            cspeed = ttk.Entry(content, width = 5)
            csplbl = ttk.Label(content, text = "Climb", foreground='grey')
            burspd = ttk.Entry(content, width = 4)
            brslbl = ttk.Label(content, text = "Burw", foreground='grey')
            tmdlbl = ttk.Label(content, text = "Temp Mod", foreground='grey')
            tmpmod1 = ttk.Entry(content, width = 9)
            tmpmod2 = ttk.Entry(content, width = 9)
            tmpmod3 = ttk.Entry(content, width = 9)
            wcrlbl = ttk.Label(content, text = "Wounds / HP", background='black', foreground='white')
            wcr1 = ttk.Entry(content, width = 31)
            wcr2 = ttk.Entry(content, width = 31)
            nldlbl = ttk.Label(content, text = "Non-Lethal Damage", background='black', foreground='white')
            nld = ttk.Entry(content, width = 31)
            inilbl = ttk.Label(content, text = "  Initiative  ", background='black', foreground='white')
            initot = ttk.Entry(content, width = 5)
            inidex = ttk.Entry(content, width = 4)
            inimsc = ttk.Entry(content, width = 4)
            inip = ttk.Label(content, text = "+")
            inie = ttk.Label(content, text = "=")
            inidexlbl = ttk.Label(content, text = "Dex", foreground='grey')
            inimsclbl = ttk.Label(content, text = "Misc", foreground='grey')
            initotlbl = ttk.Label(content, text = "Total", foreground='grey')
            inimodlbl = ttk.Label(content, text = "  Modifier  ", foreground='grey')

            """ Basic attribute placement"""
            hplbl.grid(      column=4, row=9, sticky = (E))
            hp.grid(         column=5, row=9, sticky = (W))
            drlbl.grid(      column=6, row=9, sticky = (W))
            dmgres.grid(     column=6, row=9, sticky = (E))
            speedlbl.grid(   column=7, row=9, sticky = (E), padx = 5)
            bspeed.grid(     column=8, row=9, sticky = (W))
            bpdlbl.grid(     column=8, row=10, sticky = (W))
            aspeed.grid(     column=9, row=9, sticky = (W))
            asplbl.grid(     column=9, row=10, sticky = (W))
            sspeed.grid(     column=7, row=11, sticky = (W))
            ssplbl.grid(     column=7, row=12, sticky = (W))
            fspeed.grid(     column=7, row=11, sticky = (E))
            fsplbl.grid(     column=7, row=12, sticky = (E))
            maneuv.grid(     column=8, row=11, sticky = (W))
            mnvlbl.grid(     column=8, row=12, sticky = (W))
            cspeed.grid(     column=9, row=11, sticky = (W))
            csplbl.grid(     column=9, row=12, sticky = (W))
            burspd.grid(     column=9, row=11, sticky = (E))
            brslbl.grid(     column=9, row=12, sticky = (E))
            tmdlbl.grid(     column=10, row=9, sticky = (E))
            tmpmod1.grid(    column=10, row=10, sticky = (W), padx = 3)
            tmpmod2.grid(    column=10, row=11, sticky = (W), padx = 3)
            tmpmod3.grid(    column=10, row=12, sticky = (W), padx = 3)
            wcrlbl.grid(     column=4, row=10, columnspan = 2, sticky = (W))
            wcr1.grid(       column=4, row=11, columnspan = 3, sticky = (NE))
            wcr2.grid(       column=4, row=12, columnspan = 3, sticky = (NE))
            nldlbl.grid(     column=4, row=13, columnspan = 2, sticky = (W))
            nld.grid(        column=4, row=14, columnspan = 3, sticky = (NE))
            inilbl.grid(     column=4, row=16, columnspan = 2, sticky = (W))
            initot.grid(     column=5, row=16, sticky = (E), padx = 12)
            inie.grid(       column=5, row=16, sticky = (E))
            inidex.grid(     column=6, row=16, sticky = (E))
            inip.grid(       column=6, row=16)
            inimsc.grid(     column=6, row=16, sticky = (W))
            inidexlbl.grid(  column=6, row=15, sticky = (E))
            inimsclbl.grid(  column=6, row=15, sticky = (W))
            initotlbl.grid(  column=5, row=15, sticky = (E), padx = 12)
            inimodlbl.grid(  column=4, row=15, sticky = (W))

            """ Fortitude, Reflex, Will Declaration """
            frwtotlbl = ttk.Label(content, text = "Total", foreground='grey')
            frwbaslbl = ttk.Label(content, text = "Base", foreground='grey')
            frwabllbl = ttk.Label(content, text = "Abil.", foreground='grey')
            frwmaglbl = ttk.Label(content, text = "Magic", foreground='grey')
            frwmsclbl = ttk.Label(content, text = "Misc", foreground='grey')
            frwtmplbl = ttk.Label(content, text = "Temp", foreground='grey')
            forlbl = ttk.Label(content, text = "Fortitude ", background='black', foreground='white')
            reflbl = ttk.Label(content, text = "  Reflex    ", background='black', foreground='white')
            willbl = ttk.Label(content, text = "     Will     ", background='black', foreground='white')
            fortot = ttk.Entry(content, width = 3)
            reftot = ttk.Entry(content, width = 3)
            wiltot = ttk.Entry(content, width = 3)
            forbas = ttk.Entry(content, width = 3)
            refbas = ttk.Entry(content, width = 3)
            wilbas = ttk.Entry(content, width = 3)
            forabl = ttk.Entry(content, width = 3)
            refabl = ttk.Entry(content, width = 3)
            wilabl = ttk.Entry(content, width = 3)
            formag = ttk.Entry(content, width = 3)
            refmag = ttk.Entry(content, width = 3)
            wilmag = ttk.Entry(content, width = 3)
            formsc = ttk.Entry(content, width = 3)
            refmsc = ttk.Entry(content, width = 3)
            wilmsc = ttk.Entry(content, width = 3)
            fortmp = ttk.Entry(content, width = 3)
            reftmp = ttk.Entry(content, width = 3)
            wiltmp = ttk.Entry(content, width = 3)
            frwe1 = ttk.Label(content, text = "=")
            frwe2 = ttk.Label(content, text = "=")
            frwe3 = ttk.Label(content, text = "=")
            frwp1 = ttk.Label(content, text = "+")
            frwp2 = ttk.Label(content, text = "+")
            frwp3 = ttk.Label(content, text = "+")
            frwp4 = ttk.Label(content, text = "+")
            frwp5 = ttk.Label(content, text = "+")
            frwp6 = ttk.Label(content, text = "+")
            frwp7 = ttk.Label(content, text = "+")
            frwp8 = ttk.Label(content, text = "+")
            frwp9 = ttk.Label(content, text = "+")
            frwp10 = ttk.Label(content, text = "+")
            frwp11 = ttk.Label(content, text = "+")
            frwp12 = ttk.Label(content, text = "+")
            frwp13 = ttk.Label(content, text = "+")
            frwp14 = ttk.Label(content, text = "+")
            frwp15 = ttk.Label(content, text = "+")
            frwp16 = ttk.Label(content, text = "+")

            """ Fortitude, Reflex, Will Placement """
            frwtotlbl.grid( column=8, row = 13, sticky = (W) )
            frwbaslbl.grid( column=8, row = 13, sticky = (E), padx = 5 )
            frwabllbl.grid( column=9, row = 13, sticky = (W) )
            frwmaglbl.grid( column=9, row = 13, sticky = (E) )
            frwmsclbl.grid( column=10, row = 13, sticky = (W) )
            frwtmplbl.grid( column=10, row = 13, sticky = (E) )
            forlbl.grid(    column=7, row = 14, sticky = (E) )
            reflbl.grid(    column=7, row = 15, sticky = (E) )
            willbl.grid(    column=7, row = 16, sticky = (E) )
            fortot.grid(    column=8, row = 14, sticky = (W) )
            reftot.grid(    column=8, row = 15, sticky = (W) )
            wiltot.grid(    column=8, row = 16, sticky = (W) )
            forbas.grid(    column=8, row = 14, sticky = (E), padx = 9 )
            refbas.grid(    column=8, row = 15, sticky = (E), padx = 9 )
            wilbas.grid(    column=8, row = 16, sticky = (E), padx = 9 )
            forabl.grid(    column=9, row = 14, sticky = (W) )
            refabl.grid(    column=9, row = 15, sticky = (W) )
            wilabl.grid(    column=9, row = 16, sticky = (W) )
            formag.grid(    column=9, row = 14, sticky = (E), padx = 9 )
            refmag.grid(    column=9, row = 15, sticky = (E), padx = 9 )
            wilmag.grid(    column=9, row = 16, sticky = (E), padx = 9 )
            formsc.grid(    column=10, row = 14, sticky = (W) )
            refmsc.grid(    column=10, row = 15, sticky = (W) )
            wilmsc.grid(    column=10, row = 16, sticky = (W) )
            fortmp.grid(    column=10, row = 14, sticky = (E), padx = 9 )
            reftmp.grid(    column=10, row = 15, sticky = (E), padx = 9 )
            wiltmp.grid(    column=10, row = 16, sticky = (E), padx = 9 )
            frwe1.grid(     column=8, row = 14, sticky = (W), padx = 22)
            frwe2.grid(     column=8, row = 15, sticky = (W), padx = 22)
            frwe3.grid(     column=8, row = 16, sticky = (W), padx = 22)
            frwp1.grid(     column=8, row = 14, sticky = (E) )
            frwp2.grid(     column=8, row = 15, sticky = (E) )
            frwp3.grid(     column=8, row = 16, sticky = (E) )
            frwp4.grid(     column=9, row = 14, sticky = (W), padx = 22 )
            frwp5.grid(     column=9, row = 15, sticky = (W), padx = 22 )
            frwp6.grid(     column=9, row = 16, sticky = (W), padx = 22 )
            frwp7.grid(     column=9, row = 14, sticky = (E) )
            frwp8.grid(     column=9, row = 15, sticky = (E) )
            frwp9.grid(     column=9, row = 16, sticky = (E) )
            frwp10.grid(    column=10, row = 14, sticky = (W), padx = 22 )
            frwp11.grid(    column=10, row = 15, sticky = (W), padx = 22 )
            frwp12.grid(    column=10, row = 16, sticky = (W), padx = 22 )

            """ armor class declarations """
            armclslbl= ttk.Label(content, text = "     AC    ", background='black', foreground='white')
            touchalbl= ttk.Label(content, text = " Touch  ", background='black', foreground='white')
            flatftlbl= ttk.Label(content, text = "Flat foot", background='black', foreground='white')
            atftotlbl= ttk.Label(content, text = "Total", foreground='grey')
            atfarmlbl= ttk.Label(content, text = "Armor", foreground='grey')
            arfshdlbl= ttk.Label(content, text = "Shield", foreground='grey')
            arfdexlbl= ttk.Label(content, text = "Dex Mod", foreground='grey')
            arfsizlbl= ttk.Label(content, text = "Size Mod", foreground='grey')
            arfnatlbl= ttk.Label(content, text = "Natural", foreground='grey')
            arfdfllbl= ttk.Label(content, text = "Deflect", foreground='grey')
            arfmsclbl= ttk.Label(content, text = "Misc Mod", foreground='grey')

            armortot= ttk.Entry(content, width = 8)
            touchtot= ttk.Entry(content, width = 8)
            fltfttot= ttk.Entry(content, width = 8)
            armarbon= ttk.Entry(content, width = 6)
            fltarbon= ttk.Entry(content, width = 6)
            armshbon= ttk.Entry(content, width = 6)
            fltshbon= ttk.Entry(content, width = 6)
            armordex= ttk.Entry(content, width = 6)
            touchdex= ttk.Entry(content, width = 6)
            armorsiz= ttk.Entry(content, width = 6)
            touchsiz= ttk.Entry(content, width = 6)
            fltftsiz= ttk.Entry(content, width = 6)
            armornat= ttk.Entry(content, width = 6)
            fltftnat= ttk.Entry(content, width = 6)
            armordfl= ttk.Entry(content, width = 6)
            touchdfl= ttk.Entry(content, width = 6)
            fltftdfl= ttk.Entry(content, width = 6)
            armormsc= ttk.Entry(content, width = 6)
            touchmsc= ttk.Entry(content, width = 6)
            fltftmsc= ttk.Entry(content, width = 6)

            atfep01= ttk.Label(content, text = "=  10 +")
            atfep02= ttk.Label(content, text = "=  10 +")
            atfep03= ttk.Label(content, text = "=  10 +")
            atfp01= ttk.Label(content, text = "+")
            atfp02= ttk.Label(content, text = "+")
            atfp03= ttk.Label(content, text = "+")
            atfp04= ttk.Label(content, text = "+")
            atfp05= ttk.Label(content, text = "+")
            atfp06= ttk.Label(content, text = "+")
            atfp07= ttk.Label(content, text = "+")
            atfp08= ttk.Label(content, text = "+")
            atfp09= ttk.Label(content, text = "+")
            atfp10= ttk.Label(content, text = "+")
            atfp11= ttk.Label(content, text = "+")
            atfp12= ttk.Label(content, text = "+")
            atfp13= ttk.Label(content, text = "+")
            atfp14= ttk.Label(content, text = "+")
            atfp15= ttk.Label(content, text = "+")
            atfp16= ttk.Label(content, text = "+")
            atfp17= ttk.Label(content, text = "+")

            """ armor class placement """
            armclslbl.grid( column = 2, row = 17, sticky = (E), padx=5)
            touchalbl.grid( column = 2, row = 18, sticky = (E), padx=5)
            flatftlbl.grid( column = 2, row = 19, sticky = (E), padx=5)
            atftotlbl.grid( column = 3, row = 20, sticky = (W), padx=5)
            atfarmlbl.grid( column = 4, row = 20)
            arfshdlbl.grid( column = 5, row = 20)
            arfdexlbl.grid( column = 6, row = 20)
            arfsizlbl.grid( column = 7, row = 20)
            arfnatlbl.grid( column = 8, row = 20)
            arfdfllbl.grid( column = 9, row = 20)
            arfmsclbl.grid( column = 10, row = 20)
            armortot.grid(  column = 3, row = 17, sticky = (W))
            touchtot.grid(  column = 3, row = 18, sticky = (W))
            fltfttot.grid(  column = 3, row = 19, sticky = (W))
            armarbon.grid(  column = 4, row = 17)
            fltarbon.grid(  column = 4, row = 19)
            armshbon.grid(  column = 5, row = 17)
            fltshbon.grid(  column = 5, row = 19)
            armordex.grid(  column = 6, row = 17)
            touchdex.grid(  column = 6, row = 18)
            armorsiz.grid(  column = 7, row = 17)
            touchsiz.grid(  column = 7, row = 18)
            fltftsiz.grid(  column = 7, row = 19)
            armornat.grid(  column = 8, row = 17)
            fltftnat.grid(  column = 8, row = 19)
            armordfl.grid(  column = 9, row = 17)
            touchdfl.grid(  column = 9, row = 18)
            fltftdfl.grid(  column = 9, row = 19)
            armormsc.grid(  column = 10, row = 17)
            touchmsc.grid(  column = 10, row = 18)
            fltftmsc.grid(  column = 10, row = 19)
            atfep01.grid(   column = 3, row = 17, sticky=(E))
            atfep02.grid(   column = 3, row = 18, sticky=(E))
            atfep03.grid(   column = 3, row = 19, sticky=(E))
            atfp01.grid(    column = 4, row = 17, sticky=(E))
            atfp02.grid(    column = 5, row = 17, sticky=(E))
            atfp03.grid(    column = 6, row = 17, sticky=(E))
            atfp04.grid(    column = 7, row = 17, sticky=(E))
            atfp05.grid(    column = 8, row = 17, sticky=(E))
            atfp06.grid(    column = 9, row = 17, sticky=(E))
            atfp07.grid(    column = 5, row = 18, sticky=(E))
            atfp08.grid(    column = 6, row = 18, sticky=(E))
            atfp09.grid(    column = 7, row = 18, sticky=(E))
            atfp10.grid(    column = 8, row = 18, sticky=(E))
            atfp11.grid(    column = 9, row = 18, sticky=(E))
            atfp12.grid(    column = 4, row = 19, sticky=(E))
            atfp13.grid(    column = 5, row = 19, sticky=(E))
            atfp14.grid(    column = 6, row = 19, sticky=(E))
            atfp15.grid(    column = 7, row = 19, sticky=(E))
            atfp16.grid(    column = 8, row = 19, sticky=(E))
            atfp17.grid(    column = 9, row = 19, sticky=(E))

            character.add(content, text='Abilities')

    def _create_inventory_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            """ Gear Declaration """
            gearlbl = ttk.Label(content, text = "                                       Gear                                      ", background = 'black', foreground = 'white')
            itemlbl = ttk.Label(content, text = "Item", foreground = 'grey')
            wghtlbl = ttk.Label(content, text = "WT.", foreground = 'grey')

            item1nm = ttk.Entry(content, width=30)
            item1wt = ttk.Entry(content, width=10)
            item2nm = ttk.Entry(content, width=30)
            item2wt = ttk.Entry(content, width=10)
            item3nm = ttk.Entry(content, width=30)
            item3wt = ttk.Entry(content, width=10)
            item4nm = ttk.Entry(content, width=30)
            item4wt = ttk.Entry(content, width=10)
            item5nm = ttk.Entry(content, width=30)
            item5wt = ttk.Entry(content, width=10)
            item6nm = ttk.Entry(content, width=30)
            item6wt = ttk.Entry(content, width=10)
            item7nm = ttk.Entry(content, width=30)
            item7wt = ttk.Entry(content, width=10)
            item8nm = ttk.Entry(content, width=30)
            item8wt = ttk.Entry(content, width=10)
            item9nm = ttk.Entry(content, width=30)
            item9wt = ttk.Entry(content, width=10)
            item10nm = ttk.Entry(content, width=30)
            item10wt = ttk.Entry(content, width=10)
            item11nm = ttk.Entry(content, width=30)
            item11wt = ttk.Entry(content, width=10)
            item12nm = ttk.Entry(content, width=30)
            item12wt = ttk.Entry(content, width=10)
            item13nm = ttk.Entry(content, width=30)
            item13wt = ttk.Entry(content, width=10)
            item14nm = ttk.Entry(content, width=30)
            item14wt = ttk.Entry(content, width=10)
            item15nm = ttk.Entry(content, width=30)
            item15wt = ttk.Entry(content, width=10)
            item16nm = ttk.Entry(content, width=30)
            item16wt = ttk.Entry(content, width=10)
            item17nm = ttk.Entry(content, width=30)
            item17wt = ttk.Entry(content, width=10)
            item18nm = ttk.Entry(content, width=30)
            item18wt = ttk.Entry(content, width=10)
            item19nm = ttk.Entry(content, width=30)
            item19wt = ttk.Entry(content, width=10)
            item20nm = ttk.Entry(content, width=30)
            item20wt = ttk.Entry(content, width=10)

            wtotlbl = ttk.Label(content, text = "                                   Total Weight   ", background = 'black', foreground = 'white')
            wtotbox = ttk.Entry(content, width=10)

            """ Gear Placement """
            gearlbl.grid( column = 1, row = 2, columnspan = 4)
            itemlbl.grid( column = 1, row = 3, columnspan = 3)
            wghtlbl.grid( column = 4, row = 3, columnspan = 1)

            item1nm.grid( column = 1, row = 4, columnspan = 3)
            item1wt.grid( column = 4, row = 4, columnspan = 1)
            item2nm.grid( column = 1, row = 5, columnspan = 3)
            item2wt.grid( column = 4, row = 5, columnspan = 1)
            item3nm.grid( column = 1, row = 6, columnspan = 3)
            item3wt.grid( column = 4, row = 6, columnspan = 1)
            item4nm.grid( column = 1, row = 7, columnspan = 3)
            item4wt.grid( column = 4, row = 7, columnspan = 1)
            item5nm.grid( column = 1, row = 8, columnspan = 3)
            item5wt.grid( column = 4, row = 8, columnspan = 1)
            item6nm.grid( column = 1, row = 9, columnspan = 3)
            item6wt.grid( column = 4, row = 9, columnspan = 1)
            item7nm.grid( column = 1, row = 10, columnspan = 3)
            item7wt.grid( column = 4, row = 10, columnspan = 1)
            item8nm.grid( column = 1, row = 11, columnspan = 3)
            item8wt.grid( column = 4, row = 11, columnspan = 1)
            item9nm.grid( column = 1, row = 12, columnspan = 3)
            item9wt.grid( column = 4, row = 12, columnspan = 1)
            item10nm.grid( column = 1, row = 13, columnspan = 3)
            item10wt.grid( column = 4, row = 13, columnspan = 1)
            item11nm.grid( column = 1, row = 14, columnspan = 3)
            item11wt.grid( column = 4, row = 14, columnspan = 1)
            item12nm.grid( column = 1, row = 15, columnspan = 3)
            item12wt.grid( column = 4, row = 15, columnspan = 1)
            item13nm.grid( column = 1, row = 16, columnspan = 3)
            item13wt.grid( column = 4, row = 16, columnspan = 1)
            item14nm.grid( column = 1, row = 17, columnspan = 3)
            item14wt.grid( column = 4, row = 17, columnspan = 1)
            item15nm.grid( column = 1, row = 18, columnspan = 3)
            item15wt.grid( column = 4, row = 18, columnspan = 1)
            item16nm.grid( column = 1, row = 19, columnspan = 3)
            item16wt.grid( column = 4, row = 19, columnspan = 1)
            item17nm.grid( column = 1, row = 20, columnspan = 3)
            item17wt.grid( column = 4, row = 20, columnspan = 1)
            item18nm.grid( column = 1, row = 21, columnspan = 3)
            item18wt.grid( column = 4, row = 21, columnspan = 1)
            item19nm.grid( column = 1, row = 22, columnspan = 3)
            item19wt.grid( column = 4, row = 22, columnspan = 1)
            item20nm.grid( column = 1, row = 23, columnspan = 3)
            item20wt.grid( column = 4, row = 23, columnspan = 1)

            wtotlbl.grid(  column = 1, row = 24, columnspan = 3)
            wtotbox.grid(  column = 4, row = 24, columnspan = 1)

            """ Carry Declarations """
            hdlbl = ttk.Label(content, text = "                              Load Limits                               ", background = 'black', foreground = 'white')
            ltlbl = ttk.Label(content, text = "Light Load")
            mdlbl = ttk.Label(content, text = "Medium Load")
            hvlbl = ttk.Label(content, text = "Heavy Load")
            ohlbl = ttk.Label(content, text = "Over Head")
            oglbl = ttk.Label(content, text = "Off Ground")
            dplbl = ttk.Label(content, text = "Drag/Push")
            ltbox = ttk.Entry(content, width = 5)
            mdbox = ttk.Entry(content, width = 5)
            hvbox = ttk.Entry(content, width = 5)
            ohbox = ttk.Entry(content, width = 5)
            ogbox = ttk.Entry(content, width = 5)
            dpbox = ttk.Entry(content, width = 5)
            
            """ Carry Placement """
            hdlbl.grid( column = 5, row = 2, columnspan = 6)   
            ltlbl.grid( column = 5, row = 3, columnspan = 3, sticky = (W) )
            mdlbl.grid( column = 5, row = 4, columnspan = 3, sticky = (W) )
            hvlbl.grid( column = 5, row = 5, columnspan = 3, sticky = (W) )
            ohlbl.grid( column = 8, row = 3, columnspan = 3, sticky = (W) )
            oglbl.grid( column = 8, row = 4, columnspan = 3, sticky = (W) )
            dplbl.grid( column = 8, row = 5, columnspan = 3, sticky = (W) )
            ltbox.grid( column = 7, row = 3, sticky = (E))
            mdbox.grid( column = 7, row = 4, sticky = (E))
            hvbox.grid( column = 7, row = 5, sticky = (E))
            ohbox.grid( column = 10, row = 3, sticky = (E))
            ogbox.grid( column = 10, row = 4, sticky = (E))
            dpbox.grid( column = 10, row = 5, sticky = (E))
            
            """ Money Declarations """
            mnlbl = ttk.Label(content, text = "                                 Money                                    ", background='black', foreground='white')
            cplbl = ttk.Label(content, text = "Copper")
            splbl = ttk.Label(content, text = "Silver")
            gplbl = ttk.Label(content, text = "Gold")
            pplbl = ttk.Label(content, text = "Platinum")
            cpbox = ttk.Entry(content, width = 5)
            spbox = ttk.Entry(content, width = 5)
            gpbox = ttk.Entry(content, width = 5)
            ppbox = ttk.Entry(content, width = 5)
            
            """ Money Placement """
            mnlbl.grid(column = 5, row = 6, columnspan=6)
            cplbl.grid(column = 5, row = 7, columnspan=2, sticky = (W))
            splbl.grid(column = 8, row = 7, columnspan=2, sticky = (W))
            gplbl.grid(column = 5, row = 8, columnspan=2, sticky = (W))
            pplbl.grid(column = 8, row = 8, columnspan=2, sticky = (W))
            
            cpbox.grid(column = 7, row = 7, sticky = (E))
            spbox.grid(column = 10, row = 7, sticky = (E))
            gpbox.grid(column = 7, row = 8, sticky = (E))
            ppbox.grid(column = 10, row = 8, sticky = (E))
            
            """ Experience Declaration """
            explbl = ttk.Label(content, text = "              Experience Points                ", background='black', foreground='white')
            expbox = ttk.Entry(content, width = 30)
            nxtlbl = ttk.Label(content, text = " Next Level ", background='black', foreground='white')
            nxtbox = ttk.Entry(content, width = 10)
            
            """ Experience Placement """
            explbl.grid(column = 5, row = 9, columnspan = 4) 
            expbox.grid(column = 5, row = 10, columnspan = 4)
            nxtlbl.grid(column = 9, row = 9, columnspan = 2)
            nxtbox.grid(column = 9, row = 10, columnspan = 2)
            
            character.add(content, text='Inventory')
            
    def _create_weapons_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            """ attack stats declaration """
            bablbl = ttk.Label(content, text = "      Base Attack Bonus     ", background = 'black', foreground = 'white')
            reslbl = ttk.Label(content, text = "        Spell Resistance       ", background = 'black', foreground = 'white')
            cmblbl = ttk.Label(content, text = "    CMB    ", background = 'black', foreground = 'white')
            cmdlbl = ttk.Label(content, text = "    CMD    ", background = 'black', foreground = 'white')
            atkbon = ttk.Entry(content, width = 8)
            splres = ttk.Entry(content, width = 8)
            cmbtot = ttk.Entry(content, width = 4)
            cmbbab = ttk.Entry(content, width = 4)
            cmbstr = ttk.Entry(content, width = 4)
            cmbsiz = ttk.Entry(content, width = 4)
            cmdtot = ttk.Entry(content, width = 4)
            cmdcmb = ttk.Entry(content, width = 4)
            cmddex = ttk.Entry(content, width = 4)
            cmdl10 = ttk.Label(content, text = "10")
            cmdp01 = ttk.Label(content, text = "+")
            cmdp02 = ttk.Label(content, text = "+")
            cmde01 = ttk.Label(content, text = "=")
            cmbp01 = ttk.Label(content, text = "+")
            cmbp02 = ttk.Label(content, text = "+")
            cmbe01 = ttk.Label(content, text = "=")
            cmbtotlbl = ttk.Label(content, text = "Total", foreground = 'grey')
            cmbbablbl = ttk.Label(content, text = "B.A.B.", foreground = 'grey')
            cmbstrlbl = ttk.Label(content, text = "Str Mod", foreground = 'grey')
            cmbsizlbl = ttk.Label(content, text = "Size Mod", foreground = 'grey')
            cmdtotlbl = ttk.Label(content, text = "Total", foreground = 'grey')
            cmdcmblbl = ttk.Label(content, text = "CMB", foreground = 'grey')
            cmddexlbl = ttk.Label(content, text = "Dex Mod", foreground = 'grey')

            """ attack stats placement """
            bablbl.grid(column=1, row=2, columnspan=2, sticky=(W))
            reslbl.grid(column=4, row=2, columnspan=2, sticky=(W))
            cmblbl.grid(column=1, row=4)
            cmdlbl.grid(column=1, row=5)
            atkbon.grid(column=3, row=2, sticky=(W))
            splres.grid(column=6, row=2, sticky=(W))
            cmbtot.grid(column=3, row=4, sticky=(W))
            cmbbab.grid(column=4, row=4, sticky=(W))
            cmbstr.grid(column=5, row=4)
            cmbsiz.grid(column=6, row=4, sticky=(W))
            cmdtot.grid(column=3, row=5, sticky=(W))
            cmdcmb.grid(column=4, row=5, sticky=(W))
            cmddex.grid(column=5, row=5)
            cmdl10.grid(column=6, row=5, sticky=(W))
            cmdp01.grid(column=5, row=4, sticky=(W))
            cmdp02.grid(column=5, row=4, sticky=(E))
            cmde01.grid(column=3, row=4, sticky=(E))
            cmbp01.grid(column=5, row=5, sticky=(W))
            cmbp02.grid(column=5, row=5, sticky=(E))
            cmbe01.grid(column=3, row=5, sticky=(E))
            cmbtotlbl.grid(column=3, row=3, sticky=(W))
            cmbbablbl.grid(column=4, row=3, sticky=(W))
            cmbstrlbl.grid(column=5, row=3, sticky=(W))
            cmbsizlbl.grid(column=6, row=3, sticky=(W))
            cmdcmblbl.grid(column=4, row=6, sticky=(W))
            cmdtotlbl.grid(column=3, row=6, sticky=(W))
            cmddexlbl.grid(column=5, row=6, sticky=(W))

            """ weapons declaration """
            weapon1lbllbl = ttk.Label(content, text = "Weapon 1", background = 'black', foreground = 'white')
            weapon1atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon1crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon1typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon1rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon1ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon1damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon1lblbox = ttk.Entry(content, width=42)
            weapon1atkbox = ttk.Entry(content, width=12)
            weapon1crtbox = ttk.Entry(content, width=10)
            weapon1typbox = ttk.Entry(content, width=10)
            weapon1rngbox = ttk.Entry(content, width=10)
            weapon1ammbox = ttk.Entry(content, width=20)
            weapon1dambox = ttk.Entry(content, width=23)

            weapon2lbllbl = ttk.Label(content, text = "Weapon 2", background = 'black', foreground = 'white')
            weapon2atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon2crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon2typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon2rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon2ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon2damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon2lblbox = ttk.Entry(content, width=42)
            weapon2atkbox = ttk.Entry(content, width=12)
            weapon2crtbox = ttk.Entry(content, width=10)
            weapon2typbox = ttk.Entry(content, width=10)
            weapon2rngbox = ttk.Entry(content, width=10)
            weapon2ammbox = ttk.Entry(content, width=20)
            weapon2dambox = ttk.Entry(content, width=23)

            weapon3lbllbl = ttk.Label(content, text = "Weapon 3", background = 'black', foreground = 'white')
            weapon3atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon3crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon3typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon3rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon3ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon3damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon3lblbox = ttk.Entry(content, width=42)
            weapon3atkbox = ttk.Entry(content, width=12)
            weapon3crtbox = ttk.Entry(content, width=10)
            weapon3typbox = ttk.Entry(content, width=10)
            weapon3rngbox = ttk.Entry(content, width=10)
            weapon3ammbox = ttk.Entry(content, width=20)
            weapon3dambox = ttk.Entry(content, width=23)

            weapon4lbllbl = ttk.Label(content, text = "Weapon 4" , background = 'black', foreground = 'white')
            weapon4atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon4crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon4typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon4rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon4ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon4damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon4lblbox = ttk.Entry(content, width=42)
            weapon4atkbox = ttk.Entry(content, width=12)
            weapon4crtbox = ttk.Entry(content, width=10)
            weapon4typbox = ttk.Entry(content, width=10)
            weapon4rngbox = ttk.Entry(content, width=10)
            weapon4ammbox = ttk.Entry(content, width=20)
            weapon4dambox = ttk.Entry(content, width=23)

            weapon5lbllbl = ttk.Label(content, text = "Weapon 5", background = 'black', foreground = 'white')
            weapon5atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon5crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon5typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon5rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon5ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon5damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon5lblbox = ttk.Entry(content, width=42)
            weapon5atkbox = ttk.Entry(content, width=12)
            weapon5crtbox = ttk.Entry(content, width=10)
            weapon5typbox = ttk.Entry(content, width=10)
            weapon5rngbox = ttk.Entry(content, width=10)
            weapon5ammbox = ttk.Entry(content, width=20)
            weapon5dambox = ttk.Entry(content, width=23)

            """ weapons placement """

            weapon1lbllbl.grid(column = 1, row = 7, columnspan = 4, sticky = (W))
            weapon1atklbl.grid(column = 5, row = 7, columnspan = 1, sticky = (W))
            weapon1crtlbl.grid(column = 6, row = 7, columnspan = 1, sticky = (W))
            weapon1typlbl.grid(column = 1, row = 9, columnspan = 1, sticky = (W))
            weapon1rnglbl.grid(column = 2, row = 9, columnspan = 1, sticky = (W))
            weapon1ammlbl.grid(column = 3, row = 9, columnspan = 2, sticky = (W))
            weapon1damlbl.grid(column = 5, row = 9, columnspan = 2, sticky = (W))
            weapon1lblbox.grid(column = 1, row = 8, columnspan = 4, sticky = (W))
            weapon1atkbox.grid(column = 5, row = 8, columnspan = 1, sticky = (W))
            weapon1crtbox.grid(column = 6, row = 8, columnspan = 1, sticky = (W))
            weapon1typbox.grid(column = 1, row = 10, columnspan = 1, sticky = (W))
            weapon1rngbox.grid(column = 2, row = 10, columnspan = 1, sticky = (W))
            weapon1ammbox.grid(column = 3, row = 10, columnspan = 2, sticky = (W))
            weapon1dambox.grid(column = 5, row = 10, columnspan = 2, sticky = (W))

            weapon2lbllbl.grid(column = 1, row = 11, columnspan = 4, sticky = (W))
            weapon2atklbl.grid(column = 5, row = 11, columnspan = 1, sticky = (W))
            weapon2crtlbl.grid(column = 6, row = 11, columnspan = 1, sticky = (W))
            weapon2typlbl.grid(column = 1, row = 13, columnspan = 1, sticky = (W))
            weapon2rnglbl.grid(column = 2, row = 13, columnspan = 1, sticky = (W))
            weapon2ammlbl.grid(column = 3, row = 13, columnspan = 2, sticky = (W))
            weapon2damlbl.grid(column = 5, row = 13, columnspan = 2, sticky = (W))
            weapon2lblbox.grid(column = 1, row = 12, columnspan = 4, sticky = (W))
            weapon2atkbox.grid(column = 5, row = 12, columnspan = 1, sticky = (W))
            weapon2crtbox.grid(column = 6, row = 12, columnspan = 1, sticky = (W))
            weapon2typbox.grid(column = 1, row = 14, columnspan = 1, sticky = (W))
            weapon2rngbox.grid(column = 2, row = 14, columnspan = 1, sticky = (W))
            weapon2ammbox.grid(column = 3, row = 14, columnspan = 2, sticky = (W))
            weapon2dambox.grid(column = 5, row = 14, columnspan = 2, sticky = (W))

            weapon3lbllbl.grid(column = 1, row = 15, columnspan = 4, sticky = (W))
            weapon3atklbl.grid(column = 5, row = 15, columnspan = 1, sticky = (W))
            weapon3crtlbl.grid(column = 6, row = 15, columnspan = 1, sticky = (W))
            weapon3typlbl.grid(column = 1, row = 17, columnspan = 1, sticky = (W))
            weapon3rnglbl.grid(column = 2, row = 17, columnspan = 1, sticky = (W))
            weapon3ammlbl.grid(column = 3, row = 17, columnspan = 2, sticky = (W))
            weapon3damlbl.grid(column = 5, row = 17, columnspan = 2, sticky = (W))
            weapon3lblbox.grid(column = 1, row = 16, columnspan = 4, sticky = (W))
            weapon3atkbox.grid(column = 5, row = 16, columnspan = 1, sticky = (W))
            weapon3crtbox.grid(column = 6, row = 16, columnspan = 1, sticky = (W))
            weapon3typbox.grid(column = 1, row = 18, columnspan = 1, sticky = (W))
            weapon3rngbox.grid(column = 2, row = 18, columnspan = 1, sticky = (W))
            weapon3ammbox.grid(column = 3, row = 18, columnspan = 2, sticky = (W))
            weapon3dambox.grid(column = 5, row = 18, columnspan = 2, sticky = (W))

            weapon4lbllbl.grid(column = 1, row = 19, columnspan = 4, sticky = (W))
            weapon4atklbl.grid(column = 5, row = 19, columnspan = 1, sticky = (W))
            weapon4crtlbl.grid(column = 6, row = 19, columnspan = 1, sticky = (W))
            weapon4typlbl.grid(column = 1, row = 21, columnspan = 1, sticky = (W))
            weapon4rnglbl.grid(column = 2, row = 21, columnspan = 1, sticky = (W))
            weapon4ammlbl.grid(column = 3, row = 21, columnspan = 2, sticky = (W))
            weapon4damlbl.grid(column = 5, row = 21, columnspan = 2, sticky = (W))
            weapon4lblbox.grid(column = 1, row = 20, columnspan = 4, sticky = (W))
            weapon4atkbox.grid(column = 5, row = 20, columnspan = 1, sticky = (W))
            weapon4crtbox.grid(column = 6, row = 20, columnspan = 1, sticky = (W))
            weapon4typbox.grid(column = 1, row = 22, columnspan = 1, sticky = (W))
            weapon4rngbox.grid(column = 2, row = 22, columnspan = 1, sticky = (W))
            weapon4ammbox.grid(column = 3, row = 22, columnspan = 2, sticky = (W))
            weapon4dambox.grid(column = 5, row = 22, columnspan = 2, sticky = (W))

            weapon5lbllbl.grid(column = 1, row = 23, columnspan = 4, sticky = (W))
            weapon5atklbl.grid(column = 5, row = 23, columnspan = 1, sticky = (W))
            weapon5crtlbl.grid(column = 6, row = 23, columnspan = 1, sticky = (W))
            weapon5typlbl.grid(column = 1, row = 25, columnspan = 1, sticky = (W))
            weapon5rnglbl.grid(column = 2, row = 25, columnspan = 1, sticky = (W))
            weapon5ammlbl.grid(column = 3, row = 25, columnspan = 2, sticky = (W))
            weapon5damlbl.grid(column = 5, row = 25, columnspan = 2, sticky = (W))
            weapon5lblbox.grid(column = 1, row = 24, columnspan = 4, sticky = (W))
            weapon5atkbox.grid(column = 5, row = 24, columnspan = 1, sticky = (W))
            weapon5crtbox.grid(column = 6, row = 24, columnspan = 1, sticky = (W))
            weapon5typbox.grid(column = 1, row = 26, columnspan = 1, sticky = (W))
            weapon5rngbox.grid(column = 2, row = 26, columnspan = 1, sticky = (W))
            weapon5ammbox.grid(column = 3, row = 26, columnspan = 2, sticky = (W))
            weapon5dambox.grid(column = 5, row = 26, columnspan = 2, sticky = (W))

            character.add(content, text='Weapons')

    def _create_armor_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            """ Armor Declarations """
            acglbllbl = ttk.Label(content, text="Armor Class Gear           ", background='black', foreground='white')
            acgbonlbl = ttk.Label(content, text="Bonus          ", background='black', foreground='white')
            acgtyplbl = ttk.Label(content, text="Type            ", background='black', foreground='white')
            acgchklbl = ttk.Label(content, text="Check Penalty", background='black', foreground='white')
            acgspflbl = ttk.Label(content, text="Spell Failure", background='black', foreground='white')
            acgwgtlbl = ttk.Label(content, text="Weight        ", background='black', foreground='white')
            acgprplbl = ttk.Label(content, text="Properties   ", background='black', foreground='white')
            armor1acg = ttk.Entry(content, width=20)
            armor1bon = ttk.Entry(content, width=10)
            armor1typ = ttk.Entry(content, width=10)
            armor1chk = ttk.Entry(content, width=12)
            armor1spf = ttk.Entry(content, width=10)
            armor1wgt = ttk.Entry(content, width=10)
            armor1prp = ttk.Entry(content, width=10)
            armor2acg = ttk.Entry(content, width=20)
            armor2bon = ttk.Entry(content, width=10)
            armor2typ = ttk.Entry(content, width=10)
            armor2chk = ttk.Entry(content, width=12)
            armor2spf = ttk.Entry(content, width=10)
            armor2wgt = ttk.Entry(content, width=10)
            armor2prp = ttk.Entry(content, width=10)
            armor3acg = ttk.Entry(content, width=20)
            armor3bon = ttk.Entry(content, width=10)
            armor3typ = ttk.Entry(content, width=10)
            armor3chk = ttk.Entry(content, width=12)
            armor3spf = ttk.Entry(content, width=10)
            armor3wgt = ttk.Entry(content, width=10)
            armor3prp = ttk.Entry(content, width=10)
            armor4acg = ttk.Entry(content, width=20)
            armor4bon = ttk.Entry(content, width=10)
            armor4typ = ttk.Entry(content, width=10)
            armor4chk = ttk.Entry(content, width=12)
            armor4spf = ttk.Entry(content, width=10)
            armor4wgt = ttk.Entry(content, width=10)
            armor4prp = ttk.Entry(content, width=10)
            armor5acg = ttk.Entry(content, width=20)
            armor5bon = ttk.Entry(content, width=10)
            armor5typ = ttk.Entry(content, width=10)
            armor5chk = ttk.Entry(content, width=12)
            armor5spf = ttk.Entry(content, width=10)
            armor5wgt = ttk.Entry(content, width=10)
            armor5prp = ttk.Entry(content, width=10)
            acgtotlbl = ttk.Label(content, text="Totals                              ", background='black', foreground='white')
            acgbontot = ttk.Entry(content, width=10)
            acgtyptot = ttk.Entry(content, width=10)
            acgchktot = ttk.Entry(content, width=12)
            acgspftot = ttk.Entry(content, width=10)
            acgwgttot = ttk.Entry(content, width=10)
            acgprptot = ttk.Entry(content, width=10)

            """ Armor Placement """
            acglbllbl.grid(column = 1, row = 2, columnspan = 2, sticky = (W))
            acgbonlbl.grid(column = 3, row = 2, columnspan = 1, sticky = (W))
            acgtyplbl.grid(column = 4, row = 2, columnspan = 1, sticky = (W))
            acgchklbl.grid(column = 5, row = 2, columnspan = 1, sticky = (W))
            acgspflbl.grid(column = 6, row = 2, columnspan = 1, sticky = (W))
            acgwgtlbl.grid(column = 7, row = 2, columnspan = 1, sticky = (W))
            acgprplbl.grid(column = 8, row = 2, columnspan = 1, sticky = (W))
            armor1acg.grid(column = 1, row = 3, columnspan = 2, sticky = (W))
            armor1bon.grid(column = 3, row = 3, columnspan = 1, sticky = (W))
            armor1typ.grid(column = 4, row = 3, columnspan = 1, sticky = (W))
            armor1chk.grid(column = 5, row = 3, columnspan = 1, sticky = (W))
            armor1spf.grid(column = 6, row = 3, columnspan = 1, sticky = (W))
            armor1wgt.grid(column = 7, row = 3, columnspan = 1, sticky = (W))
            armor1prp.grid(column = 8, row = 3, columnspan = 1, sticky = (W))
            armor2acg.grid(column = 1, row = 4, columnspan = 2, sticky = (W))
            armor2bon.grid(column = 3, row = 4, columnspan = 1, sticky = (W))
            armor2typ.grid(column = 4, row = 4, columnspan = 1, sticky = (W))
            armor2chk.grid(column = 5, row = 4, columnspan = 1, sticky = (W))
            armor2spf.grid(column = 6, row = 4, columnspan = 1, sticky = (W))
            armor2wgt.grid(column = 7, row = 4, columnspan = 1, sticky = (W))
            armor2prp.grid(column = 8, row = 4, columnspan = 1, sticky = (W))
            armor3acg.grid(column = 1, row = 5, columnspan = 2, sticky = (W))
            armor3bon.grid(column = 3, row = 5, columnspan = 1, sticky = (W))
            armor3typ.grid(column = 4, row = 5, columnspan = 1, sticky = (W))
            armor3chk.grid(column = 5, row = 5, columnspan = 1, sticky = (W))
            armor3spf.grid(column = 6, row = 5, columnspan = 1, sticky = (W))
            armor3wgt.grid(column = 7, row = 5, columnspan = 1, sticky = (W))
            armor3prp.grid(column = 8, row = 5, columnspan = 1, sticky = (W))
            armor4acg.grid(column = 1, row = 6, columnspan = 2, sticky = (W))
            armor4bon.grid(column = 3, row = 6, columnspan = 1, sticky = (W))
            armor4typ.grid(column = 4, row = 6, columnspan = 1, sticky = (W))
            armor4chk.grid(column = 5, row = 6, columnspan = 1, sticky = (W))
            armor4spf.grid(column = 6, row = 6, columnspan = 1, sticky = (W))
            armor4wgt.grid(column = 7, row = 6, columnspan = 1, sticky = (W))
            armor4prp.grid(column = 8, row = 6, columnspan = 1, sticky = (W))
            armor5acg.grid(column = 1, row = 7, columnspan = 2, sticky = (W))
            armor5bon.grid(column = 3, row = 7, columnspan = 1, sticky = (W))
            armor5typ.grid(column = 4, row = 7, columnspan = 1, sticky = (W))
            armor5chk.grid(column = 5, row = 7, columnspan = 1, sticky = (W))
            armor5spf.grid(column = 6, row = 7, columnspan = 1, sticky = (W))
            armor5wgt.grid(column = 7, row = 7, columnspan = 1, sticky = (W))
            armor5prp.grid(column = 8, row = 7, columnspan = 1, sticky = (W))
            acgtotlbl.grid(column = 1, row = 8, columnspan = 2, sticky = (W))
            acgbontot.grid(column = 3, row = 8, columnspan = 1, sticky = (W))
            acgtyptot.grid(column = 4, row = 8, columnspan = 1, sticky = (W))
            acgchktot.grid(column = 5, row = 8, columnspan = 1, sticky = (W))
            acgspftot.grid(column = 6, row = 8, columnspan = 1, sticky = (W))
            acgwgttot.grid(column = 7, row = 8, columnspan = 1, sticky = (W))
            acgprptot.grid(column = 8, row = 8, columnspan = 1, sticky = (W))
            
            character.add(content, text='Armor')
            
    def _create_skills_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            """ skills declarations """
            nameslbl = ttk.Label(content, text = "Skill Names")
            totallbl = ttk.Label(content, text = "Total Bonus")
            abltylbl = ttk.Label(content, text = "Ability Mod")
            rankslbl = ttk.Label(content, text = "Ranks Mod")
            miscmlbl = ttk.Label(content, text = "Misc Mod")

            acrochk = ttk.Checkbutton(content, text = "Acrobatics")
            acrob01 = ttk.Entry(content, width = 10)
            acrostt = ttk.Label(content, text = " = DEX ")
            acrob02 = ttk.Entry(content, width = 10)
            acrop01 = ttk.Label(content, text = "+")
            acrob03 = ttk.Entry(content, width = 10)
            acrop02 = ttk.Label(content, text = "+")
            acrob04 = ttk.Entry(content, width = 10)

            apprchk = ttk.Checkbutton(content, text = "Appraise")
            apprb01 = ttk.Entry(content, width = 10)
            apprstt = ttk.Label(content, text = " = INT ")
            aprrb02 = ttk.Entry(content, width = 10)
            apprp01 = ttk.Label(content, text = "+")
            aprrb03 = ttk.Entry(content, width = 10)
            apprp02 = ttk.Label(content, text = "+")
            apprb04 = ttk.Entry(content, width = 10)

            blffchk = ttk.Checkbutton(content, text = "Bluff")
            blffb01 = ttk.Entry(content, width = 10)
            blffstt = ttk.Label(content, text = " = CHA ")
            blffb02 = ttk.Entry(content, width = 10)
            blffp01 = ttk.Label(content, text = "+")
            blffb03 = ttk.Entry(content, width = 10)
            blffp02 = ttk.Label(content, text = "+")
            blffb04 = ttk.Entry(content, width = 10)
            
            clmbchk = ttk.Checkbutton(content, text = "Climb")
            clmbb01 = ttk.Entry(content, width = 10)
            clmbstt = ttk.Label(content, text = " = STR ")
            clmbb02 = ttk.Entry(content, width = 10)
            clmbp01 = ttk.Label(content, text = "+")
            clmbb03 = ttk.Entry(content, width = 10)
            clmbp02 = ttk.Label(content, text = "+")
            clmbb04 = ttk.Entry(content, width = 10)

            cft1chk = ttk.Checkbutton(content, text = "Craft")
            cft1typ = ttk.Entry(content, width = 15)
            cft1b01 = ttk.Entry(content, width = 10)
            cft1stt = ttk.Label(content, text = " = INT ")
            cft1b02 = ttk.Entry(content, width = 10)
            cft1p01 = ttk.Label(content, text = "+")
            cft1b03 = ttk.Entry(content, width = 10)
            cft1p02 = ttk.Label(content, text = "+")
            cft1b04 = ttk.Entry(content, width = 10)

            cft2chk = ttk.Checkbutton(content, text = "Craft")
            cft2typ = ttk.Entry(content, width = 15)
            cft2b01 = ttk.Entry(content, width = 10)
            cft2stt = ttk.Label(content, text = " = INT ")
            cft2b02 = ttk.Entry(content, width = 10)
            cft2p01 = ttk.Label(content, text = "+")
            cft2b03 = ttk.Entry(content, width = 10)
            cft2p02 = ttk.Label(content, text = "+")
            cft2b04 = ttk.Entry(content, width = 10)
            
            cft3chk = ttk.Checkbutton(content, text = "Craft")
            cft3typ = ttk.Entry(content, width = 15)
            cft3b01 = ttk.Entry(content, width = 10)
            cft3stt = ttk.Label(content, text = " = INT ")
            cft3b02 = ttk.Entry(content, width = 10)
            cft3p01 = ttk.Label(content, text = "+")
            cft3b03 = ttk.Entry(content, width = 10)
            cft3p02 = ttk.Label(content, text = "+")
            cft3b04 = ttk.Entry(content, width = 10)

            dplochk = ttk.Checkbutton(content, text = "Diplomacy")
            dplob01 = ttk.Entry(content, width = 10)
            dplostt = ttk.Label(content, text = " = CHA ")
            dplob02 = ttk.Entry(content, width = 10)
            dplop01 = ttk.Label(content, text = "+")
            dplob03 = ttk.Entry(content, width = 10)
            dplop02 = ttk.Label(content, text = "+")
            dplob04 = ttk.Entry(content, width = 10)
            
            dsblchk = ttk.Checkbutton(content, text = "Disable Device*")
            dsblb01 = ttk.Entry(content, width = 10)
            dsblstt = ttk.Label(content, text = " = DEX ")
            dsblb02 = ttk.Entry(content, width = 10)
            dsblp01 = ttk.Label(content, text = "+")
            dsblb03 = ttk.Entry(content, width = 10)
            dsblp02 = ttk.Label(content, text = "+")
            dsblb04 = ttk.Entry(content, width = 10)

            dsgschk = ttk.Checkbutton(content, text = "Disguise")
            dsgsb01 = ttk.Entry(content, width = 10)
            dsgsstt = ttk.Label(content, text = " = CHA ")
            dsgsb02 = ttk.Entry(content, width = 10)
            dsgsp01 = ttk.Label(content, text = "+")
            dsgsb03 = ttk.Entry(content, width = 10)
            dsgsp02 = ttk.Label(content, text = "+")
            dsgsb04 = ttk.Entry(content, width = 10)

            escpchk = ttk.Checkbutton(content, text = "Escape Artist")
            escpb01 = ttk.Entry(content, width = 10)
            escpstt = ttk.Label(content, text = " = DEX ")
            escpb02 = ttk.Entry(content, width = 10)
            escpp01 = ttk.Label(content, text = "+")
            escpb03 = ttk.Entry(content, width = 10)
            escpp02 = ttk.Label(content, text = "+")
            escpb04 = ttk.Entry(content, width = 10)

            flyschk = ttk.Checkbutton(content, text = "Fly")
            flysb01 = ttk.Entry(content, width = 10)
            flysstt = ttk.Label(content, text = " = DEX ")
            flysb02 = ttk.Entry(content, width = 10)
            flysp01 = ttk.Label(content, text = "+")
            flysb03 = ttk.Entry(content, width = 10)
            flysp02 = ttk.Label(content, text = "+")
            flysb04 = ttk.Entry(content, width = 10)

            hdlachk = ttk.Checkbutton(content, text = "Handle Animal*")
            hdlab01 = ttk.Entry(content, width = 10)
            hdlastt = ttk.Label(content, text = " = CHA ")
            hdlab02 = ttk.Entry(content, width = 10)
            hdlap01 = ttk.Label(content, text = "+")
            hdlab03 = ttk.Entry(content, width = 10)
            hdlap02 = ttk.Label(content, text = "+")
            hdlab04 = ttk.Entry(content, width = 10)

            healchk = ttk.Checkbutton(content, text = "Heal")
            healb01 = ttk.Entry(content, width = 10)
            healstt = ttk.Label(content, text = " = WIS ")
            healb02 = ttk.Entry(content, width = 10)
            healp01 = ttk.Label(content, text = "+")
            healb03 = ttk.Entry(content, width = 10)
            healp02 = ttk.Label(content, text = "+")
            healb04 = ttk.Entry(content, width = 10)

            ntmdchk = ttk.Checkbutton(content, text = "Intimidate")
            ntmdb01 = ttk.Entry(content, width = 10)
            ntmdstt = ttk.Label(content, text = " = CHA ")
            ntmdb02 = ttk.Entry(content, width = 10)
            ntmdp01 = ttk.Label(content, text = "+")
            ntmdb03 = ttk.Entry(content, width = 10)
            ntmdp02 = ttk.Label(content, text = "+")
            ntmdb04 = ttk.Entry(content, width = 10)

            arcnchk = ttk.Checkbutton(content, text = "Knowledge (Arcana)*")
            arcnb01 = ttk.Entry(content, width = 10)
            arcnstt = ttk.Label(content, text = " = INT ")
            arcnb02 = ttk.Entry(content, width = 10)
            arcnp01 = ttk.Label(content, text = "+")
            arcnb03 = ttk.Entry(content, width = 10)
            arcnp02 = ttk.Label(content, text = "+")
            arcnb04 = ttk.Entry(content, width = 10)

            dngnchk = ttk.Checkbutton(content, text = "Knowledge (Dungeoneering)*")
            dngnb01 = ttk.Entry(content, width = 10)
            dngnstt = ttk.Label(content, text = " = INT ")
            dngnb02 = ttk.Entry(content, width = 10)
            dngnp01 = ttk.Label(content, text = "+")
            dngnb03 = ttk.Entry(content, width = 10)
            dngnp02 = ttk.Label(content, text = "+")
            dngnb04 = ttk.Entry(content, width = 10)

            engnchk = ttk.Checkbutton(content, text = "Knowledge (Engineering)*")
            engnb01 = ttk.Entry(content, width = 10)
            engnstt = ttk.Label(content, text = " = INT ")
            engnb02 = ttk.Entry(content, width = 10)
            engnp01 = ttk.Label(content, text = "+")
            engnb03 = ttk.Entry(content, width = 10)
            engnp02 = ttk.Label(content, text = "+")
            engnb04 = ttk.Entry(content, width = 10)

            geogchk = ttk.Checkbutton(content, text = "Knowledge (Geography)*")
            geogb01 = ttk.Entry(content, width = 10)
            geogstt = ttk.Label(content, text = " = INT ")
            geogb02 = ttk.Entry(content, width = 10)
            geogp01 = ttk.Label(content, text = "+")
            geogb03 = ttk.Entry(content, width = 10)
            geogp02 = ttk.Label(content, text = "+")
            geogb04 = ttk.Entry(content, width = 10)

            histchk = ttk.Checkbutton(content, text = "Knowledge (History)*")
            histb01 = ttk.Entry(content, width = 10)
            histstt = ttk.Label(content, text = " = INT ")
            histb02 = ttk.Entry(content, width = 10)
            histp01 = ttk.Label(content, text = "+")
            histb03 = ttk.Entry(content, width = 10)
            histp02 = ttk.Label(content, text = "+")
            histb04 = ttk.Entry(content, width = 10)

            loclchk = ttk.Checkbutton(content, text = "Knowledge (Local)*")
            loclb01 = ttk.Entry(content, width = 10)
            loclstt = ttk.Label(content, text = " = INT ")
            loclb02 = ttk.Entry(content, width = 10)
            loclp01 = ttk.Label(content, text = "+")
            loclb03 = ttk.Entry(content, width = 10)
            loclp02 = ttk.Label(content, text = "+")
            loclb04 = ttk.Entry(content, width = 10)

            ntrechk = ttk.Checkbutton(content, text = "Knowledge (Nature)*")
            ntreb01 = ttk.Entry(content, width = 10)
            ntrestt = ttk.Label(content, text = " = INT ")
            ntreb02 = ttk.Entry(content, width = 10)
            ntrep01 = ttk.Label(content, text = "+")
            ntreb03 = ttk.Entry(content, width = 10)
            ntrep02 = ttk.Label(content, text = "+")
            ntreb04 = ttk.Entry(content, width = 10)

            noblchk = ttk.Checkbutton(content, text = "Knowledge (Nobility)*")
            nobllbl = ttk.Entry(content, width = 10)
            noblb01 = ttk.Entry(content, width = 10)
            noblstt = ttk.Label(content, text = " = INT ")
            noblb02 = ttk.Entry(content, width = 10)
            noblp01 = ttk.Label(content, text = "+")
            noblb03 = ttk.Entry(content, width = 10)
            noblp02 = ttk.Label(content, text = "+")
            noblb04 = ttk.Entry(content, width = 10)

            planchk = ttk.Checkbutton(content, text = "Knowledge (Planes)*")
            planb01 = ttk.Entry(content, width = 10)
            planstt = ttk.Label(content, text = " = INT ")
            planb02 = ttk.Entry(content, width = 10)
            planp01 = ttk.Label(content, text = "+")
            planb03 = ttk.Entry(content, width = 10)
            planp02 = ttk.Label(content, text = "+")
            planb04 = ttk.Entry(content, width = 10)

            relgchk = ttk.Checkbutton(content, text = "Knowledge (Religion)*")
            relgb01 = ttk.Entry(content, width = 10)
            relgstt = ttk.Label(content, text = " = INT ")
            relgb02 = ttk.Entry(content, width = 10)
            relgp01 = ttk.Label(content, text = "+")
            relgb03 = ttk.Entry(content, width = 10)
            relgp02 = ttk.Label(content, text = "+")
            relgb04 = ttk.Entry(content, width = 10)

            lngschk = ttk.Checkbutton(content, text = "Knowledge (Arcana)*")
            lngsb01 = ttk.Entry(content, width = 10)
            lngsstt = ttk.Label(content, text = " = INT ")
            lngsb02 = ttk.Entry(content, width = 10)
            lngsp01 = ttk.Label(content, text = "+")
            lngsb03 = ttk.Entry(content, width = 10)
            lngsp02 = ttk.Label(content, text = "+")
            lngsb04 = ttk.Entry(content, width = 10)

            prcpchk = ttk.Checkbutton(content, text = "Linguistics*")
            prcpb01 = ttk.Entry(content, width = 10)
            prcpstt = ttk.Label(content, text = " = INT ")
            prcpb02 = ttk.Entry(content, width = 10)
            prcpp01 = ttk.Label(content, text = "+")
            prcpb03 = ttk.Entry(content, width = 10)
            prcpp02 = ttk.Label(content, text = "+")
            prcpb04 = ttk.Entry(content, width = 10)

            pfm1chk = ttk.Checkbutton(content, text = "Perform")
            pfm1typ = ttk.Entry(content, width = 15)
            pfm1b01 = ttk.Entry(content, width = 10)
            pfm1stt = ttk.Label(content, text = " = WIS ")
            pfm1b02 = ttk.Entry(content, width = 10)
            pfm1p01 = ttk.Label(content, text = "+")
            pfm1b03 = ttk.Entry(content, width = 10)
            pfm1p02 = ttk.Label(content, text = "+")
            pfm1b04 = ttk.Entry(content, width = 10)

            pfm2chk = ttk.Checkbutton(content, text = "Perform")
            pfm2typ = ttk.Entry(content, width = 15)
            pfm2b01 = ttk.Entry(content, width = 10)
            pfm2stt = ttk.Label(content, text = " = CHA ")
            pfm2b02 = ttk.Entry(content, width = 10)
            pfm2p01 = ttk.Label(content, text = "+")
            pfm2b03 = ttk.Entry(content, width = 10)
            pfm2p02 = ttk.Label(content, text = "+")
            pfm2b04 = ttk.Entry(content, width = 10)

            prf1chk = ttk.Checkbutton(content, text = "Profession*")
            prf1typ = ttk.Entry(content, width = 15)
            prf1b01 = ttk.Entry(content, width = 10)
            prf1stt = ttk.Label(content, text = " = CHA ")
            prf1b02 = ttk.Entry(content, width = 10)
            prf1p01 = ttk.Label(content, text = "+")
            prf1b03 = ttk.Entry(content, width = 10)
            prf1p02 = ttk.Label(content, text = "+")
            prf1b04 = ttk.Entry(content, width = 10)

            prf2chk = ttk.Checkbutton(content, text = "Profession*")
            prf2typ = ttk.Entry(content, width = 15)
            prf2b01 = ttk.Entry(content, width = 10)
            prf2stt = ttk.Label(content, text = " = WIS ")
            prf2b02 = ttk.Entry(content, width = 10)
            prf2p01 = ttk.Label(content, text = "+")
            prf2b03 = ttk.Entry(content, width = 10)
            prf2p02 = ttk.Label(content, text = "+")
            prf2b04 = ttk.Entry(content, width = 10)

            ridechk = ttk.Checkbutton(content, text = "Ride")
            rideb01 = ttk.Entry(content, width = 10)
            ridestt = ttk.Label(content, text = " = DEX ")
            rideb02 = ttk.Entry(content, width = 10)
            ridep01 = ttk.Label(content, text = "+")
            rideb03 = ttk.Entry(content, width = 10)
            ridep02 = ttk.Label(content, text = "+")
            rideb04 = ttk.Entry(content, width = 10)

            snsmchk = ttk.Checkbutton(content, text = "Sense Motive")
            snsmb01 = ttk.Entry(content, width = 10)
            snsmstt = ttk.Label(content, text = " = WIS ")
            snsmb02 = ttk.Entry(content, width = 10)
            snsmp01 = ttk.Label(content, text = "+")
            snsmb03 = ttk.Entry(content, width = 10)
            snsmp02 = ttk.Label(content, text = "+")
            snsmb04 = ttk.Entry(content, width = 10)

            slohchk = ttk.Checkbutton(content, text = "Sleight of Hand*")
            slohb01 = ttk.Entry(content, width = 10)
            slohstt = ttk.Label(content, text = " = DEX ")
            slohb02 = ttk.Entry(content, width = 10)
            slohp01 = ttk.Label(content, text = "+")
            slohb03 = ttk.Entry(content, width = 10)
            slohp02 = ttk.Label(content, text = "+")
            slohb04 = ttk.Entry(content, width = 10)

            scftchk = ttk.Checkbutton(content, text = "Spellcraft*")
            scftb01 = ttk.Entry(content, width = 10)
            scftstt = ttk.Label(content, text = " = INT ")
            scftb02 = ttk.Entry(content, width = 10)
            scftp01 = ttk.Label(content, text = "+")
            scftb03 = ttk.Entry(content, width = 10)
            scftp02 = ttk.Label(content, text = "+")
            scftb04 = ttk.Entry(content, width = 10)

            stltchk = ttk.Checkbutton(content, text = "Stealth")
            stltb01 = ttk.Entry(content, width = 10)
            stltstt = ttk.Label(content, text = " = DEX ")
            stltb02 = ttk.Entry(content, width = 10)
            stltp01 = ttk.Label(content, text = "+")
            stltb03 = ttk.Entry(content, width = 10)
            stltp02 = ttk.Label(content, text = "+")
            stltb04 = ttk.Entry(content, width = 10)

            srvlchk = ttk.Checkbutton(content, text = "Survival")
            srvlb01 = ttk.Entry(content, width = 10)
            srvlstt = ttk.Label(content, text = " = WIS ")
            srvlb02 = ttk.Entry(content, width = 10)
            srvlp01 = ttk.Label(content, text = "+")
            srvlb03 = ttk.Entry(content, width = 10)
            srvlp02 = ttk.Label(content, text = "+")
            srvlb04 = ttk.Entry(content, width = 10)

            swimchk = ttk.Checkbutton(content, text = "Swim")
            swimb01 = ttk.Entry(content, width = 10)
            swimstt = ttk.Label(content, text = " = STR ")
            swimb02 = ttk.Entry(content, width = 10)
            swimp01 = ttk.Label(content, text = "+")
            swimb03 = ttk.Entry(content, width = 10)
            swimp02 = ttk.Label(content, text = "+")
            swimb04 = ttk.Entry(content, width = 10)

            umdvchk = ttk.Checkbutton(content, text = "Use Magic Device*")
            umdvb01 = ttk.Entry(content, width = 10)
            umdvstt = ttk.Label(content, text = " = CHA ")
            umdvb02 = ttk.Entry(content, width = 10)
            umdvp01 = ttk.Label(content, text = "+")
            umdvb03 = ttk.Entry(content, width = 10)
            umdvp02 = ttk.Label(content, text = "+")
            umdvb04 = ttk.Entry(content, width = 10)

            trnonly = ttk.Label(content, text = "*Trained Only")
                                
            """ skills placement """

            nameslbl.grid(column = 1, row = 2, columnspan=4, sticky = (W))
            totallbl.grid(column = 5, row = 2)
            abltylbl.grid(column = 7, row = 2)
            rankslbl.grid(column = 9, row = 2)
            miscmlbl.grid(column = 11, row = 2)

            acrochk.grid(column = 1, row = 3, columnspan=4, sticky = (W))
            acrob01.grid(column = 5, row = 3)
            acrostt.grid(column = 6, row = 3)
            acrob02.grid(column = 7, row = 3)
            acrop01.grid(column = 8, row = 3)
            acrob03.grid(column = 9, row = 3)
            acrop02.grid(column = 10, row = 3)
            acrob04.grid(column = 11, row = 3)

            apprchk.grid(column = 1, row = 4, columnspan=4, sticky = (W))
            apprb01.grid(column = 5, row = 4)
            apprstt.grid(column = 6, row = 4)
            aprrb02.grid(column = 7, row = 4)
            apprp01.grid(column = 8, row = 4)
            aprrb03.grid(column = 9, row = 4)
            apprp02.grid(column = 10, row = 4)
            apprb04.grid(column = 11, row = 4)

            blffchk.grid(column = 1, row = 5, columnspan=4, sticky = (W))
            blffb01.grid(column = 5, row = 5)
            blffstt.grid(column = 6, row = 5)
            blffb02.grid(column = 7, row = 5)
            blffp01.grid(column = 8, row = 5)
            blffb03.grid(column = 9, row = 5)
            blffp02.grid(column = 10, row = 5)
            blffb04.grid(column = 11, row = 5)
            
            clmbchk.grid(column = 1, row = 6, columnspan=4, sticky = (W))
            clmbb01.grid(column = 5, row = 6)
            clmbstt.grid(column = 6, row = 6)
            clmbb02.grid(column = 7, row = 6)
            clmbp01.grid(column = 8, row = 6)
            clmbb03.grid(column = 9, row = 6)
            clmbp02.grid(column = 10, row = 6)
            clmbb04.grid(column = 11, row = 6)

            cft1chk.grid(column = 1, row = 7, columnspan=4, sticky = (W))
            cft1typ.grid(column = 4, row = 7)
            cft1b01.grid(column = 5, row = 7)
            cft1stt.grid(column = 6, row = 7)
            cft1b02.grid(column = 7, row = 7)
            cft1p01.grid(column = 8, row = 7)
            cft1b03.grid(column = 9, row = 7)
            cft1p02.grid(column = 10, row = 7)
            cft1b04.grid(column = 11, row = 7)

            cft2chk.grid(column = 1, row = 8, columnspan=4, sticky = (W))
            cft2typ.grid(column = 4, row = 8)
            cft2b01.grid(column = 5, row = 8)
            cft2stt.grid(column = 6, row = 8)
            cft2b02.grid(column = 7, row = 8)
            cft2p01.grid(column = 8, row = 8)
            cft2b03.grid(column = 9, row = 8)
            cft2p02.grid(column = 10, row = 8)
            cft2b04.grid(column = 11, row = 8)
            
            cft3chk.grid(column = 1, row = 9, columnspan=4, sticky = (W))
            cft3typ.grid(column = 4, row = 9)
            cft3b01.grid(column = 5, row = 9)
            cft3stt.grid(column = 6, row = 9)
            cft3b02.grid(column = 7, row = 9)
            cft3p01.grid(column = 8, row = 9)
            cft3b03.grid(column = 9, row = 9)
            cft3p02.grid(column = 10, row = 9)
            cft3b04.grid(column = 11, row = 9)

            dplochk.grid(column = 1, row = 10, columnspan=4, sticky = (W))
            dplob01.grid(column = 5, row = 10)
            dplostt.grid(column = 6, row = 10)
            dplob02.grid(column = 7, row = 10)
            dplop01.grid(column = 8, row = 10)
            dplob03.grid(column = 9, row = 10)
            dplop02.grid(column = 10, row = 10)
            dplob04.grid(column = 11, row = 10)
            
            dsblchk.grid(column = 1, row = 11, columnspan=4, sticky = (W))
            dsblb01.grid(column = 5, row = 11)
            dsblstt.grid(column = 6, row = 11)
            dsblb02.grid(column = 7, row = 11)
            dsblp01.grid(column = 8, row = 11)
            dsblb03.grid(column = 9, row = 11)
            dsblp02.grid(column = 10, row = 11)
            dsblb04.grid(column = 11, row = 11)

            dsgschk.grid(column = 1, row = 12, columnspan=4, sticky = (W))
            dsgsb01.grid(column = 5, row = 12)
            dsgsstt.grid(column = 6, row = 12)
            dsgsb02.grid(column = 7, row = 12)
            dsgsp01.grid(column = 8, row = 12)
            dsgsb03.grid(column = 9, row = 12)
            dsgsp02.grid(column = 10, row = 12)
            dsgsb04.grid(column = 11, row = 12)

            escpchk.grid(column = 1, row = 13, columnspan=4, sticky = (W))
            escpb01.grid(column = 5, row = 13)
            escpstt.grid(column = 6, row = 13)
            escpb02.grid(column = 7, row = 13)
            escpp01.grid(column = 8, row = 13)
            escpb03.grid(column = 9, row = 13)
            escpp02.grid(column = 10, row = 13)
            escpb04.grid(column = 11, row = 13)

            flyschk.grid(column = 1, row = 14, columnspan=4, sticky = (W))
            flysb01.grid(column = 5, row = 14)
            flysstt.grid(column = 6, row = 14)
            flysb02.grid(column = 7, row = 14)
            flysp01.grid(column = 8, row = 14)
            flysb03.grid(column = 9, row = 14)
            flysp02.grid(column = 10, row = 14)
            flysb04.grid(column = 11, row = 14)

            hdlachk.grid(column = 1, row = 15, columnspan=4, sticky = (W))
            hdlab01.grid(column = 5, row = 15)
            hdlastt.grid(column = 6, row = 15)
            hdlab02.grid(column = 7, row = 15)
            hdlap01.grid(column = 8, row = 15)
            hdlab03.grid(column = 9, row = 15)
            hdlap02.grid(column = 10, row = 15)
            hdlab04.grid(column = 11, row = 15)

            healchk.grid(column = 1, row = 16, columnspan=4, sticky = (W))
            healb01.grid(column = 5, row = 16)
            healstt.grid(column = 6, row = 16)
            healb02.grid(column = 7, row = 16)
            healp01.grid(column = 8, row = 16)
            healb03.grid(column = 9, row = 16)
            healp02.grid(column = 10, row = 16)
            healb04.grid(column = 11, row = 16)

            ntmdchk.grid(column = 1, row = 17, columnspan=4, sticky = (W))
            ntmdb01.grid(column = 5, row = 17)
            ntmdstt.grid(column = 6, row = 17)
            ntmdb02.grid(column = 7, row = 17)
            ntmdp01.grid(column = 8, row = 17)
            ntmdb03.grid(column = 9, row = 17)
            ntmdp02.grid(column = 10, row = 17)
            ntmdb04.grid(column = 11, row = 17)

            arcnchk.grid(column = 1, row = 18, columnspan=4, sticky = (W))
            arcnb01.grid(column = 5, row = 18)
            arcnstt.grid(column = 6, row = 18)
            arcnb02.grid(column = 7, row = 18)
            arcnp01.grid(column = 8, row = 18)
            arcnb03.grid(column = 9, row = 18)
            arcnp02.grid(column = 10, row = 18)
            arcnb04.grid(column = 11, row = 18)

            dngnchk.grid(column = 1, row = 19, columnspan=4, sticky = (W))
            dngnb01.grid(column = 5, row = 19)
            dngnstt.grid(column = 6, row = 19)
            dngnb02.grid(column = 7, row = 19)
            dngnp01.grid(column = 8, row = 19)
            dngnb03.grid(column = 9, row = 19)
            dngnp02.grid(column = 10, row = 19)
            dngnb04.grid(column = 11, row = 19)

            engnchk.grid(column = 1, row = 20, columnspan=4, sticky = (W))
            engnb01.grid(column = 5, row = 20)
            engnstt.grid(column = 6, row = 20)
            engnb02.grid(column = 7, row = 20)
            engnp01.grid(column = 8, row = 20)
            engnb03.grid(column = 9, row = 20)
            engnp02.grid(column = 10, row = 20)
            engnb04.grid(column = 11, row = 20)

            geogchk.grid(column = 1, row = 21, columnspan=4, sticky = (W))
            geogb01.grid(column = 5, row = 21)
            geogstt.grid(column = 6, row = 21)
            geogb02.grid(column = 7, row = 21)
            geogp01.grid(column = 8, row = 21)
            geogb03.grid(column = 9, row = 21)
            geogp02.grid(column = 10, row = 21)
            geogb04.grid(column = 11, row = 21)

            histchk.grid(column = 1, row = 22, columnspan=4, sticky = (W))
            histb01.grid(column = 5, row = 22)
            histstt.grid(column = 6, row = 22)
            histb02.grid(column = 7, row = 22)
            histp01.grid(column = 8, row = 22)
            histb03.grid(column = 9, row = 22)
            histp02.grid(column = 10, row = 22)
            histb04.grid(column = 11, row = 22)

            loclchk.grid(column = 1, row = 23, columnspan=4, sticky = (W))
            loclb01.grid(column = 5, row = 23)
            loclstt.grid(column = 6, row = 23)
            loclb02.grid(column = 7, row = 23)
            loclp01.grid(column = 8, row = 23)
            loclb03.grid(column = 9, row = 23)
            loclp02.grid(column = 10, row = 23)
            loclb04.grid(column = 11, row = 23)

            ntrechk.grid(column = 1, row = 24, columnspan=4, sticky = (W))
            ntreb01.grid(column = 5, row = 24)
            ntrestt.grid(column = 6, row = 24)
            ntreb02.grid(column = 7, row = 24)
            ntrep01.grid(column = 8, row = 24)
            ntreb03.grid(column = 9, row = 24)
            ntrep02.grid(column = 10, row = 24)
            ntreb04.grid(column = 11, row = 24)

            noblchk.grid(column = 1, row = 25, columnspan=4, sticky = (W))
            noblb01.grid(column = 5, row = 25)
            noblstt.grid(column = 6, row = 25)
            noblb02.grid(column = 7, row = 25)
            noblp01.grid(column = 8, row = 25)
            noblb03.grid(column = 9, row = 25)
            noblp02.grid(column = 10, row = 25)
            noblb04.grid(column = 11, row = 25)

            planchk.grid(column = 1, row = 26, columnspan=4, sticky = (W))
            planb01.grid(column = 5, row = 26)
            planstt.grid(column = 6, row = 26)
            planb02.grid(column = 7, row = 26)
            planp01.grid(column = 8, row = 26)
            planb03.grid(column = 9, row = 26)
            planp02.grid(column = 10, row = 26)
            planb04.grid(column = 11, row = 26)

            relgchk.grid(column = 1, row = 27, columnspan=4, sticky = (W))
            relgb01.grid(column = 5, row = 27)
            relgstt.grid(column = 6, row = 27)
            relgb02.grid(column = 7, row = 27)
            relgp01.grid(column = 8, row = 27)
            relgb03.grid(column = 9, row = 27)
            relgp02.grid(column = 10, row = 27)
            relgb04.grid(column = 11, row = 27)

            lngschk.grid(column = 1, row = 28, columnspan=4, sticky = (W))
            lngsb01.grid(column = 5, row = 28)
            lngsstt.grid(column = 6, row = 28)
            lngsb02.grid(column = 7, row = 28)
            lngsp01.grid(column = 8, row = 28)
            lngsb03.grid(column = 9, row = 28)
            lngsp02.grid(column = 10, row = 28)
            lngsb04.grid(column = 11, row = 28)

            prcpchk.grid(column = 1, row = 29, columnspan=4, sticky = (W))
            prcpb01.grid(column = 5, row = 29)
            prcpstt.grid(column = 6, row = 29)
            prcpb02.grid(column = 7, row = 29)
            prcpp01.grid(column = 8, row = 29)
            prcpb03.grid(column = 9, row = 29)
            prcpp02.grid(column = 10, row = 29)
            prcpb04.grid(column = 11, row = 29)

            pfm1chk.grid(column = 1, row = 30, columnspan=4, sticky = (W))
            pfm1typ.grid(column = 4, row = 30)
            pfm1b01.grid(column = 5, row = 30)
            pfm1stt.grid(column = 6, row = 30)
            pfm1b02.grid(column = 7, row = 30)
            pfm1p01.grid(column = 8, row = 30)
            pfm1b03.grid(column = 9, row = 30)
            pfm1p02.grid(column = 10, row = 30)
            pfm1b04.grid(column = 11, row = 30)

            pfm2chk.grid(column = 1, row = 31, columnspan=4, sticky = (W))
            pfm2typ.grid(column = 4, row = 31)
            pfm2b01.grid(column = 5, row = 31)
            pfm2stt.grid(column = 6, row = 31)
            pfm2b02.grid(column = 7, row = 31)
            pfm2p01.grid(column = 8, row = 31)
            pfm2b03.grid(column = 9, row = 31)
            pfm2p02.grid(column = 10, row = 31)
            pfm2b04.grid(column = 11, row = 31)

            prf1chk.grid(column = 1, row = 32, columnspan=4, sticky = (W))
            prf1typ.grid(column = 4, row = 32)
            prf1b01.grid(column = 5, row = 32)
            prf1stt.grid(column = 6, row = 32)
            prf1b02.grid(column = 7, row = 32)
            prf1p01.grid(column = 8, row = 32)
            prf1b03.grid(column = 9, row = 32)
            prf1p02.grid(column = 10, row = 32)
            prf1b04.grid(column = 11, row = 32)

            prf2chk.grid(column = 1, row = 33, columnspan=4, sticky = (W))
            prf2typ.grid(column = 4, row = 33)
            prf2b01.grid(column = 5, row = 33)
            prf2stt.grid(column = 6, row = 33)
            prf2b02.grid(column = 7, row = 33)
            prf2p01.grid(column = 8, row = 33)
            prf2b03.grid(column = 9, row = 33)
            prf2p02.grid(column = 10, row = 33)
            prf2b04.grid(column = 11, row = 33)

            ridechk.grid(column = 1, row = 34, columnspan=4, sticky = (W))
            rideb01.grid(column = 5, row = 34)
            ridestt.grid(column = 6, row = 34)
            rideb02.grid(column = 7, row = 34)
            ridep01.grid(column = 8, row = 34)
            rideb03.grid(column = 9, row = 34)
            ridep02.grid(column = 10, row = 34)
            rideb04.grid(column = 11, row = 34)

            snsmchk.grid(column = 1, row = 35, columnspan=4, sticky = (W))
            snsmb01.grid(column = 5, row = 35)
            snsmstt.grid(column = 6, row = 35)
            snsmb02.grid(column = 7, row = 35)
            snsmp01.grid(column = 8, row = 35)
            snsmb03.grid(column = 9, row = 35)
            snsmp02.grid(column = 10, row = 35)
            snsmb04.grid(column = 11, row = 35)

            slohchk.grid(column = 1, row = 36, columnspan=4, sticky = (W))
            slohb01.grid(column = 5, row = 36)
            slohstt.grid(column = 6, row = 36)
            slohb02.grid(column = 7, row = 36)
            slohp01.grid(column = 8, row = 36)
            slohb03.grid(column = 9, row = 36)
            slohp02.grid(column = 10, row = 36)
            slohb04.grid(column = 11, row = 36)

            scftchk.grid(column = 1, row = 37, columnspan=4, sticky = (W))
            scftb01.grid(column = 5, row = 37)
            scftstt.grid(column = 6, row = 37)
            scftb02.grid(column = 7, row = 37)
            scftp01.grid(column = 8, row = 37)
            scftb03.grid(column = 9, row = 37)
            scftp02.grid(column = 10, row = 37)
            scftb04.grid(column = 11, row = 37)

            stltchk.grid(column = 1, row = 38, columnspan=4, sticky = (W))
            stltb01.grid(column = 5, row = 38)
            stltstt.grid(column = 6, row = 38)
            stltb02.grid(column = 7, row = 38)
            stltp01.grid(column = 8, row = 38)
            stltb03.grid(column = 9, row = 38)
            stltp02.grid(column = 10, row = 38)
            stltb04.grid(column = 11, row = 38)

            srvlchk.grid(column = 1, row = 39, columnspan=4, sticky = (W))
            srvlb01.grid(column = 5, row = 39)
            srvlstt.grid(column = 6, row = 39)
            srvlb02.grid(column = 7, row = 39)
            srvlp01.grid(column = 8, row = 39)
            srvlb03.grid(column = 9, row = 39)
            srvlp02.grid(column = 10, row = 39)
            srvlb04.grid(column = 11, row = 39)

            swimchk.grid(column = 1, row = 40, columnspan=4, sticky = (W))
            swimb01.grid(column = 5, row = 40)
            swimstt.grid(column = 6, row = 40)
            swimb02.grid(column = 7, row = 40)
            swimp01.grid(column = 8, row = 40)
            swimb03.grid(column = 9, row = 40)
            swimp02.grid(column = 10, row = 40)
            swimb04.grid(column = 11, row = 40)

            umdvchk.grid(column = 1, row = 41, columnspan=4, sticky = (W))
            umdvb01.grid(column = 5, row = 41)
            umdvstt.grid(column = 6, row = 41)
            umdvb02.grid(column = 7, row = 41)
            umdvp01.grid(column = 8, row = 41)
            umdvb03.grid(column = 9, row = 41)
            umdvp02.grid(column = 10, row = 41)
            umdvb04.grid(column = 11, row = 41)

            trnonly.grid(column = 1, row = 42)
            
            character.add(content, text='Skills')

    def _create_spells_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            

            character.add(content, text='Spells')
            
if __name__ == '__main__':
    PathfinderGUI().mainloop()
