from tkinter import *
from tkinter import ttk
import search_database
from search_database import search_db
import Character

Test = Character.Character()
Test.stats['str'] = 15
Test.stats['dex'] = 18
Test.stats['int'] = 14
Test.stats['con'] = 16
Test.stats['wis'] = 12
Test.stats['cha'] = 4

Current = Character.Character()

root = Tk()

def Show(event):
    print (Current.name)

class PathfinderGUI(ttk.Frame):    
        
       
    def __init__(self, name='pathfindergui'):
            ttk.Frame.__init__(self, name=name)
            self.pack(expand=Y, fill=BOTH)
            self.master.title('NoWhere Pathfinder Assistant')
            Panel = Frame(self, name='char')
            Panel.pack(side=TOP, fill=BOTH, expand=Y)

            style = ttk.Style()
            style.map("TEntry", background=[("active","white"),("disabled","red")])
            
            character =ttk.Notebook(Panel, name='character')
            character.enable_traversal()
            character.pack(fill=BOTH, expand=Y, padx=2, pady=3)
            self._create_information_tab(character)
            self._create_abilities_tab(character)
            self._create_inventory_tab(character)
            self._create_weapons_tab(character)
            self._create_armor_tab(character)
            self._create_skills_tab(character)
            self._create_spells_tab(character)

    def update(event, target, data):
            if target =='charname':
                Current.name = data.get()
            elif target == 'align':
                Current.alignment = data.get()
            elif target == 'playername':
                Current.alignment = data.get()
            elif target == 'deity':
                Current.deity = data.get()
            elif target == 'homeland':
                Current.homeland = data.get()
            elif target == 'gender':
                Current.gender = data.get()
            elif target == 'age':
                Current.age = data.get()
            elif target == 'height':
                Current.height = data.get()
            elif target == 'weight':
                Current.weight = data.get()
            elif target == 'hair':
                Current.hair = data.get()
            elif target == 'eyes':
                Current.eyes = data.get()
        
            
    def _create_information_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            ibuttonlbl = ttk.Label(content, text = " ")
            ibuttonnew = ttk.Button(content, text = "New", width = 10)
            ibuttonsave = ttk.Button(content, text = "Save", width = 10)
            ibuttonload = ttk.Button(content, text = "Load", width = 10)
            ibuttonexit = ttk.Button(content, text = "Exit", width = 10)

            """varaible declarations for comboboxes"""
            namevar=StringVar()
            alignmentvar= StringVar()
            playervar = StringVar()
            deityvar = StringVar()
            racevar = StringVar()
            sizevar = StringVar()
            lang1 = StringVar()
            lang2 = StringVar()
            lang3 = StringVar()
            lang4 = StringVar()
            lang5 = StringVar()
            lang6 = StringVar()
            homelandvar = StringVar()
            gendervar = StringVar()
            agevar = IntVar()
            heightvar = StringVar()
            weightvar = IntVar()
            hairvar = StringVar()
            eyesvar = StringVar()
            
            """ basic character information declaration """
            name = ttk.Entry(content, width=58, textvariable=namevar)
            name.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'charname', namevar))
            namelbl = ttk.Label(content, text="Character Name")
            align = ttk.Combobox(content, width=10, textvariable=alignmentvar,values=search_db('al_name','Alignments',' '))
            align.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'align', alignmentvar))
            alignlbl = ttk.Label(content, text="Alignment")
            player = ttk.Entry(content, width=43, textvariable=playervar)
            player.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'playername', playervar))
            playerlbl = ttk.Label(content, text="Player")
            level = ttk.Entry(content, width=72) # should be read only but requires classes.
            levellbl = ttk.Label(content, text="Character Class and Level")
            deity = ttk.Entry(content, width=21, textvariable=deityvar)
            deity.bind('<FocusOut>', lambda x: PathdfinderGUI.update(x, 'deity', deityvar))
            deitylbl = ttk.Label(content, text="Deity")
            homeland = ttk.Entry(content, width=21, textvariable=homelandvar)
            homeland.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'homeland', homelandvar))
            homelandlbl = ttk.Label(content, text="Homeland")
            race = ttk.Entry(content, width=39)
            racelbl = ttk.Label(content, text="Race")    
            size = ttk.Entry(content, width=18)
            sizelbl = ttk.Label(content, text="Size")
            gender = ttk.Entry(content, width=8, textvariable=gendervar)
            gender.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'gender', gendervar))
            genderlbl = ttk.Label(content, text="Gender")
            age = ttk.Entry(content, width=4, textvariable=agevar)
            age.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'age', agevar))
            agelbl = ttk.Label(content, text="Age")
            height = ttk.Entry(content, width=10, textvariable=heightvar)
            height.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'height', heightvar))
            heightlbl = ttk.Label(content, text="Height")
            weight = ttk.Entry(content, width=10, textvariable=weightvar)
            weight.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'weight', weightvar))
            weightlbl = ttk.Label(content, text="Weight")
            hair = ttk.Entry(content, width=10, textvariable=hairvar)
            hair.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'hair', hairvar))
            hairlbl = ttk.Label(content, text="Hair")
            eyes = ttk.Entry(content, width=10, textvariable=eyesvar)
            eyes.bind('<FocusOut>', lambda x: PathfinderGUI.update(x, 'eyes', eyesvar))
            eyeslbl = ttk.Label(content, text="Eyes")
            languagelbl = ttk.Label(content, text = "Languages Spoken", background='black', foreground='white')
            language1 = ttk.Combobox(content, width = 15, textvariable=lang1, values=search_db('la_name','Languages',''))
            language2 = ttk.Combobox(content, width = 15, textvariable=lang2, values=search_db('la_name','Languages',''))
            language3 = ttk.Combobox(content, width = 15, textvariable=lang3, values=search_db('la_name','Languages',''))
            language4 = ttk.Combobox(content, width = 15, textvariable=lang4, values=search_db('la_name','Languages',''))
            language5 = ttk.Combobox(content, width = 15, textvariable=lang5, values=search_db('la_name','Languages',''))
            language6 = ttk.Combobox(content, width = 15, textvariable=lang6, values=search_db('la_name','Languages',''))
            
            """ basic character information placement """
            content.grid(    column=0, row=0)
            name.grid(       column=1, row=2, columnspan=3)
            namelbl.grid(    column=1, row=3, sticky=(N, W))
            align.grid(      column=4, row=2, sticky=(W), columnspan=1)
            alignlbl.grid(   column=4, row=3, sticky=(N, W))
            player.grid(     column=5, row=2, sticky=(W), columnspan=4)
            playerlbl.grid(  column=5, row=3, sticky=(N,W))
            level.grid(      column=1, row=4, sticky=(W), columnspan=4)
            levellbl.grid(   column=1, row=5, sticky=(N,W), columnspan=3)
            deity.grid(      column=5, row=4, sticky=(W), columnspan=2)
            deitylbl.grid(   column=5, row=5, sticky=(N,W))
            homeland.grid(   column=7, row=4, sticky=(W), columnspan=2)
            homelandlbl.grid(column=7, row=5, sticky=(N,W))
            race.grid(       column=1, row=7, sticky=(W), columnspan=2)
            racelbl.grid(    column=1, row=8, sticky=(N,W))
            size.grid(       column=3, row=7, sticky=(W), columnspan=1)
            sizelbl.grid(    column=3, row=8, sticky=(N,W))
            gender.grid(     column=4, row=7, sticky=(W))
            genderlbl.grid(  column=4, row=8, sticky=(N,W))
            age.grid(        column=4, row=7, sticky=(E))
            agelbl.grid(     column=4, row=8, sticky=(N,E))
            height.grid(     column=5, row=7, sticky=(W), columnspan=1)
            heightlbl.grid(  column=5, row=8, sticky=(N,W))
            weight.grid(     column=6, row=7, sticky=(W), columnspan=1)
            weightlbl.grid(  column=6, row=8, sticky=(N,W))
            hair.grid(       column=7, row=7, sticky=(W), columnspan=1)
            hairlbl.grid(    column=7, row=8, sticky=(N,W))
            eyes.grid(       column=8, row=7, sticky=(W), columnspan=1)
            eyeslbl.grid(    column=8, row=8, sticky=(N,W))
            languagelbl.grid(column=1, row=9, sticky=(W), columnspan=2)
            language1.grid(  column=1, row=10, sticky=(W))
            language2.grid(  column=2, row=10, sticky=(W))
            language3.grid(  column=3, row=10, sticky=(W))
            language4.grid(  column=1, row=11, sticky=(W))
            language5.grid(  column=2, row=11, sticky=(W))
            language6.grid(  column=3, row=11, sticky=(W))            

            ibuttonlbl.grid( column=1, row=12 )
            ibuttonnew.grid( column=1, row=13, sticky=(W) )
            ibuttonsave.grid( column=2, row=13, sticky=(W) )
            ibuttonload.grid( column=3, row=13, sticky=(W) )
            ibuttonexit.grid( column=4, row=13, sticky=(W) )
            
            character.add(content, text='Information')
            
    def _create_abilities_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            abuttonlbl = ttk.Label(content, text = " ")
            abuttonnew = ttk.Button(content, text = "New", width = 10)
            abuttonsave = ttk.Button(content, text = "Save", width = 10)
            abuttonload = ttk.Button(content, text = "Load", width = 10)
            abuttonexit = ttk.Button(content, text = "Exit", width = 10)
            
            """ ability declaration """
            abnamelbl = ttk.Label(content, text="Ability Name", background='black', foreground='white')
            abscorelbl = ttk.Label(content, text = "Abl Score | Mod", background='black', foreground='white')
            tempadjlbl = ttk.Label(content, text = "Temp Adj | Mod", background='black', foreground='white')
            strlbl = ttk.Label(content, text = "   Strength    "  , background='black', foreground='white')
            strabs = ttk.Entry(content, width = 6)
            strabm = ttk.Entry(content, width = 6)
            strtma = ttk.Entry(content, width = 6)
            strtmm = ttk.Entry(content, width = 6) 
            dexlbl = ttk.Label(content, text = "   Dexterity    ", background='black', foreground='white')
            dexabs = ttk.Entry(content, width = 6)
            dexabm = ttk.Entry(content, width = 6)
            dextma = ttk.Entry(content, width = 6)
            dextmm = ttk.Entry(content, width = 6)
            conlbl = ttk.Label(content, text = "Constitution", background='black', foreground='white')
            conabs = ttk.Entry(content, width = 6)
            conabm = ttk.Entry(content, width = 6)
            contma = ttk.Entry(content, width = 6)
            contmm = ttk.Entry(content, width = 6)
            intlbl = ttk.Label(content, text = " Intelligence ", background='black', foreground='white')
            intabs = ttk.Entry(content, width = 6)
            intabm = ttk.Entry(content, width = 6)
            inttma = ttk.Entry(content, width = 6)
            inttmm = ttk.Entry(content, width = 6)
            wislbl = ttk.Label(content, text = "   Wisdom    ", background='black', foreground='white')
            wisabs = ttk.Entry(content, width = 6)
            wisabm = ttk.Entry(content, width = 6)
            wistma = ttk.Entry(content, width = 6)
            wistmm = ttk.Entry(content, width = 6)
            chalbl = ttk.Label(content, text = "   Charisma  ", background='black', foreground='white')
            chaabs = ttk.Entry(content, width = 6)
            chaabm = ttk.Entry(content, width = 6)
            chatma = ttk.Entry(content, width = 6)
            chatmm = ttk.Entry(content, width = 6)

            """ ability placement """
            abnamelbl.grid(  column=1, row=9, sticky = (W))
            abscorelbl.grid( column=2, row=9, sticky = (W))
            tempadjlbl.grid( column=3, row=9, sticky = (W))
            strlbl.grid(     column=1, row=10, columnspan = 2, sticky = (W))
            strabs.grid(     column=2, row=10, sticky = (W))
            strabm.grid(     column=2, row=10, sticky = (E), padx = 5)
            strtma.grid(     column=3, row=10, sticky = (W), padx = 3)
            strtmm.grid(     column=3, row=10, sticky = (E), padx = 8)
            dexlbl.grid(     column=1, row=11, columnspan = 2, sticky = (W))
            dexabs.grid(     column=2, row=11, sticky = (W))
            dexabm.grid(     column=2, row=11, sticky = (E), padx = 5)
            dextma.grid(     column=3, row=11, sticky = (W), padx = 3)
            dextmm.grid(     column=3, row=11, sticky = (E), padx = 8)
            conlbl.grid(     column=1, row=12, columnspan = 2, sticky = (W))
            conabs.grid(     column=2, row=12, sticky = (W))
            conabm.grid(     column=2, row=12, sticky = (E), padx = 5)
            contma.grid(     column=3, row=12, sticky = (W), padx = 3)
            contmm.grid(     column=3, row=12, sticky = (E), padx = 8)
            intlbl.grid(     column=1, row=13, columnspan = 2, sticky = (W))
            intabs.grid(     column=2, row=13, sticky = (W))
            intabm.grid(     column=2, row=13, sticky = (E), padx = 5)
            inttma.grid(     column=3, row=13, sticky = (W), padx = 3)
            inttmm.grid(     column=3, row=13, sticky = (E), padx = 8)
            wislbl.grid(     column=1, row=14, columnspan = 2, sticky = (W))
            wisabs.grid(     column=2, row=14, sticky = (W))
            wisabm.grid(     column=2, row=14, sticky = (E), padx = 5)
            wistma.grid(     column=3, row=14, sticky = (W), padx = 3)
            wistmm.grid(     column=3, row=14, sticky = (E), padx = 8)
            chalbl.grid(     column=1, row=15, columnspan = 2, sticky = (W))
            chaabs.grid(     column=2, row=15, sticky = (W))
            chaabm.grid(     column=2, row=15, sticky = (E), padx = 5)
            chatma.grid(     column=3, row=15, sticky = (W), padx = 3)
            chatmm.grid(     column=3, row=15, sticky = (E), padx = 8)

            """ Basic attribute declaration """
            hplbl = ttk.Label(content, text = "Total HP", background='black', foreground='white')
            hp = ttk.Entry(content, width = 10)
            drlbl = ttk.Label(content, text = "DR", foreground='grey')
            dmgres = ttk.Entry(content, width = 5)
            speedlbl = ttk.Label(content, text = "Speed", background='black', foreground='white')
            bspeed = ttk.Entry(content, width = 10)
            bpdlbl = ttk.Label(content, text = " Base", foreground='grey')
            aspeed = ttk.Entry(content, width = 10)
            asplbl = ttk.Label(content, text = " w/ Armor", foreground='grey')
            sspeed = ttk.Entry(content, width = 5)
            ssplbl = ttk.Label(content, text = "Swim", foreground='grey')
            fspeed = ttk.Entry(content, width = 4)
            fsplbl = ttk.Label(content, text = "Fly", foreground='grey')
            maneuv = ttk.Entry(content, width = 10)
            mnvlbl = ttk.Label(content, text = "Maneuver", foreground='grey')
            cspeed = ttk.Entry(content, width = 5)
            csplbl = ttk.Label(content, text = "Climb", foreground='grey')
            burspd = ttk.Entry(content, width = 4)
            brslbl = ttk.Label(content, text = "Burw", foreground='grey')
            tmdlbl = ttk.Label(content, text = "Temp Mod", foreground='grey')
            tmpmod1 = ttk.Entry(content, width = 9)
            tmpmod2 = ttk.Entry(content, width = 9)
            tmpmod3 = ttk.Entry(content, width = 9)
            wcrlbl = ttk.Label(content, text = "Wounds / HP", background='black', foreground='white')
            wcr1 = ttk.Entry(content, width = 31)
            wcr2 = ttk.Entry(content, width = 31)
            nldlbl = ttk.Label(content, text = "Non-Lethal Damage", background='black', foreground='white')
            nld = ttk.Entry(content, width = 31)
            inilbl = ttk.Label(content, text = "  Initiative  ", background='black', foreground='white')
            initot = ttk.Entry(content, width = 5)
            inidex = ttk.Entry(content, width = 4)
            inimsc = ttk.Entry(content, width = 4)
            inip = ttk.Label(content, text = "+")
            inie = ttk.Label(content, text = "=")
            inidexlbl = ttk.Label(content, text = "Dex", foreground='grey')
            inimsclbl = ttk.Label(content, text = "Misc", foreground='grey')
            initotlbl = ttk.Label(content, text = "Total", foreground='grey')
            inimodlbl = ttk.Label(content, text = "  Modifier  ", foreground='grey')

            """ Basic attribute placement"""
            hplbl.grid(      column=4, row=9, sticky = (E))
            hp.grid(         column=5, row=9, sticky = (W))
            drlbl.grid(      column=6, row=9, sticky = (W))
            dmgres.grid(     column=6, row=9, sticky = (E))
            speedlbl.grid(   column=7, row=9, sticky = (E), padx = 5)
            bspeed.grid(     column=8, row=9, sticky = (W))
            bpdlbl.grid(     column=8, row=10, sticky = (W))
            aspeed.grid(     column=9, row=9, sticky = (W))
            asplbl.grid(     column=9, row=10, sticky = (W))
            sspeed.grid(     column=7, row=11, sticky = (W))
            ssplbl.grid(     column=7, row=12, sticky = (W))
            fspeed.grid(     column=7, row=11, sticky = (E))
            fsplbl.grid(     column=7, row=12, sticky = (E))
            maneuv.grid(     column=8, row=11, sticky = (W))
            mnvlbl.grid(     column=8, row=12, sticky = (W))
            cspeed.grid(     column=9, row=11, sticky = (W))
            csplbl.grid(     column=9, row=12, sticky = (W))
            burspd.grid(     column=9, row=11, sticky = (E))
            brslbl.grid(     column=9, row=12, sticky = (E))
            tmdlbl.grid(     column=10, row=9, sticky = (E))
            tmpmod1.grid(    column=10, row=10, sticky = (W), padx = 3)
            tmpmod2.grid(    column=10, row=11, sticky = (W), padx = 3)
            tmpmod3.grid(    column=10, row=12, sticky = (W), padx = 3)
            wcrlbl.grid(     column=4, row=10, columnspan = 2, sticky = (W))
            wcr1.grid(       column=4, row=11, columnspan = 3, sticky = (NE))
            wcr2.grid(       column=4, row=12, columnspan = 3, sticky = (NE))
            nldlbl.grid(     column=4, row=13, columnspan = 2, sticky = (W))
            nld.grid(        column=4, row=14, columnspan = 3, sticky = (NE))
            inilbl.grid(     column=4, row=16, columnspan = 2, sticky = (W))
            initot.grid(     column=5, row=16, sticky = (E), padx = 12)
            inie.grid(       column=5, row=16, sticky = (E))
            inidex.grid(     column=6, row=16, sticky = (E))
            inip.grid(       column=6, row=16)
            inimsc.grid(     column=6, row=16, sticky = (W))
            inidexlbl.grid(  column=6, row=15, sticky = (E))
            inimsclbl.grid(  column=6, row=15, sticky = (W))
            initotlbl.grid(  column=5, row=15, sticky = (E), padx = 12)
            inimodlbl.grid(  column=4, row=15, sticky = (W))

            """ Fortitude, Reflex, Will Declaration """
            frwtotlbl = ttk.Label(content, text = "Total", foreground='grey')
            frwbaslbl = ttk.Label(content, text = "Base", foreground='grey')
            frwabllbl = ttk.Label(content, text = "Abil.", foreground='grey')
            frwmaglbl = ttk.Label(content, text = "Magic", foreground='grey')
            frwmsclbl = ttk.Label(content, text = "Misc", foreground='grey')
            frwtmplbl = ttk.Label(content, text = "Temp", foreground='grey')
            forlbl = ttk.Label(content, text = "Fortitude ", background='black', foreground='white')
            reflbl = ttk.Label(content, text = "  Reflex    ", background='black', foreground='white')
            willbl = ttk.Label(content, text = "     Will     ", background='black', foreground='white')
            fortot = ttk.Entry(content, width = 3)
            reftot = ttk.Entry(content, width = 3)
            wiltot = ttk.Entry(content, width = 3)
            forbas = ttk.Entry(content, width = 3)
            refbas = ttk.Entry(content, width = 3)
            wilbas = ttk.Entry(content, width = 3)
            forabl = ttk.Entry(content, width = 3)
            refabl = ttk.Entry(content, width = 3)
            wilabl = ttk.Entry(content, width = 3)
            formag = ttk.Entry(content, width = 3)
            refmag = ttk.Entry(content, width = 3)
            wilmag = ttk.Entry(content, width = 3)
            formsc = ttk.Entry(content, width = 3)
            refmsc = ttk.Entry(content, width = 3)
            wilmsc = ttk.Entry(content, width = 3)
            fortmp = ttk.Entry(content, width = 3)
            reftmp = ttk.Entry(content, width = 3)
            wiltmp = ttk.Entry(content, width = 3)
            frwe1 = ttk.Label(content, text = "=")
            frwe2 = ttk.Label(content, text = "=")
            frwe3 = ttk.Label(content, text = "=")
            frwp1 = ttk.Label(content, text = "+")
            frwp2 = ttk.Label(content, text = "+")
            frwp3 = ttk.Label(content, text = "+")
            frwp4 = ttk.Label(content, text = "+")
            frwp5 = ttk.Label(content, text = "+")
            frwp6 = ttk.Label(content, text = "+")
            frwp7 = ttk.Label(content, text = "+")
            frwp8 = ttk.Label(content, text = "+")
            frwp9 = ttk.Label(content, text = "+")
            frwp10 = ttk.Label(content, text = "+")
            frwp11 = ttk.Label(content, text = "+")
            frwp12 = ttk.Label(content, text = "+")
            frwp13 = ttk.Label(content, text = "+")
            frwp14 = ttk.Label(content, text = "+")
            frwp15 = ttk.Label(content, text = "+")
            frwp16 = ttk.Label(content, text = "+")

            """ Fortitude, Reflex, Will Placement """
            frwtotlbl.grid( column=8, row = 13, sticky = (W) )
            frwbaslbl.grid( column=8, row = 13, sticky = (E), padx = 5 )
            frwabllbl.grid( column=9, row = 13, sticky = (W) )
            frwmaglbl.grid( column=9, row = 13, sticky = (E) )
            frwmsclbl.grid( column=10, row = 13, sticky = (W) )
            frwtmplbl.grid( column=10, row = 13, sticky = (E) )
            forlbl.grid(    column=7, row = 14, sticky = (E) )
            reflbl.grid(    column=7, row = 15, sticky = (E) )
            willbl.grid(    column=7, row = 16, sticky = (E) )
            fortot.grid(    column=8, row = 14, sticky = (W) )
            reftot.grid(    column=8, row = 15, sticky = (W) )
            wiltot.grid(    column=8, row = 16, sticky = (W) )
            forbas.grid(    column=8, row = 14, sticky = (E), padx = 9 )
            refbas.grid(    column=8, row = 15, sticky = (E), padx = 9 )
            wilbas.grid(    column=8, row = 16, sticky = (E), padx = 9 )
            forabl.grid(    column=9, row = 14, sticky = (W) )
            refabl.grid(    column=9, row = 15, sticky = (W) )
            wilabl.grid(    column=9, row = 16, sticky = (W) )
            formag.grid(    column=9, row = 14, sticky = (E), padx = 9 )
            refmag.grid(    column=9, row = 15, sticky = (E), padx = 9 )
            wilmag.grid(    column=9, row = 16, sticky = (E), padx = 9 )
            formsc.grid(    column=10, row = 14, sticky = (W) )
            refmsc.grid(    column=10, row = 15, sticky = (W) )
            wilmsc.grid(    column=10, row = 16, sticky = (W) )
            fortmp.grid(    column=10, row = 14, sticky = (E), padx = 9 )
            reftmp.grid(    column=10, row = 15, sticky = (E), padx = 9 )
            wiltmp.grid(    column=10, row = 16, sticky = (E), padx = 9 )
            frwe1.grid(     column=8, row = 14, sticky = (W), padx = 22)
            frwe2.grid(     column=8, row = 15, sticky = (W), padx = 22)
            frwe3.grid(     column=8, row = 16, sticky = (W), padx = 22)
            frwp1.grid(     column=8, row = 14, sticky = (E) )
            frwp2.grid(     column=8, row = 15, sticky = (E) )
            frwp3.grid(     column=8, row = 16, sticky = (E) )
            frwp4.grid(     column=9, row = 14, sticky = (W), padx = 22 )
            frwp5.grid(     column=9, row = 15, sticky = (W), padx = 22 )
            frwp6.grid(     column=9, row = 16, sticky = (W), padx = 22 )
            frwp7.grid(     column=9, row = 14, sticky = (E) )
            frwp8.grid(     column=9, row = 15, sticky = (E) )
            frwp9.grid(     column=9, row = 16, sticky = (E) )
            frwp10.grid(    column=10, row = 14, sticky = (W), padx = 22 )
            frwp11.grid(    column=10, row = 15, sticky = (W), padx = 22 )
            frwp12.grid(    column=10, row = 16, sticky = (W), padx = 22 )

            """ armor class declarations """
            armclslbl= ttk.Label(content, text = "     AC    ", background='black', foreground='white')
            touchalbl= ttk.Label(content, text = " Touch  ", background='black', foreground='white')
            flatftlbl= ttk.Label(content, text = "Flat foot", background='black', foreground='white')
            atftotlbl= ttk.Label(content, text = "Total", foreground='grey')
            atfarmlbl= ttk.Label(content, text = "Armor", foreground='grey')
            arfshdlbl= ttk.Label(content, text = "Shield", foreground='grey')
            arfdexlbl= ttk.Label(content, text = "Dex Mod", foreground='grey')
            arfsizlbl= ttk.Label(content, text = "Size Mod", foreground='grey')
            arfnatlbl= ttk.Label(content, text = "Natural", foreground='grey')
            arfdfllbl= ttk.Label(content, text = "Deflect", foreground='grey')
            arfmsclbl= ttk.Label(content, text = "Misc Mod", foreground='grey')

            armortot= ttk.Entry(content, width = 8)
            touchtot= ttk.Entry(content, width = 8)
            fltfttot= ttk.Entry(content, width = 8)
            armarbon= ttk.Entry(content, width = 6)
            fltarbon= ttk.Entry(content, width = 6)
            armshbon= ttk.Entry(content, width = 6)
            fltshbon= ttk.Entry(content, width = 6)
            armordex= ttk.Entry(content, width = 6)
            touchdex= ttk.Entry(content, width = 6)
            armorsiz= ttk.Entry(content, width = 6)
            touchsiz= ttk.Entry(content, width = 6)
            fltftsiz= ttk.Entry(content, width = 6)
            armornat= ttk.Entry(content, width = 6)
            fltftnat= ttk.Entry(content, width = 6)
            armordfl= ttk.Entry(content, width = 6)
            touchdfl= ttk.Entry(content, width = 6)
            fltftdfl= ttk.Entry(content, width = 6)
            armormsc= ttk.Entry(content, width = 6)
            touchmsc= ttk.Entry(content, width = 6)
            fltftmsc= ttk.Entry(content, width = 6)

            atfep01= ttk.Label(content, text = "=  10 +")
            atfep02= ttk.Label(content, text = "=  10 +")
            atfep03= ttk.Label(content, text = "=  10 +")
            atfp01= ttk.Label(content, text = "+")
            atfp02= ttk.Label(content, text = "+")
            atfp03= ttk.Label(content, text = "+")
            atfp04= ttk.Label(content, text = "+")
            atfp05= ttk.Label(content, text = "+")
            atfp06= ttk.Label(content, text = "+")
            atfp07= ttk.Label(content, text = "+")
            atfp08= ttk.Label(content, text = "+")
            atfp09= ttk.Label(content, text = "+")
            atfp10= ttk.Label(content, text = "+")
            atfp11= ttk.Label(content, text = "+")
            atfp12= ttk.Label(content, text = "+")
            atfp13= ttk.Label(content, text = "+")
            atfp14= ttk.Label(content, text = "+")
            atfp15= ttk.Label(content, text = "+")
            atfp16= ttk.Label(content, text = "+")
            atfp17= ttk.Label(content, text = "+")

            """ armor class placement """
            armclslbl.grid( column = 2, row = 17, sticky = (E), padx=5)
            touchalbl.grid( column = 2, row = 18, sticky = (E), padx=5)
            flatftlbl.grid( column = 2, row = 19, sticky = (E), padx=5)
            atftotlbl.grid( column = 3, row = 20, sticky = (W), padx=5)
            atfarmlbl.grid( column = 4, row = 20)
            arfshdlbl.grid( column = 5, row = 20)
            arfdexlbl.grid( column = 6, row = 20)
            arfsizlbl.grid( column = 7, row = 20)
            arfnatlbl.grid( column = 8, row = 20)
            arfdfllbl.grid( column = 9, row = 20)
            arfmsclbl.grid( column = 10, row = 20)
            armortot.grid(  column = 3, row = 17, sticky = (W))
            touchtot.grid(  column = 3, row = 18, sticky = (W))
            fltfttot.grid(  column = 3, row = 19, sticky = (W))
            armarbon.grid(  column = 4, row = 17)
            fltarbon.grid(  column = 4, row = 19)
            armshbon.grid(  column = 5, row = 17)
            fltshbon.grid(  column = 5, row = 19)
            armordex.grid(  column = 6, row = 17)
            touchdex.grid(  column = 6, row = 18)
            armorsiz.grid(  column = 7, row = 17)
            touchsiz.grid(  column = 7, row = 18)
            fltftsiz.grid(  column = 7, row = 19)
            armornat.grid(  column = 8, row = 17)
            fltftnat.grid(  column = 8, row = 19)
            armordfl.grid(  column = 9, row = 17)
            touchdfl.grid(  column = 9, row = 18)
            fltftdfl.grid(  column = 9, row = 19)
            armormsc.grid(  column = 10, row = 17)
            touchmsc.grid(  column = 10, row = 18)
            fltftmsc.grid(  column = 10, row = 19)
            atfep01.grid(   column = 3, row = 17, sticky=(E))
            atfep02.grid(   column = 3, row = 18, sticky=(E))
            atfep03.grid(   column = 3, row = 19, sticky=(E))
            atfp01.grid(    column = 4, row = 17, sticky=(E))
            atfp02.grid(    column = 5, row = 17, sticky=(E))
            atfp03.grid(    column = 6, row = 17, sticky=(E))
            atfp04.grid(    column = 7, row = 17, sticky=(E))
            atfp05.grid(    column = 8, row = 17, sticky=(E))
            atfp06.grid(    column = 9, row = 17, sticky=(E))
            atfp07.grid(    column = 5, row = 18, sticky=(E))
            atfp08.grid(    column = 6, row = 18, sticky=(E))
            atfp09.grid(    column = 7, row = 18, sticky=(E))
            atfp10.grid(    column = 8, row = 18, sticky=(E))
            atfp11.grid(    column = 9, row = 18, sticky=(E))
            atfp12.grid(    column = 4, row = 19, sticky=(E))
            atfp13.grid(    column = 5, row = 19, sticky=(E))
            atfp14.grid(    column = 6, row = 19, sticky=(E))
            atfp15.grid(    column = 7, row = 19, sticky=(E))
            atfp16.grid(    column = 8, row = 19, sticky=(E))
            atfp17.grid(    column = 9, row = 19, sticky=(E))

            abuttonlbl.grid( column=1, row=20 )
            abuttonnew.grid( column=1, row=21, sticky=(W) )
            abuttonsave.grid( column=2, row=21, sticky=(W) )
            abuttonload.grid( column=3, row=21, sticky=(W) )
            abuttonexit.grid( column=4, row=21, sticky=(W) )
            
            character.add(content, text='Abilities')

    def _create_inventory_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            nbuttonlbl = ttk.Label(content, text = " ")
            nbuttonnew = ttk.Button(content, text = "New", width = 10)
            nbuttonsave = ttk.Button(content, text = "Save", width = 10)
            nbuttonload = ttk.Button(content, text = "Load", width = 10)
            nbuttonexit = ttk.Button(content, text = "Exit", width = 10)

            """ Gear Declaration """
            gearlbl = ttk.Label(content, text = "                                       Gear                                      ", background = 'black', foreground = 'white')
            itemlbl = ttk.Label(content, text = "Item", foreground = 'grey')
            wghtlbl = ttk.Label(content, text = "WT.", foreground = 'grey')

            item1nm = ttk.Entry(content, width=30)
            item1wt = ttk.Entry(content, width=10)
            item2nm = ttk.Entry(content, width=30)
            item2wt = ttk.Entry(content, width=10)
            item3nm = ttk.Entry(content, width=30)
            item3wt = ttk.Entry(content, width=10)
            item4nm = ttk.Entry(content, width=30)
            item4wt = ttk.Entry(content, width=10)
            item5nm = ttk.Entry(content, width=30)
            item5wt = ttk.Entry(content, width=10)
            item6nm = ttk.Entry(content, width=30)
            item6wt = ttk.Entry(content, width=10)
            item7nm = ttk.Entry(content, width=30)
            item7wt = ttk.Entry(content, width=10)
            item8nm = ttk.Entry(content, width=30)
            item8wt = ttk.Entry(content, width=10)
            item9nm = ttk.Entry(content, width=30)
            item9wt = ttk.Entry(content, width=10)
            item10nm = ttk.Entry(content, width=30)
            item10wt = ttk.Entry(content, width=10)
            item11nm = ttk.Entry(content, width=30)
            item11wt = ttk.Entry(content, width=10)
            item12nm = ttk.Entry(content, width=30)
            item12wt = ttk.Entry(content, width=10)
            item13nm = ttk.Entry(content, width=30)
            item13wt = ttk.Entry(content, width=10)
            item14nm = ttk.Entry(content, width=30)
            item14wt = ttk.Entry(content, width=10)
            item15nm = ttk.Entry(content, width=30)
            item15wt = ttk.Entry(content, width=10)
            item16nm = ttk.Entry(content, width=30)
            item16wt = ttk.Entry(content, width=10)
            item17nm = ttk.Entry(content, width=30)
            item17wt = ttk.Entry(content, width=10)
            item18nm = ttk.Entry(content, width=30)
            item18wt = ttk.Entry(content, width=10)
            item19nm = ttk.Entry(content, width=30)
            item19wt = ttk.Entry(content, width=10)
            item20nm = ttk.Entry(content, width=30)
            item20wt = ttk.Entry(content, width=10)

            wtotlbl = ttk.Label(content, text = "                                   Total Weight   ", background = 'black', foreground = 'white')
            wtotbox = ttk.Entry(content, width=10)

            """ Gear Placement """
            gearlbl.grid( column = 1, row = 2, columnspan = 4)
            itemlbl.grid( column = 1, row = 3, columnspan = 3)
            wghtlbl.grid( column = 4, row = 3, columnspan = 1)

            item1nm.grid( column = 1, row = 4, columnspan = 3)
            item1wt.grid( column = 4, row = 4, columnspan = 1)
            item2nm.grid( column = 1, row = 5, columnspan = 3)
            item2wt.grid( column = 4, row = 5, columnspan = 1)
            item3nm.grid( column = 1, row = 6, columnspan = 3)
            item3wt.grid( column = 4, row = 6, columnspan = 1)
            item4nm.grid( column = 1, row = 7, columnspan = 3)
            item4wt.grid( column = 4, row = 7, columnspan = 1)
            item5nm.grid( column = 1, row = 8, columnspan = 3)
            item5wt.grid( column = 4, row = 8, columnspan = 1)
            item6nm.grid( column = 1, row = 9, columnspan = 3)
            item6wt.grid( column = 4, row = 9, columnspan = 1)
            item7nm.grid( column = 1, row = 10, columnspan = 3)
            item7wt.grid( column = 4, row = 10, columnspan = 1)
            item8nm.grid( column = 1, row = 11, columnspan = 3)
            item8wt.grid( column = 4, row = 11, columnspan = 1)
            item9nm.grid( column = 1, row = 12, columnspan = 3)
            item9wt.grid( column = 4, row = 12, columnspan = 1)
            item10nm.grid( column = 1, row = 13, columnspan = 3)
            item10wt.grid( column = 4, row = 13, columnspan = 1)
            item11nm.grid( column = 1, row = 14, columnspan = 3)
            item11wt.grid( column = 4, row = 14, columnspan = 1)
            item12nm.grid( column = 1, row = 15, columnspan = 3)
            item12wt.grid( column = 4, row = 15, columnspan = 1)
            item13nm.grid( column = 1, row = 16, columnspan = 3)
            item13wt.grid( column = 4, row = 16, columnspan = 1)
            item14nm.grid( column = 1, row = 17, columnspan = 3)
            item14wt.grid( column = 4, row = 17, columnspan = 1)
            item15nm.grid( column = 1, row = 18, columnspan = 3)
            item15wt.grid( column = 4, row = 18, columnspan = 1)
            item16nm.grid( column = 1, row = 19, columnspan = 3)
            item16wt.grid( column = 4, row = 19, columnspan = 1)
            item17nm.grid( column = 1, row = 20, columnspan = 3)
            item17wt.grid( column = 4, row = 20, columnspan = 1)
            item18nm.grid( column = 1, row = 21, columnspan = 3)
            item18wt.grid( column = 4, row = 21, columnspan = 1)
            item19nm.grid( column = 1, row = 22, columnspan = 3)
            item19wt.grid( column = 4, row = 22, columnspan = 1)
            item20nm.grid( column = 1, row = 23, columnspan = 3)
            item20wt.grid( column = 4, row = 23, columnspan = 1)

            wtotlbl.grid(  column = 1, row = 24, columnspan = 3)
            wtotbox.grid(  column = 4, row = 24, columnspan = 1)

            """ Carry Declarations """
            hdlbl = ttk.Label(content, text = "                              Load Limits                               ", background = 'black', foreground = 'white')
            ltlbl = ttk.Label(content, text = "Light Load")
            mdlbl = ttk.Label(content, text = "Medium Load")
            hvlbl = ttk.Label(content, text = "Heavy Load")
            ohlbl = ttk.Label(content, text = "Over Head")
            oglbl = ttk.Label(content, text = "Off Ground")
            dplbl = ttk.Label(content, text = "Drag/Push")
            ltbox = ttk.Entry(content, width = 5)
            mdbox = ttk.Entry(content, width = 5)
            hvbox = ttk.Entry(content, width = 5)
            ohbox = ttk.Entry(content, width = 5)
            ogbox = ttk.Entry(content, width = 5)
            dpbox = ttk.Entry(content, width = 5)
            
            """ Carry Placement """
            hdlbl.grid( column = 5, row = 2, columnspan = 6)   
            ltlbl.grid( column = 5, row = 3, columnspan = 3, sticky = (W) )
            mdlbl.grid( column = 5, row = 4, columnspan = 3, sticky = (W) )
            hvlbl.grid( column = 5, row = 5, columnspan = 3, sticky = (W) )
            ohlbl.grid( column = 8, row = 3, columnspan = 3, sticky = (W) )
            oglbl.grid( column = 8, row = 4, columnspan = 3, sticky = (W) )
            dplbl.grid( column = 8, row = 5, columnspan = 3, sticky = (W) )
            ltbox.grid( column = 7, row = 3, sticky = (E))
            mdbox.grid( column = 7, row = 4, sticky = (E))
            hvbox.grid( column = 7, row = 5, sticky = (E))
            ohbox.grid( column = 10, row = 3, sticky = (E))
            ogbox.grid( column = 10, row = 4, sticky = (E))
            dpbox.grid( column = 10, row = 5, sticky = (E))
            
            """ Money Declarations """
            mnlbl = ttk.Label(content, text = "                                 Money                                    ", background='black', foreground='white')
            cplbl = ttk.Label(content, text = "Copper")
            splbl = ttk.Label(content, text = "Silver")
            gplbl = ttk.Label(content, text = "Gold")
            pplbl = ttk.Label(content, text = "Platinum")
            cpbox = ttk.Entry(content, width = 5)
            spbox = ttk.Entry(content, width = 5)
            gpbox = ttk.Entry(content, width = 5)
            ppbox = ttk.Entry(content, width = 5)
            
            """ Money Placement """
            mnlbl.grid(column = 5, row = 6, columnspan=6)
            cplbl.grid(column = 5, row = 7, columnspan=2, sticky = (W))
            splbl.grid(column = 8, row = 7, columnspan=2, sticky = (W))
            gplbl.grid(column = 5, row = 8, columnspan=2, sticky = (W))
            pplbl.grid(column = 8, row = 8, columnspan=2, sticky = (W))
            
            cpbox.grid(column = 7, row = 7, sticky = (E))
            spbox.grid(column = 10, row = 7, sticky = (E))
            gpbox.grid(column = 7, row = 8, sticky = (E))
            ppbox.grid(column = 10, row = 8, sticky = (E))
            
            """ Experience Declaration """
            explbl = ttk.Label(content, text = "              Experience Points                ", background='black', foreground='white')
            expbox = ttk.Entry(content, width = 30)
            nxtlbl = ttk.Label(content, text = " Next Level ", background='black', foreground='white')
            nxtbox = ttk.Entry(content, width = 10)
            
            """ Experience Placement """
            explbl.grid(column = 5, row = 9, columnspan = 4) 
            expbox.grid(column = 5, row = 10, columnspan = 4)
            nxtlbl.grid(column = 9, row = 9, columnspan = 2)
            nxtbox.grid(column = 9, row = 10, columnspan = 2)

            nbuttonlbl.grid( column=1, row=21 )
            nbuttonnew.grid( column=1, row=26, sticky=(W) )
            nbuttonsave.grid( column=2, row=26, sticky=(W) )
            nbuttonload.grid( column=3, row=26, sticky=(W) )
            nbuttonexit.grid( column=4, row=26, sticky=(W) )
            
            character.add(content, text='Inventory')
            
    def _create_weapons_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            wbuttonlbl = ttk.Label(content, text = " ")
            wbuttonnew = ttk.Button(content, text = "New", width = 10)
            wbuttonsave = ttk.Button(content, text = "Save", width = 10)
            wbuttonload = ttk.Button(content, text = "Load", width = 10)
            wbuttonexit = ttk.Button(content, text = "Exit", width = 10)
            
            """ attack stats declaration """
            bablbl = ttk.Label(content, text = "      Base Attack Bonus     ", background = 'black', foreground = 'white')
            reslbl = ttk.Label(content, text = "        Spell Resistance       ", background = 'black', foreground = 'white')
            cmblbl = ttk.Label(content, text = "    CMB    ", background = 'black', foreground = 'white')
            cmdlbl = ttk.Label(content, text = "    CMD    ", background = 'black', foreground = 'white')
            atkbon = ttk.Entry(content, width = 8)
            splres = ttk.Entry(content, width = 8)
            cmbtot = ttk.Entry(content, width = 4)
            cmbbab = ttk.Entry(content, width = 4)
            cmbstr = ttk.Entry(content, width = 4)
            cmbsiz = ttk.Entry(content, width = 4)
            cmdtot = ttk.Entry(content, width = 4)
            cmdcmb = ttk.Entry(content, width = 4)
            cmddex = ttk.Entry(content, width = 4)
            cmdl10 = ttk.Label(content, text = "10")
            cmdp01 = ttk.Label(content, text = "+")
            cmdp02 = ttk.Label(content, text = "+")
            cmde01 = ttk.Label(content, text = "=")
            cmbp01 = ttk.Label(content, text = "+")
            cmbp02 = ttk.Label(content, text = "+")
            cmbe01 = ttk.Label(content, text = "=")
            cmbtotlbl = ttk.Label(content, text = "Total", foreground = 'grey')
            cmbbablbl = ttk.Label(content, text = "B.A.B.", foreground = 'grey')
            cmbstrlbl = ttk.Label(content, text = "Str Mod", foreground = 'grey')
            cmbsizlbl = ttk.Label(content, text = "Size Mod", foreground = 'grey')
            cmdtotlbl = ttk.Label(content, text = "Total", foreground = 'grey')
            cmdcmblbl = ttk.Label(content, text = "CMB", foreground = 'grey')
            cmddexlbl = ttk.Label(content, text = "Dex Mod", foreground = 'grey')

            """ attack stats placement """
            bablbl.grid(column=1, row=2, columnspan=2, sticky=(W))
            reslbl.grid(column=4, row=2, columnspan=2, sticky=(W))
            cmblbl.grid(column=1, row=4)
            cmdlbl.grid(column=1, row=5)
            atkbon.grid(column=3, row=2, sticky=(W))
            splres.grid(column=6, row=2, sticky=(W))
            cmbtot.grid(column=3, row=4, sticky=(W))
            cmbbab.grid(column=4, row=4, sticky=(W))
            cmbstr.grid(column=5, row=4)
            cmbsiz.grid(column=6, row=4, sticky=(W))
            cmdtot.grid(column=3, row=5, sticky=(W))
            cmdcmb.grid(column=4, row=5, sticky=(W))
            cmddex.grid(column=5, row=5)
            cmdl10.grid(column=6, row=5, sticky=(W))
            cmdp01.grid(column=5, row=4, sticky=(W))
            cmdp02.grid(column=5, row=4, sticky=(E))
            cmde01.grid(column=3, row=4, sticky=(E))
            cmbp01.grid(column=5, row=5, sticky=(W))
            cmbp02.grid(column=5, row=5, sticky=(E))
            cmbe01.grid(column=3, row=5, sticky=(E))
            cmbtotlbl.grid(column=3, row=3, sticky=(W))
            cmbbablbl.grid(column=4, row=3, sticky=(W))
            cmbstrlbl.grid(column=5, row=3, sticky=(W))
            cmbsizlbl.grid(column=6, row=3, sticky=(W))
            cmdcmblbl.grid(column=4, row=6, sticky=(W))
            cmdtotlbl.grid(column=3, row=6, sticky=(W))
            cmddexlbl.grid(column=5, row=6, sticky=(W))

            """ weapons declaration """
            weapon1lbllbl = ttk.Label(content, text = "Weapon 1", background = 'black', foreground = 'white')
            weapon1atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon1crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon1typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon1rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon1ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon1damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon1lblbox = ttk.Entry(content, width=42)
            weapon1atkbox = ttk.Entry(content, width=12)
            weapon1crtbox = ttk.Entry(content, width=10)
            weapon1typbox = ttk.Entry(content, width=10)
            weapon1rngbox = ttk.Entry(content, width=10)
            weapon1ammbox = ttk.Entry(content, width=20)
            weapon1dambox = ttk.Entry(content, width=23)

            weapon2lbllbl = ttk.Label(content, text = "Weapon 2", background = 'black', foreground = 'white')
            weapon2atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon2crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon2typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon2rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon2ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon2damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon2lblbox = ttk.Entry(content, width=42)
            weapon2atkbox = ttk.Entry(content, width=12)
            weapon2crtbox = ttk.Entry(content, width=10)
            weapon2typbox = ttk.Entry(content, width=10)
            weapon2rngbox = ttk.Entry(content, width=10)
            weapon2ammbox = ttk.Entry(content, width=20)
            weapon2dambox = ttk.Entry(content, width=23)

            weapon3lbllbl = ttk.Label(content, text = "Weapon 3", background = 'black', foreground = 'white')
            weapon3atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon3crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon3typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon3rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon3ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon3damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon3lblbox = ttk.Entry(content, width=42)
            weapon3atkbox = ttk.Entry(content, width=12)
            weapon3crtbox = ttk.Entry(content, width=10)
            weapon3typbox = ttk.Entry(content, width=10)
            weapon3rngbox = ttk.Entry(content, width=10)
            weapon3ammbox = ttk.Entry(content, width=20)
            weapon3dambox = ttk.Entry(content, width=23)

            weapon4lbllbl = ttk.Label(content, text = "Weapon 4" , background = 'black', foreground = 'white')
            weapon4atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon4crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon4typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon4rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon4ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon4damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon4lblbox = ttk.Entry(content, width=42)
            weapon4atkbox = ttk.Entry(content, width=12)
            weapon4crtbox = ttk.Entry(content, width=10)
            weapon4typbox = ttk.Entry(content, width=10)
            weapon4rngbox = ttk.Entry(content, width=10)
            weapon4ammbox = ttk.Entry(content, width=20)
            weapon4dambox = ttk.Entry(content, width=23)

            weapon5lbllbl = ttk.Label(content, text = "Weapon 5", background = 'black', foreground = 'white')
            weapon5atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
            weapon5crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
            weapon5typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
            weapon5rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
            weapon5ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
            weapon5damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
            weapon5lblbox = ttk.Entry(content, width=42)
            weapon5atkbox = ttk.Entry(content, width=12)
            weapon5crtbox = ttk.Entry(content, width=10)
            weapon5typbox = ttk.Entry(content, width=10)
            weapon5rngbox = ttk.Entry(content, width=10)
            weapon5ammbox = ttk.Entry(content, width=20)
            weapon5dambox = ttk.Entry(content, width=23)

            """ weapons placement """

            weapon1lbllbl.grid(column = 1, row = 7, columnspan = 4, sticky = (W))
            weapon1atklbl.grid(column = 5, row = 7, columnspan = 1, sticky = (W))
            weapon1crtlbl.grid(column = 6, row = 7, columnspan = 1, sticky = (W))
            weapon1typlbl.grid(column = 1, row = 9, columnspan = 1, sticky = (W))
            weapon1rnglbl.grid(column = 2, row = 9, columnspan = 1, sticky = (W))
            weapon1ammlbl.grid(column = 3, row = 9, columnspan = 2, sticky = (W))
            weapon1damlbl.grid(column = 5, row = 9, columnspan = 2, sticky = (W))
            weapon1lblbox.grid(column = 1, row = 8, columnspan = 4, sticky = (W))
            weapon1atkbox.grid(column = 5, row = 8, columnspan = 1, sticky = (W))
            weapon1crtbox.grid(column = 6, row = 8, columnspan = 1, sticky = (W))
            weapon1typbox.grid(column = 1, row = 10, columnspan = 1, sticky = (W))
            weapon1rngbox.grid(column = 2, row = 10, columnspan = 1, sticky = (W))
            weapon1ammbox.grid(column = 3, row = 10, columnspan = 2, sticky = (W))
            weapon1dambox.grid(column = 5, row = 10, columnspan = 2, sticky = (W))

            weapon2lbllbl.grid(column = 1, row = 11, columnspan = 4, sticky = (W))
            weapon2atklbl.grid(column = 5, row = 11, columnspan = 1, sticky = (W))
            weapon2crtlbl.grid(column = 6, row = 11, columnspan = 1, sticky = (W))
            weapon2typlbl.grid(column = 1, row = 13, columnspan = 1, sticky = (W))
            weapon2rnglbl.grid(column = 2, row = 13, columnspan = 1, sticky = (W))
            weapon2ammlbl.grid(column = 3, row = 13, columnspan = 2, sticky = (W))
            weapon2damlbl.grid(column = 5, row = 13, columnspan = 2, sticky = (W))
            weapon2lblbox.grid(column = 1, row = 12, columnspan = 4, sticky = (W))
            weapon2atkbox.grid(column = 5, row = 12, columnspan = 1, sticky = (W))
            weapon2crtbox.grid(column = 6, row = 12, columnspan = 1, sticky = (W))
            weapon2typbox.grid(column = 1, row = 14, columnspan = 1, sticky = (W))
            weapon2rngbox.grid(column = 2, row = 14, columnspan = 1, sticky = (W))
            weapon2ammbox.grid(column = 3, row = 14, columnspan = 2, sticky = (W))
            weapon2dambox.grid(column = 5, row = 14, columnspan = 2, sticky = (W))

            weapon3lbllbl.grid(column = 1, row = 15, columnspan = 4, sticky = (W))
            weapon3atklbl.grid(column = 5, row = 15, columnspan = 1, sticky = (W))
            weapon3crtlbl.grid(column = 6, row = 15, columnspan = 1, sticky = (W))
            weapon3typlbl.grid(column = 1, row = 17, columnspan = 1, sticky = (W))
            weapon3rnglbl.grid(column = 2, row = 17, columnspan = 1, sticky = (W))
            weapon3ammlbl.grid(column = 3, row = 17, columnspan = 2, sticky = (W))
            weapon3damlbl.grid(column = 5, row = 17, columnspan = 2, sticky = (W))
            weapon3lblbox.grid(column = 1, row = 16, columnspan = 4, sticky = (W))
            weapon3atkbox.grid(column = 5, row = 16, columnspan = 1, sticky = (W))
            weapon3crtbox.grid(column = 6, row = 16, columnspan = 1, sticky = (W))
            weapon3typbox.grid(column = 1, row = 18, columnspan = 1, sticky = (W))
            weapon3rngbox.grid(column = 2, row = 18, columnspan = 1, sticky = (W))
            weapon3ammbox.grid(column = 3, row = 18, columnspan = 2, sticky = (W))
            weapon3dambox.grid(column = 5, row = 18, columnspan = 2, sticky = (W))

            weapon4lbllbl.grid(column = 1, row = 19, columnspan = 4, sticky = (W))
            weapon4atklbl.grid(column = 5, row = 19, columnspan = 1, sticky = (W))
            weapon4crtlbl.grid(column = 6, row = 19, columnspan = 1, sticky = (W))
            weapon4typlbl.grid(column = 1, row = 21, columnspan = 1, sticky = (W))
            weapon4rnglbl.grid(column = 2, row = 21, columnspan = 1, sticky = (W))
            weapon4ammlbl.grid(column = 3, row = 21, columnspan = 2, sticky = (W))
            weapon4damlbl.grid(column = 5, row = 21, columnspan = 2, sticky = (W))
            weapon4lblbox.grid(column = 1, row = 20, columnspan = 4, sticky = (W))
            weapon4atkbox.grid(column = 5, row = 20, columnspan = 1, sticky = (W))
            weapon4crtbox.grid(column = 6, row = 20, columnspan = 1, sticky = (W))
            weapon4typbox.grid(column = 1, row = 22, columnspan = 1, sticky = (W))
            weapon4rngbox.grid(column = 2, row = 22, columnspan = 1, sticky = (W))
            weapon4ammbox.grid(column = 3, row = 22, columnspan = 2, sticky = (W))
            weapon4dambox.grid(column = 5, row = 22, columnspan = 2, sticky = (W))

            weapon5lbllbl.grid(column = 1, row = 23, columnspan = 4, sticky = (W))
            weapon5atklbl.grid(column = 5, row = 23, columnspan = 1, sticky = (W))
            weapon5crtlbl.grid(column = 6, row = 23, columnspan = 1, sticky = (W))
            weapon5typlbl.grid(column = 1, row = 25, columnspan = 1, sticky = (W))
            weapon5rnglbl.grid(column = 2, row = 25, columnspan = 1, sticky = (W))
            weapon5ammlbl.grid(column = 3, row = 25, columnspan = 2, sticky = (W))
            weapon5damlbl.grid(column = 5, row = 25, columnspan = 2, sticky = (W))
            weapon5lblbox.grid(column = 1, row = 24, columnspan = 4, sticky = (W))
            weapon5atkbox.grid(column = 5, row = 24, columnspan = 1, sticky = (W))
            weapon5crtbox.grid(column = 6, row = 24, columnspan = 1, sticky = (W))
            weapon5typbox.grid(column = 1, row = 26, columnspan = 1, sticky = (W))
            weapon5rngbox.grid(column = 2, row = 26, columnspan = 1, sticky = (W))
            weapon5ammbox.grid(column = 3, row = 26, columnspan = 2, sticky = (W))
            weapon5dambox.grid(column = 5, row = 26, columnspan = 2, sticky = (W))

            wbuttonlbl.grid( column=1, row=27 )
            wbuttonnew.grid( column=1, row=28, sticky=(W) )
            wbuttonsave.grid( column=2, row=28, sticky=(W) )
            wbuttonload.grid( column=3, row=28, sticky=(W) )
            wbuttonexit.grid( column=4, row=28, sticky=(W) )
            
            character.add(content, text='Weapons')

    def _create_armor_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            rbuttonlbl = ttk.Label(content, text = " ")
            rbuttonnew = ttk.Button(content, text = "New", width = 10)
            rbuttonsave = ttk.Button(content, text = "Save", width = 10)
            rbuttonload = ttk.Button(content, text = "Load", width = 10)
            rbuttonexit = ttk.Button(content, text = "Exit", width = 10)
            
            """ Armor Declarations """
            acglbllbl = ttk.Label(content, text="Armor Class Gear           ", background='black', foreground='white')
            acgbonlbl = ttk.Label(content, text="Bonus          ", background='black', foreground='white')
            acgtyplbl = ttk.Label(content, text="Type            ", background='black', foreground='white')
            acgchklbl = ttk.Label(content, text="Check Penalty", background='black', foreground='white')
            acgspflbl = ttk.Label(content, text="Spell Failure", background='black', foreground='white')
            acgwgtlbl = ttk.Label(content, text="Weight        ", background='black', foreground='white')
            acgprplbl = ttk.Label(content, text="Properties   ", background='black', foreground='white')
            armor1acg = ttk.Entry(content, width=20)
            armor1bon = ttk.Entry(content, width=10)
            armor1typ = ttk.Entry(content, width=10)
            armor1chk = ttk.Entry(content, width=12)
            armor1spf = ttk.Entry(content, width=10)
            armor1wgt = ttk.Entry(content, width=10)
            armor1prp = ttk.Entry(content, width=10)
            armor2acg = ttk.Entry(content, width=20)
            armor2bon = ttk.Entry(content, width=10)
            armor2typ = ttk.Entry(content, width=10)
            armor2chk = ttk.Entry(content, width=12)
            armor2spf = ttk.Entry(content, width=10)
            armor2wgt = ttk.Entry(content, width=10)
            armor2prp = ttk.Entry(content, width=10)
            armor3acg = ttk.Entry(content, width=20)
            armor3bon = ttk.Entry(content, width=10)
            armor3typ = ttk.Entry(content, width=10)
            armor3chk = ttk.Entry(content, width=12)
            armor3spf = ttk.Entry(content, width=10)
            armor3wgt = ttk.Entry(content, width=10)
            armor3prp = ttk.Entry(content, width=10)
            armor4acg = ttk.Entry(content, width=20)
            armor4bon = ttk.Entry(content, width=10)
            armor4typ = ttk.Entry(content, width=10)
            armor4chk = ttk.Entry(content, width=12)
            armor4spf = ttk.Entry(content, width=10)
            armor4wgt = ttk.Entry(content, width=10)
            armor4prp = ttk.Entry(content, width=10)
            armor5acg = ttk.Entry(content, width=20)
            armor5bon = ttk.Entry(content, width=10)
            armor5typ = ttk.Entry(content, width=10)
            armor5chk = ttk.Entry(content, width=12)
            armor5spf = ttk.Entry(content, width=10)
            armor5wgt = ttk.Entry(content, width=10)
            armor5prp = ttk.Entry(content, width=10)
            acgtotlbl = ttk.Label(content, text="Totals                              ", background='black', foreground='white')
            acgbontot = ttk.Entry(content, width=10)
            acgtyptot = ttk.Entry(content, width=10)
            acgchktot = ttk.Entry(content, width=12)
            acgspftot = ttk.Entry(content, width=10)
            acgwgttot = ttk.Entry(content, width=10)
            acgprptot = ttk.Entry(content, width=10)

            """ Armor Placement """
            acglbllbl.grid(column = 1, row = 2, columnspan = 2, sticky = (W))
            acgbonlbl.grid(column = 3, row = 2, columnspan = 1, sticky = (W))
            acgtyplbl.grid(column = 4, row = 2, columnspan = 1, sticky = (W))
            acgchklbl.grid(column = 5, row = 2, columnspan = 1, sticky = (W))
            acgspflbl.grid(column = 6, row = 2, columnspan = 1, sticky = (W))
            acgwgtlbl.grid(column = 7, row = 2, columnspan = 1, sticky = (W))
            acgprplbl.grid(column = 8, row = 2, columnspan = 1, sticky = (W))
            armor1acg.grid(column = 1, row = 3, columnspan = 2, sticky = (W))
            armor1bon.grid(column = 3, row = 3, columnspan = 1, sticky = (W))
            armor1typ.grid(column = 4, row = 3, columnspan = 1, sticky = (W))
            armor1chk.grid(column = 5, row = 3, columnspan = 1, sticky = (W))
            armor1spf.grid(column = 6, row = 3, columnspan = 1, sticky = (W))
            armor1wgt.grid(column = 7, row = 3, columnspan = 1, sticky = (W))
            armor1prp.grid(column = 8, row = 3, columnspan = 1, sticky = (W))
            armor2acg.grid(column = 1, row = 4, columnspan = 2, sticky = (W))
            armor2bon.grid(column = 3, row = 4, columnspan = 1, sticky = (W))
            armor2typ.grid(column = 4, row = 4, columnspan = 1, sticky = (W))
            armor2chk.grid(column = 5, row = 4, columnspan = 1, sticky = (W))
            armor2spf.grid(column = 6, row = 4, columnspan = 1, sticky = (W))
            armor2wgt.grid(column = 7, row = 4, columnspan = 1, sticky = (W))
            armor2prp.grid(column = 8, row = 4, columnspan = 1, sticky = (W))
            armor3acg.grid(column = 1, row = 5, columnspan = 2, sticky = (W))
            armor3bon.grid(column = 3, row = 5, columnspan = 1, sticky = (W))
            armor3typ.grid(column = 4, row = 5, columnspan = 1, sticky = (W))
            armor3chk.grid(column = 5, row = 5, columnspan = 1, sticky = (W))
            armor3spf.grid(column = 6, row = 5, columnspan = 1, sticky = (W))
            armor3wgt.grid(column = 7, row = 5, columnspan = 1, sticky = (W))
            armor3prp.grid(column = 8, row = 5, columnspan = 1, sticky = (W))
            armor4acg.grid(column = 1, row = 6, columnspan = 2, sticky = (W))
            armor4bon.grid(column = 3, row = 6, columnspan = 1, sticky = (W))
            armor4typ.grid(column = 4, row = 6, columnspan = 1, sticky = (W))
            armor4chk.grid(column = 5, row = 6, columnspan = 1, sticky = (W))
            armor4spf.grid(column = 6, row = 6, columnspan = 1, sticky = (W))
            armor4wgt.grid(column = 7, row = 6, columnspan = 1, sticky = (W))
            armor4prp.grid(column = 8, row = 6, columnspan = 1, sticky = (W))
            armor5acg.grid(column = 1, row = 7, columnspan = 2, sticky = (W))
            armor5bon.grid(column = 3, row = 7, columnspan = 1, sticky = (W))
            armor5typ.grid(column = 4, row = 7, columnspan = 1, sticky = (W))
            armor5chk.grid(column = 5, row = 7, columnspan = 1, sticky = (W))
            armor5spf.grid(column = 6, row = 7, columnspan = 1, sticky = (W))
            armor5wgt.grid(column = 7, row = 7, columnspan = 1, sticky = (W))
            armor5prp.grid(column = 8, row = 7, columnspan = 1, sticky = (W))
            acgtotlbl.grid(column = 1, row = 8, columnspan = 2, sticky = (W))
            acgbontot.grid(column = 3, row = 8, columnspan = 1, sticky = (W))
            acgtyptot.grid(column = 4, row = 8, columnspan = 1, sticky = (W))
            acgchktot.grid(column = 5, row = 8, columnspan = 1, sticky = (W))
            acgspftot.grid(column = 6, row = 8, columnspan = 1, sticky = (W))
            acgwgttot.grid(column = 7, row = 8, columnspan = 1, sticky = (W))
            acgprptot.grid(column = 8, row = 8, columnspan = 1, sticky = (W))

            rbuttonlbl.grid( column=1, row=9 )
            rbuttonnew.grid( column=1, row=10, sticky=(W) )
            rbuttonsave.grid( column=2, row=10, sticky=(W) )
            rbuttonload.grid( column=3, row=10, sticky=(W) )
            rbuttonexit.grid( column=4, row=10, sticky=(W) )
            
            character.add(content, text='Armor')
            
    def _create_skills_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            sbuttonlbl = ttk.Label(content, text = " ")
            sbuttonnew = ttk.Button(content, text = "New", width = 10)
            sbuttonsave = ttk.Button(content, text = "Save", width = 10)
            sbuttonload = ttk.Button(content, text = "Load", width = 10)
            sbuttonexit = ttk.Button(content, text = "Exit", width = 10)
            
            """ skills declarations """
            nameslbl = ttk.Label(content, text = "Skill Names")
            totallbl = ttk.Label(content, text = "Total Bonus")
            abltylbl = ttk.Label(content, text = "Ability Mod")
            rankslbl = ttk.Label(content, text = "Ranks Mod")
            miscmlbl = ttk.Label(content, text = "Misc Mod")

            ## Start of loop
            # 2d array [skill][tkinter function in order on row.
            SkillArray = {' ': []} # Empty starter
            j = 2
            for i in sorted(Character.STDSkills.keys()):
                j += 1
                SkillArray[i] = [ttk.Checkbutton(content, text = i)]
                SkillArray[i].append(ttk.Entry(content, width = 10))
                SkillArray[i][1].insert(END,"%d"%Test.SkillCheck(i))
                SkillArray[i][1].state(['readonly'])
                SkillArray[i].append(ttk.Label(content, text = " = %s "%Character.STDBase[i]))
                SkillArray[i].append(ttk.Entry(content, width = 10, state = 'normal'))
                SkillArray[i][3].insert(END,"%d"%Test.AbilityCheck(Character.STDBase[i]))
                SkillArray[i][3].state(['readonly'])
                SkillArray[i].append(ttk.Label(content, text = "+"))
                SkillArray[i].append(ttk.Entry(content, width = 10))
                SkillArray[i].append(ttk.Label(content, text = "+"))
                SkillArray[i].append(ttk.Entry(content, width = 10))

                # If armor Penalty do stuff.
            
                SkillArray[i][0].grid(column = 1, row = j, columnspan=4, sticky = (W))
                SkillArray[i][1].grid(column = 5, row = j)
                SkillArray[i][2].grid(column = 6, row = j)
                SkillArray[i][3].grid(column = 7, row = j)
                SkillArray[i][4].grid(column = 8, row = j)
                SkillArray[i][5].grid(column = 9, row = j)
                SkillArray[i][6].grid(column = 10, row = j)
                SkillArray[i][7].grid(column = 11, row = j)

            ## End of loop

            sbuttonlbl.grid( column=1, row=43 )
            sbuttonnew.grid( column=1, row=44, sticky=(W) )
            sbuttonsave.grid( column=2, row=44, sticky=(W) )
            sbuttonload.grid( column=3, row=44, sticky=(W) )
            sbuttonexit.grid( column=4, row=44, sticky=(W) )
            
            character.add(content, text='Skills')

    def _create_spells_tab(self, character):
            content = ttk.Frame(character, padding=(3,3,12,12))
            content.grid(column=0, row=0)

            pbuttonlbl = ttk.Label(content, text = " ")
            pbuttonnew = ttk.Button(content, text = "New", width = 10)
            pbuttonsave = ttk.Button(content, text = "Save", width = 10)
            pbuttonload = ttk.Button(content, text = "Load", width = 10)
            pbuttonexit = ttk.Button(content, text = "Exit", width = 10)
            
            """ spell declarations """
            spklbl = ttk.Label(content, text = "Known")
            ssdlbl = ttk.Label(content, text = "Save DC")
            spllbl = ttk.Label(content, text = "Level")
            spdlbl = ttk.Label(content, text = "Per Day")
            bonlbl = ttk.Label(content, text = "Bonus")
            
            spknil = ttk.Entry(content, width = 10)
            ssdnil = ttk.Entry(content, width = 10)
            lvlnil = ttk.Label(content, text = "0")
            spdnil = ttk.Entry(content, width = 10)
            bonnil = ttk.Label(content, text = "---")

            spk1st = ttk.Entry(content, width = 10)
            ssd1st = ttk.Entry(content, width = 10)
            lvl1st = ttk.Label(content, text = "1st")
            spd1st = ttk.Entry(content, width = 10)
            bon1st = ttk.Entry(content, width = 10)

            spk2nd = ttk.Entry(content, width = 10)
            ssd2nd = ttk.Entry(content, width = 10)
            lvl2nd = ttk.Label(content, text = "2nd")
            spd2nd = ttk.Entry(content, width = 10)
            bon2nd = ttk.Entry(content, width = 10)

            spk3rd = ttk.Entry(content, width = 10)
            ssd3rd = ttk.Entry(content, width = 10)
            lvl3rd = ttk.Label(content, text = "3rd")
            spd3rd = ttk.Entry(content, width = 10)
            bon3rd = ttk.Entry(content, width = 10)

            spk4th = ttk.Entry(content, width = 10)
            ssd4th = ttk.Entry(content, width = 10)
            lvl4th = ttk.Label(content, text = "4th")
            spd4th = ttk.Entry(content, width = 10)
            bon4th = ttk.Entry(content, width = 10)

            spk5th = ttk.Entry(content, width = 10)
            ssd5th = ttk.Entry(content, width = 10)
            lvl5th = ttk.Label(content, text = "5th")
            spd5th = ttk.Entry(content, width = 10)
            bon5th = ttk.Entry(content, width = 10)

            spk6th = ttk.Entry(content, width = 10)
            ssd6th = ttk.Entry(content, width = 10)
            lvl6th = ttk.Label(content, text = "6th")
            spd6th = ttk.Entry(content, width = 10)
            bon6th = ttk.Entry(content, width = 10)

            spk7th = ttk.Entry(content, width = 10)
            ssd7th = ttk.Entry(content, width = 10)
            lvl7th = ttk.Label(content, text = "7th")
            spd7th = ttk.Entry(content, width = 10)
            bon7th = ttk.Entry(content, width = 10)

            spk8th = ttk.Entry(content, width = 10)
            ssd8th = ttk.Entry(content, width = 10)
            lvl8th = ttk.Label(content, text = "8th")
            spd8th = ttk.Entry(content, width = 10)
            bon8th = ttk.Entry(content, width = 10)

            spk9th = ttk.Entry(content, width = 10)
            ssd9th = ttk.Entry(content, width = 10)
            lvl9th = ttk.Label(content, text = "9th")
            spd9th = ttk.Entry(content, width = 10)
            bon9th = ttk.Entry(content, width = 10)

            """ spell placement """
            spklbl.grid(column = 1, row = 2)
            ssdlbl.grid(column = 2, row = 2)
            spllbl.grid(column = 3, row = 2)
            spdlbl.grid(column = 4, row = 2)
            bonlbl.grid(column = 5, row = 2)
            
            spknil.grid(column = 1, row = 3)
            ssdnil.grid(column = 2, row = 3)
            lvlnil.grid(column = 3, row = 3)
            spdnil.grid(column = 4, row = 3)
            bonnil.grid(column = 5, row = 3)

            spk1st.grid(column = 1, row = 4)
            ssd1st.grid(column = 2, row = 4)
            lvl1st.grid(column = 3, row = 4)
            spd1st.grid(column = 4, row = 4)
            bon1st.grid(column = 5, row = 4)

            spk2nd.grid(column = 1, row = 5)
            ssd2nd.grid(column = 2, row = 5)
            lvl2nd.grid(column = 3, row = 5)
            spd2nd.grid(column = 4, row = 5)
            bon2nd.grid(column = 5, row = 5)

            spk3rd.grid(column = 1, row = 6)
            ssd3rd.grid(column = 2, row = 6)
            lvl3rd.grid(column = 3, row = 6)
            spd3rd.grid(column = 4, row = 6)
            bon3rd.grid(column = 5, row = 6)

            spk4th.grid(column = 1, row = 7)
            ssd4th.grid(column = 2, row = 7)
            lvl4th.grid(column = 3, row = 7)
            spd4th.grid(column = 4, row = 7)
            bon4th.grid(column = 5, row = 7)

            spk5th.grid(column = 1, row = 8)
            ssd5th.grid(column = 2, row = 8)
            lvl5th.grid(column = 3, row = 8)
            spd5th.grid(column = 4, row = 8)
            bon5th.grid(column = 5, row = 8)

            spk6th.grid(column = 1, row = 9)
            ssd6th.grid(column = 2, row = 9)
            lvl6th.grid(column = 3, row = 9)
            spd6th.grid(column = 4, row = 9)
            bon6th.grid(column = 5, row = 9)

            spk7th.grid(column = 1, row = 10)
            ssd7th.grid(column = 2, row = 10)
            lvl7th.grid(column = 3, row = 10)
            spd7th.grid(column = 4, row = 10)
            bon7th.grid(column = 5, row = 10)

            spk8th.grid(column = 1, row = 11)
            ssd8th.grid(column = 2, row = 11)
            lvl8th.grid(column = 3, row = 11)
            spd8th.grid(column = 4, row = 11)
            bon8th.grid(column = 5, row = 11)

            spk9th.grid(column = 1, row = 12)
            ssd9th.grid(column = 2, row = 12)
            lvl9th.grid(column = 3, row = 12)
            spd9th.grid(column = 4, row = 12)
            bon9th.grid(column = 5, row = 12)

            """ Domain/Specialty School Declaration """
            dsslbl = ttk.Label(content, text = "Domains/Specialty School")
            dssbox = ttk.Entry(content, width = 80)
            
            dss0lb = ttk.Label(content, text = "0")
            dss0b1 = ttk.Checkbutton(content)
            dss0b2 = ttk.Checkbutton(content)
            dss0b3 = ttk.Checkbutton(content)
            dss0b4 = ttk.Checkbutton(content)
            dss0b5 = ttk.Checkbutton(content)
            dss0b6 = ttk.Checkbutton(content)
            dss0b7 = ttk.Checkbutton(content)
            dss0b8 = ttk.Checkbutton(content)
            dss0b9 = ttk.Checkbutton(content)
            dss0e1 = ttk.Entry(content, width = 40)
            dss0e2 = ttk.Entry(content, width = 40)
            dss0e3 = ttk.Entry(content, width = 40)
            dss0e4 = ttk.Entry(content, width = 40)
            dss0e5 = ttk.Entry(content, width = 40)
            dss0e6 = ttk.Entry(content, width = 40)

            dss1lb = ttk.Label(content, text = "1")
            dss1b1 = ttk.Checkbutton(content)
            dss1b2 = ttk.Checkbutton(content)
            dss1b3 = ttk.Checkbutton(content)
            dss1b4 = ttk.Checkbutton(content)
            dss1b5 = ttk.Checkbutton(content)
            dss1b6 = ttk.Checkbutton(content)
            dss1b7 = ttk.Checkbutton(content)
            dss1b8 = ttk.Checkbutton(content)
            dss1b9 = ttk.Checkbutton(content)
            dss1e1 = ttk.Entry(content, width = 40)
            dss1e2 = ttk.Entry(content, width = 40)
            dss1e3 = ttk.Entry(content, width = 40)
            dss1e4 = ttk.Entry(content, width = 40)
            dss1e5 = ttk.Entry(content, width = 40)
            dss1e6 = ttk.Entry(content, width = 40)
            
            dss2lb = ttk.Label(content, text = "2")
            dss2b1 = ttk.Checkbutton(content)
            dss2b2 = ttk.Checkbutton(content)
            dss2b3 = ttk.Checkbutton(content)
            dss2b4 = ttk.Checkbutton(content)
            dss2b5 = ttk.Checkbutton(content)
            dss2b6 = ttk.Checkbutton(content)
            dss2b7 = ttk.Checkbutton(content)
            dss2b8 = ttk.Checkbutton(content)
            dss2b9 = ttk.Checkbutton(content)
            dss2e1 = ttk.Entry(content, width = 40)
            dss2e2 = ttk.Entry(content, width = 40)
            dss2e3 = ttk.Entry(content, width = 40)
            dss2e4 = ttk.Entry(content, width = 40)
            dss2e5 = ttk.Entry(content, width = 40)
            dss2e6 = ttk.Entry(content, width = 40)
            
            dss3lb = ttk.Label(content, text = "3")
            dss3b1 = ttk.Checkbutton(content)
            dss3b2 = ttk.Checkbutton(content)
            dss3b3 = ttk.Checkbutton(content)
            dss3b4 = ttk.Checkbutton(content)
            dss3b5 = ttk.Checkbutton(content)
            dss3b6 = ttk.Checkbutton(content)
            dss3b7 = ttk.Checkbutton(content)
            dss3b8 = ttk.Checkbutton(content)
            dss3b9 = ttk.Checkbutton(content)
            dss3e1 = ttk.Entry(content, width = 40)
            dss3e2 = ttk.Entry(content, width = 40)
            dss3e3 = ttk.Entry(content, width = 40)
            dss3e4 = ttk.Entry(content, width = 40)
            dss3e5 = ttk.Entry(content, width = 40)
            dss3e6 = ttk.Entry(content, width = 40)
            
            dss4lb = ttk.Label(content, text = "4")
            dss4b1 = ttk.Checkbutton(content)
            dss4b2 = ttk.Checkbutton(content)
            dss4b3 = ttk.Checkbutton(content)
            dss4b4 = ttk.Checkbutton(content)
            dss4b5 = ttk.Checkbutton(content)
            dss4b6 = ttk.Checkbutton(content)
            dss4b7 = ttk.Checkbutton(content)
            dss4b8 = ttk.Checkbutton(content)
            dss4b9 = ttk.Checkbutton(content)
            dss4e1 = ttk.Entry(content, width = 40)
            dss4e2 = ttk.Entry(content, width = 40)
            dss4e3 = ttk.Entry(content, width = 40)
            dss4e4 = ttk.Entry(content, width = 40)
            dss4e5 = ttk.Entry(content, width = 40)
            dss4e6 = ttk.Entry(content, width = 40)
            
            dss5lb = ttk.Label(content, text = "5")
            dss5b1 = ttk.Checkbutton(content)
            dss5b2 = ttk.Checkbutton(content)
            dss5b3 = ttk.Checkbutton(content)
            dss5b4 = ttk.Checkbutton(content)
            dss5b5 = ttk.Checkbutton(content)
            dss5b6 = ttk.Checkbutton(content)
            dss5b7 = ttk.Checkbutton(content)
            dss5b8 = ttk.Checkbutton(content)
            dss5b9 = ttk.Checkbutton(content)
            dss5e1 = ttk.Entry(content, width = 40)
            dss5e2 = ttk.Entry(content, width = 40)
            dss5e3 = ttk.Entry(content, width = 40)
            dss5e4 = ttk.Entry(content, width = 40)
            dss5e5 = ttk.Entry(content, width = 40)
            dss5e6 = ttk.Entry(content, width = 40)
            
            dss6lb = ttk.Label(content, text = "6")
            dss6b1 = ttk.Checkbutton(content)
            dss6b2 = ttk.Checkbutton(content)
            dss6b3 = ttk.Checkbutton(content)
            dss6b4 = ttk.Checkbutton(content)
            dss6b5 = ttk.Checkbutton(content)
            dss6b6 = ttk.Checkbutton(content)
            dss6b7 = ttk.Checkbutton(content)
            dss6b8 = ttk.Checkbutton(content)
            dss6b9 = ttk.Checkbutton(content)
            dss6e1 = ttk.Entry(content, width = 40)
            dss6e2 = ttk.Entry(content, width = 40)
            dss6e3 = ttk.Entry(content, width = 40)
            dss6e4 = ttk.Entry(content, width = 40)
            dss6e5 = ttk.Entry(content, width = 40)
            dss6e6 = ttk.Entry(content, width = 40)
            
            dss7lb = ttk.Label(content, text = "7")
            dss7b1 = ttk.Checkbutton(content)
            dss7b2 = ttk.Checkbutton(content)
            dss7b3 = ttk.Checkbutton(content)
            dss7b4 = ttk.Checkbutton(content)
            dss7b5 = ttk.Checkbutton(content)
            dss7b6 = ttk.Checkbutton(content)
            dss7b7 = ttk.Checkbutton(content)
            dss7b8 = ttk.Checkbutton(content)
            dss7b9 = ttk.Checkbutton(content)
            dss7e1 = ttk.Entry(content, width = 40)
            dss7e2 = ttk.Entry(content, width = 40)
            dss7e3 = ttk.Entry(content, width = 40)
            dss7e4 = ttk.Entry(content, width = 40)
            dss7e5 = ttk.Entry(content, width = 40)
            dss7e6 = ttk.Entry(content, width = 40)
            
            dss8lb = ttk.Label(content, text = "8")
            dss8b1 = ttk.Checkbutton(content)
            dss8b2 = ttk.Checkbutton(content)
            dss8b3 = ttk.Checkbutton(content)
            dss8b4 = ttk.Checkbutton(content)
            dss8b5 = ttk.Checkbutton(content)
            dss8b6 = ttk.Checkbutton(content)
            dss8b7 = ttk.Checkbutton(content)
            dss8b8 = ttk.Checkbutton(content)
            dss8b9 = ttk.Checkbutton(content)
            dss8e1 = ttk.Entry(content, width = 40)
            dss8e2 = ttk.Entry(content, width = 40)
            dss8e3 = ttk.Entry(content, width = 40)
            dss8e4 = ttk.Entry(content, width = 40)
            dss8e5 = ttk.Entry(content, width = 40)
            dss8e6 = ttk.Entry(content, width = 40)

            dss9lb = ttk.Label(content, text = "9")
            dss9b1 = ttk.Checkbutton(content)
            dss9b2 = ttk.Checkbutton(content)
            dss9b3 = ttk.Checkbutton(content)
            dss9b4 = ttk.Checkbutton(content)
            dss9b5 = ttk.Checkbutton(content)
            dss9b6 = ttk.Checkbutton(content)
            dss9b7 = ttk.Checkbutton(content)
            dss9b8 = ttk.Checkbutton(content)
            dss9b9 = ttk.Checkbutton(content)
            dss9e1 = ttk.Entry(content, width = 40)
            dss9e2 = ttk.Entry(content, width = 40)
            dss9e3 = ttk.Entry(content, width = 40)
            dss9e4 = ttk.Entry(content, width = 40)
            dss9e5 = ttk.Entry(content, width = 40)
            dss9e6 = ttk.Entry(content, width = 40)

            """ Domain/Specialty School """
            dsslbl.grid(column = 6, row = 2, columnspan = 8)
            dssbox.grid(column = 7, row = 3, columnspan = 8)
            
            dss0lb.grid(column = 6, row = 4)
            dss0b1.grid(column = 7, row = 4, sticky=(W))
            dss0b2.grid(column = 7, row = 4)
            dss0b3.grid(column = 7, row = 4, sticky=(E))
            dss0b4.grid(column = 8, row = 4, sticky=(W))
            dss0b5.grid(column = 8, row = 4)
            dss0b6.grid(column = 8, row = 4, sticky=(E))
            dss0b7.grid(column = 9, row = 4, sticky=(W))
            dss0b8.grid(column = 9, row = 4)
            dss0b9.grid(column = 9, row = 4, sticky=(E))
            dss0e1.grid(column = 6, row = 5, columnspan=4)
            dss0e2.grid(column = 10, row = 5, columnspan=4)
            dss0e3.grid(column = 6, row = 6, columnspan=4)
            dss0e4.grid(column = 10, row = 6, columnspan=4)
            dss0e5.grid(column = 6, row = 7, columnspan=4)
            dss0e6.grid(column = 10, row = 7, columnspan=4)

            dss1lb.grid(column = 6, row = 8)
            dss1b1.grid(column = 7, row = 8, sticky=(W))
            dss1b2.grid(column = 7, row = 8)
            dss1b3.grid(column = 7, row = 8, sticky=(E))
            dss1b4.grid(column = 8, row = 8, sticky=(W))
            dss1b5.grid(column = 8, row = 8)
            dss1b6.grid(column = 8, row = 8, sticky=(E))
            dss1b7.grid(column = 9, row = 8, sticky=(W))
            dss1b8.grid(column = 9, row = 8)
            dss1b9.grid(column = 9, row = 8, sticky=(E))
            dss1e1.grid(column = 6, row = 9, columnspan=4)
            dss1e2.grid(column = 10, row = 9, columnspan=4)
            dss1e3.grid(column = 6, row = 10, columnspan=4)
            dss1e4.grid(column = 10, row = 10, columnspan=4)
            dss1e5.grid(column = 6, row = 11, columnspan=4)
            dss1e6.grid(column = 10, row = 11, columnspan=4)
            
            dss2lb.grid(column = 6, row = 12)
            dss2b1.grid(column = 7, row = 12, sticky=(W))
            dss2b2.grid(column = 7, row = 12)
            dss2b3.grid(column = 7, row = 12, sticky=(E))
            dss2b4.grid(column = 8, row = 12, sticky=(W))
            dss2b5.grid(column = 8, row = 12)
            dss2b6.grid(column = 8, row = 12, sticky=(E))
            dss2b7.grid(column = 9, row = 12, sticky=(W))
            dss2b8.grid(column = 9, row = 12)
            dss2b9.grid(column = 9, row = 12, sticky=(E))
            dss2e1.grid(column = 6, row = 13, columnspan=4)
            dss2e2.grid(column = 10, row = 13, columnspan=4)
            dss2e3.grid(column = 6, row = 14, columnspan=4)
            dss2e4.grid(column = 10, row = 14, columnspan=4)
            dss2e5.grid(column = 6, row = 15, columnspan=4)
            dss2e6.grid(column = 10, row = 15, columnspan=4)
            
            dss3lb.grid(column = 6, row = 16)
            dss3b1.grid(column = 7, row = 16, sticky=(W))
            dss3b2.grid(column = 7, row = 16)
            dss3b3.grid(column = 7, row = 16, sticky=(E))
            dss3b4.grid(column = 8, row = 16, sticky=(W))
            dss3b5.grid(column = 8, row = 16)
            dss3b6.grid(column = 8, row = 16, sticky=(E))
            dss3b7.grid(column = 9, row = 16, sticky=(W))
            dss3b8.grid(column = 9, row = 16)
            dss3b9.grid(column = 9, row = 16, sticky=(E))
            dss3e1.grid(column = 6, row = 17, columnspan=4)
            dss3e2.grid(column = 10, row = 17, columnspan=4)
            dss3e3.grid(column = 6, row = 18, columnspan=4)
            dss3e4.grid(column = 10, row = 18, columnspan=4)
            dss3e5.grid(column = 6, row = 19, columnspan=4)
            dss3e6.grid(column = 10, row = 19, columnspan=4)
            
            dss4lb.grid(column = 6, row = 20)
            dss4b1.grid(column = 7, row = 20, sticky=(W))
            dss4b2.grid(column = 7, row = 20)
            dss4b3.grid(column = 7, row = 20, sticky=(E))
            dss4b4.grid(column = 8, row = 20, sticky=(W))
            dss4b5.grid(column = 8, row = 20)
            dss4b6.grid(column = 8, row = 20, sticky=(E))
            dss4b7.grid(column = 9, row = 20, sticky=(W))
            dss4b8.grid(column = 9, row = 20)
            dss4b9.grid(column = 9, row = 20, sticky=(E))
            dss4e1.grid(column = 6, row = 21, columnspan=4)
            dss4e2.grid(column = 10, row = 21, columnspan=4)
            dss4e3.grid(column = 6, row = 22, columnspan=4)
            dss4e4.grid(column = 10, row = 22, columnspan=4)
            dss4e5.grid(column = 6, row = 23, columnspan=4)
            dss4e6.grid(column = 10, row = 23, columnspan=4)
            
            dss5lb.grid(column = 6, row = 24)
            dss5b1.grid(column = 7, row = 24, sticky=(W))
            dss5b2.grid(column = 7, row = 24)
            dss5b3.grid(column = 7, row = 24, sticky=(E))
            dss5b4.grid(column = 8, row = 24, sticky=(W))
            dss5b5.grid(column = 8, row = 24)
            dss5b6.grid(column = 8, row = 24, sticky=(E))
            dss5b7.grid(column = 9, row = 24, sticky=(W))
            dss5b8.grid(column = 9, row = 24)
            dss5b9.grid(column = 9, row = 24, sticky=(E))
            dss5e1.grid(column = 6, row = 25, columnspan=4)
            dss5e2.grid(column = 10, row = 25, columnspan=4)
            dss5e3.grid(column = 6, row = 26, columnspan=4)
            dss5e4.grid(column = 10, row = 26, columnspan=4)
            dss5e5.grid(column = 6, row = 27, columnspan=4)
            dss5e6.grid(column = 10, row = 27, columnspan=4)
            
            dss6lb.grid(column = 6, row = 28)
            dss6b1.grid(column = 7, row = 28, sticky=(W))
            dss6b2.grid(column = 7, row = 28)
            dss6b3.grid(column = 7, row = 28, sticky=(E))
            dss6b4.grid(column = 8, row = 28, sticky=(W))
            dss6b5.grid(column = 8, row = 28)
            dss6b6.grid(column = 8, row = 28, sticky=(E))
            dss6b7.grid(column = 9, row = 28, sticky=(W))
            dss6b8.grid(column = 9, row = 28)
            dss6b9.grid(column = 9, row = 28, sticky=(E))
            dss6e1.grid(column = 6, row = 29, columnspan=4)
            dss6e2.grid(column = 10, row = 29, columnspan=4)
            dss6e3.grid(column = 6, row = 30, columnspan=4)
            dss6e4.grid(column = 10, row = 30, columnspan=4)
            dss6e5.grid(column = 6, row = 31, columnspan=4)
            dss6e6.grid(column = 10, row = 31, columnspan=4)
            
            dss7lb.grid(column = 6, row = 32)
            dss7b1.grid(column = 7, row = 32, sticky=(W))
            dss7b2.grid(column = 7, row = 32)
            dss7b3.grid(column = 7, row = 32, sticky=(E))
            dss7b4.grid(column = 8, row = 32, sticky=(W))
            dss7b5.grid(column = 8, row = 32)
            dss7b6.grid(column = 8, row = 32, sticky=(E))
            dss7b7.grid(column = 9, row = 32, sticky=(W))
            dss7b8.grid(column = 9, row = 32)
            dss7b9.grid(column = 9, row = 32, sticky=(E))
            dss7e1.grid(column = 6, row = 33, columnspan=4)
            dss7e2.grid(column = 10, row = 33, columnspan=4)
            dss7e3.grid(column = 6, row = 34, columnspan=4)
            dss7e4.grid(column = 10, row = 34, columnspan=4)
            dss7e5.grid(column = 6, row = 35, columnspan=4)
            dss7e6.grid(column = 10, row = 35, columnspan=4)
            
            dss8lb.grid(column = 6, row = 36)
            dss8b1.grid(column = 7, row = 36, sticky=(W))
            dss8b2.grid(column = 7, row = 36)
            dss8b3.grid(column = 7, row = 36, sticky=(E))
            dss8b4.grid(column = 8, row = 36, sticky=(W))
            dss8b5.grid(column = 8, row = 36)
            dss8b6.grid(column = 8, row = 36, sticky=(E))
            dss8b7.grid(column = 9, row = 36, sticky=(W))
            dss8b8.grid(column = 9, row = 36)
            dss8b9.grid(column = 9, row = 36, sticky=(E))
            dss8e1.grid(column = 6, row = 37, columnspan=4)
            dss8e2.grid(column = 10, row = 37, columnspan=4)
            dss8e3.grid(column = 6, row = 38, columnspan=4)
            dss8e4.grid(column = 10, row = 38, columnspan=4)
            dss8e5.grid(column = 6, row = 39, columnspan=4)
            dss8e6.grid(column = 10, row = 39, columnspan=4)

            dss9lb.grid(column = 6, row = 40)
            dss9b1.grid(column = 7, row = 40, sticky=(W))
            dss9b2.grid(column = 7, row = 40)
            dss9b3.grid(column = 7, row = 40, sticky=(E))
            dss9b4.grid(column = 8, row = 40, sticky=(W))
            dss9b5.grid(column = 8, row = 40)
            dss9b6.grid(column = 8, row = 40, sticky=(E))
            dss9b7.grid(column = 9, row = 40, sticky=(W))
            dss9b8.grid(column = 9, row = 40)
            dss9b9.grid(column = 9, row = 40, sticky=(E))
            dss9e1.grid(column = 6, row = 41, columnspan=4)
            dss9e2.grid(column = 10, row = 41, columnspan=4)
            dss9e3.grid(column = 6, row = 42, columnspan=4)
            dss9e4.grid(column = 10, row = 42, columnspan=4)
            dss9e5.grid(column = 6, row = 43, columnspan=4)
            dss9e6.grid(column = 10, row = 43, columnspan=4)

            pbuttonlbl.grid( column=1, row=44 )
            pbuttonnew.grid( column=1, row=45, sticky=(W) )
            pbuttonsave.grid( column=2, row=45, sticky=(W) )
            pbuttonload.grid( column=3, row=45, sticky=(W) )
            pbuttonexit.grid( column=4, row=45, sticky=(W) )
            
            character.add(content, text='Spells')

            
if __name__ == '__main__':
    PathfinderGUI().mainloop()
