from tkinter import *
from tkinter import ttk

root = Tk()

content = ttk.Frame(root, padding=(3,3,12,12))
frame = ttk.Frame(content, borderwidth=5, relief="sunken", width=200, height=100)
content.grid(    column=0, row=0)

""" attack stats declaration """
bablbl = ttk.Label(content, text = "      Base Attack Bonus     ", background = 'black', foreground = 'white')
reslbl = ttk.Label(content, text = "        Spell Resistance       ", background = 'black', foreground = 'white')
cmblbl = ttk.Label(content, text = "    CMB    ", background = 'black', foreground = 'white')
cmdlbl = ttk.Label(content, text = "    CMD    ", background = 'black', foreground = 'white')
atkbon = ttk.Entry(content, width = 8)
splres = ttk.Entry(content, width = 8)
cmbtot = ttk.Entry(content, width = 4)
cmbbab = ttk.Entry(content, width = 4)
cmbstr = ttk.Entry(content, width = 4)
cmbsiz = ttk.Entry(content, width = 4)
cmdtot = ttk.Entry(content, width = 4)
cmdcmb = ttk.Entry(content, width = 4)
cmddex = ttk.Entry(content, width = 4)
cmdl10 = ttk.Label(content, text = "10")
cmdp01 = ttk.Label(content, text = "+")
cmdp02 = ttk.Label(content, text = "+")
cmde01 = ttk.Label(content, text = "=")
cmbp01 = ttk.Label(content, text = "+")
cmbp02 = ttk.Label(content, text = "+")
cmbe01 = ttk.Label(content, text = "=")
cmbtotlbl = ttk.Label(content, text = "Total", foreground = 'grey')
cmbbablbl = ttk.Label(content, text = "B.A.B.", foreground = 'grey')
cmbstrlbl = ttk.Label(content, text = "Str Mod", foreground = 'grey')
cmbsizlbl = ttk.Label(content, text = "Size Mod", foreground = 'grey')
cmdtotlbl = ttk.Label(content, text = "Total", foreground = 'grey')
cmdcmblbl = ttk.Label(content, text = "CMB", foreground = 'grey')
cmddexlbl = ttk.Label(content, text = "Dex Mod", foreground = 'grey')

""" attack stats placement """
bablbl.grid(column=1, row=2, columnspan=2, sticky=(W))
reslbl.grid(column=4, row=2, columnspan=2, sticky=(W))
cmblbl.grid(column=1, row=4)
cmdlbl.grid(column=1, row=5)
atkbon.grid(column=3, row=2, sticky=(W))
splres.grid(column=6, row=2, sticky=(W))
cmbtot.grid(column=3, row=4, sticky=(W))
cmbbab.grid(column=4, row=4, sticky=(W))
cmbstr.grid(column=5, row=4)
cmbsiz.grid(column=6, row=4, sticky=(W))
cmdtot.grid(column=3, row=5, sticky=(W))
cmdcmb.grid(column=4, row=5, sticky=(W))
cmddex.grid(column=5, row=5)
cmdl10.grid(column=6, row=5, sticky=(W))
cmdp01.grid(column=5, row=4, sticky=(W))
cmdp02.grid(column=5, row=4, sticky=(E))
cmde01.grid(column=3, row=4, sticky=(E))
cmbp01.grid(column=5, row=5, sticky=(W))
cmbp02.grid(column=5, row=5, sticky=(E))
cmbe01.grid(column=3, row=5, sticky=(E))
cmbtotlbl.grid(column=3, row=3, sticky=(W))
cmbbablbl.grid(column=4, row=3, sticky=(W))
cmbstrlbl.grid(column=5, row=3, sticky=(W))
cmbsizlbl.grid(column=6, row=3, sticky=(W))
cmdcmblbl.grid(column=4, row=6, sticky=(W))
cmdtotlbl.grid(column=3, row=6, sticky=(W))
cmddexlbl.grid(column=5, row=6, sticky=(W))

""" weapons declaration """
weapon1lbllbl = ttk.Label(content, text = "Weapon 1", background = 'black', foreground = 'white')
weapon1atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
weapon1crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
weapon1typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
weapon1rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
weapon1ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
weapon1damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
weapon1lblbox = ttk.Entry(content, width=42)
weapon1atkbox = ttk.Entry(content, width=12)
weapon1crtbox = ttk.Entry(content, width=10)
weapon1typbox = ttk.Entry(content, width=10)
weapon1rngbox = ttk.Entry(content, width=10)
weapon1ammbox = ttk.Entry(content, width=20)
weapon1dambox = ttk.Entry(content, width=23)

weapon2lbllbl = ttk.Label(content, text = "Weapon 2", background = 'black', foreground = 'white')
weapon2atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
weapon2crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
weapon2typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
weapon2rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
weapon2ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
weapon2damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
weapon2lblbox = ttk.Entry(content, width=42)
weapon2atkbox = ttk.Entry(content, width=12)
weapon2crtbox = ttk.Entry(content, width=10)
weapon2typbox = ttk.Entry(content, width=10)
weapon2rngbox = ttk.Entry(content, width=10)
weapon2ammbox = ttk.Entry(content, width=20)
weapon2dambox = ttk.Entry(content, width=23)

weapon3lbllbl = ttk.Label(content, text = "Weapon 3", background = 'black', foreground = 'white')
weapon3atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
weapon3crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
weapon3typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
weapon3rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
weapon3ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
weapon3damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
weapon3lblbox = ttk.Entry(content, width=42)
weapon3atkbox = ttk.Entry(content, width=12)
weapon3crtbox = ttk.Entry(content, width=10)
weapon3typbox = ttk.Entry(content, width=10)
weapon3rngbox = ttk.Entry(content, width=10)
weapon3ammbox = ttk.Entry(content, width=20)
weapon3dambox = ttk.Entry(content, width=23)

weapon4lbllbl = ttk.Label(content, text = "Weapon 4" , background = 'black', foreground = 'white')
weapon4atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
weapon4crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
weapon4typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
weapon4rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
weapon4ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
weapon4damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
weapon4lblbox = ttk.Entry(content, width=42)
weapon4atkbox = ttk.Entry(content, width=12)
weapon4crtbox = ttk.Entry(content, width=10)
weapon4typbox = ttk.Entry(content, width=10)
weapon4rngbox = ttk.Entry(content, width=10)
weapon4ammbox = ttk.Entry(content, width=20)
weapon4dambox = ttk.Entry(content, width=23)

weapon5lbllbl = ttk.Label(content, text = "Weapon 5", background = 'black', foreground = 'white')
weapon5atklbl = ttk.Label(content, text = "Attack Bonus", background = 'black', foreground = 'white')
weapon5crtlbl = ttk.Label(content, text = "Critical", background = 'black', foreground = 'white')
weapon5typlbl = ttk.Label(content, text = "Type", background = 'black', foreground = 'white')
weapon5rnglbl = ttk.Label(content, text = "Range", background = 'black', foreground = 'white')
weapon5ammlbl = ttk.Label(content, text = "Ammunition", background = 'black', foreground = 'white')
weapon5damlbl = ttk.Label(content, text = "Damage", background = 'black', foreground = 'white')
weapon5lblbox = ttk.Entry(content, width=42)
weapon5atkbox = ttk.Entry(content, width=12)
weapon5crtbox = ttk.Entry(content, width=10)
weapon5typbox = ttk.Entry(content, width=10)
weapon5rngbox = ttk.Entry(content, width=10)
weapon5ammbox = ttk.Entry(content, width=20)
weapon5dambox = ttk.Entry(content, width=23)

""" weapons placement """

weapon1lbllbl.grid(column = 1, row = 7, columnspan = 4, sticky = (W))
weapon1atklbl.grid(column = 5, row = 7, columnspan = 1, sticky = (W))
weapon1crtlbl.grid(column = 6, row = 7, columnspan = 1, sticky = (W))
weapon1typlbl.grid(column = 1, row = 9, columnspan = 1, sticky = (W))
weapon1rnglbl.grid(column = 2, row = 9, columnspan = 1, sticky = (W))
weapon1ammlbl.grid(column = 3, row = 9, columnspan = 2, sticky = (W))
weapon1damlbl.grid(column = 5, row = 9, columnspan = 2, sticky = (W))
weapon1lblbox.grid(column = 1, row = 8, columnspan = 4, sticky = (W))
weapon1atkbox.grid(column = 5, row = 8, columnspan = 1, sticky = (W))
weapon1crtbox.grid(column = 6, row = 8, columnspan = 1, sticky = (W))
weapon1typbox.grid(column = 1, row = 10, columnspan = 1, sticky = (W))
weapon1rngbox.grid(column = 2, row = 10, columnspan = 1, sticky = (W))
weapon1ammbox.grid(column = 3, row = 10, columnspan = 2, sticky = (W))
weapon1dambox.grid(column = 5, row = 10, columnspan = 2, sticky = (W))

weapon2lbllbl.grid(column = 1, row = 11, columnspan = 4, sticky = (W))
weapon2atklbl.grid(column = 5, row = 11, columnspan = 1, sticky = (W))
weapon2crtlbl.grid(column = 6, row = 11, columnspan = 1, sticky = (W))
weapon2typlbl.grid(column = 1, row = 13, columnspan = 1, sticky = (W))
weapon2rnglbl.grid(column = 2, row = 13, columnspan = 1, sticky = (W))
weapon2ammlbl.grid(column = 3, row = 13, columnspan = 2, sticky = (W))
weapon2damlbl.grid(column = 5, row = 13, columnspan = 2, sticky = (W))
weapon2lblbox.grid(column = 1, row = 12, columnspan = 4, sticky = (W))
weapon2atkbox.grid(column = 5, row = 12, columnspan = 1, sticky = (W))
weapon2crtbox.grid(column = 6, row = 12, columnspan = 1, sticky = (W))
weapon2typbox.grid(column = 1, row = 14, columnspan = 1, sticky = (W))
weapon2rngbox.grid(column = 2, row = 14, columnspan = 1, sticky = (W))
weapon2ammbox.grid(column = 3, row = 14, columnspan = 2, sticky = (W))
weapon2dambox.grid(column = 5, row = 14, columnspan = 2, sticky = (W))

weapon3lbllbl.grid(column = 1, row = 15, columnspan = 4, sticky = (W))
weapon3atklbl.grid(column = 5, row = 15, columnspan = 1, sticky = (W))
weapon3crtlbl.grid(column = 6, row = 15, columnspan = 1, sticky = (W))
weapon3typlbl.grid(column = 1, row = 17, columnspan = 1, sticky = (W))
weapon3rnglbl.grid(column = 2, row = 17, columnspan = 1, sticky = (W))
weapon3ammlbl.grid(column = 3, row = 17, columnspan = 2, sticky = (W))
weapon3damlbl.grid(column = 5, row = 17, columnspan = 2, sticky = (W))
weapon3lblbox.grid(column = 1, row = 16, columnspan = 4, sticky = (W))
weapon3atkbox.grid(column = 5, row = 16, columnspan = 1, sticky = (W))
weapon3crtbox.grid(column = 6, row = 16, columnspan = 1, sticky = (W))
weapon3typbox.grid(column = 1, row = 18, columnspan = 1, sticky = (W))
weapon3rngbox.grid(column = 2, row = 18, columnspan = 1, sticky = (W))
weapon3ammbox.grid(column = 3, row = 18, columnspan = 2, sticky = (W))
weapon3dambox.grid(column = 5, row = 18, columnspan = 2, sticky = (W))

weapon4lbllbl.grid(column = 1, row = 19, columnspan = 4, sticky = (W))
weapon4atklbl.grid(column = 5, row = 19, columnspan = 1, sticky = (W))
weapon4crtlbl.grid(column = 6, row = 19, columnspan = 1, sticky = (W))
weapon4typlbl.grid(column = 1, row = 21, columnspan = 1, sticky = (W))
weapon4rnglbl.grid(column = 2, row = 21, columnspan = 1, sticky = (W))
weapon4ammlbl.grid(column = 3, row = 21, columnspan = 2, sticky = (W))
weapon4damlbl.grid(column = 5, row = 21, columnspan = 2, sticky = (W))
weapon4lblbox.grid(column = 1, row = 20, columnspan = 4, sticky = (W))
weapon4atkbox.grid(column = 5, row = 20, columnspan = 1, sticky = (W))
weapon4crtbox.grid(column = 6, row = 20, columnspan = 1, sticky = (W))
weapon4typbox.grid(column = 1, row = 22, columnspan = 1, sticky = (W))
weapon4rngbox.grid(column = 2, row = 22, columnspan = 1, sticky = (W))
weapon4ammbox.grid(column = 3, row = 22, columnspan = 2, sticky = (W))
weapon4dambox.grid(column = 5, row = 22, columnspan = 2, sticky = (W))

weapon5lbllbl.grid(column = 1, row = 23, columnspan = 4, sticky = (W))
weapon5atklbl.grid(column = 5, row = 23, columnspan = 1, sticky = (W))
weapon5crtlbl.grid(column = 6, row = 23, columnspan = 1, sticky = (W))
weapon5typlbl.grid(column = 1, row = 25, columnspan = 1, sticky = (W))
weapon5rnglbl.grid(column = 2, row = 25, columnspan = 1, sticky = (W))
weapon5ammlbl.grid(column = 3, row = 25, columnspan = 2, sticky = (W))
weapon5damlbl.grid(column = 5, row = 25, columnspan = 2, sticky = (W))
weapon5lblbox.grid(column = 1, row = 24, columnspan = 4, sticky = (W))
weapon5atkbox.grid(column = 5, row = 24, columnspan = 1, sticky = (W))
weapon5crtbox.grid(column = 6, row = 24, columnspan = 1, sticky = (W))
weapon5typbox.grid(column = 1, row = 26, columnspan = 1, sticky = (W))
weapon5rngbox.grid(column = 2, row = 26, columnspan = 1, sticky = (W))
weapon5ammbox.grid(column = 3, row = 26, columnspan = 2, sticky = (W))
weapon5dambox.grid(column = 5, row = 26, columnspan = 2, sticky = (W))

root.mainloop()
